CREATE TABLE dbo.INFORME_DISPONIBILIDAD
(
    IdInformeDisponibilidad INT IDENTITY CONSTRAINT PK_INFORME_DISPONIBILIDAD PRIMARY KEY,
    IdUnidadFlota INT NOT NULL CONSTRAINT FK_INFORME_UNIDAD REFERENCES dbo.UNIDAD_FLOTA(IdUnidadFlota),
    IdIntervencionMantenimiento INT NULL CONSTRAINT FK_INFORME_INTERVENCION REFERENCES dbo.INTERVENCION_MANTENIMIENTO(IdIntervencionMantenimiento),
    FechaHora DATETIME NOT NULL,
    Disponible BIT NOT NULL,
    EstadoUnidad VARCHAR(30) NOT NULL,
    Observaciones NVARCHAR(1000) NULL,
    Vigente BIT NOT NULL,
    CONSTRAINT UQ_INFORME_UNIDAD UNIQUE(IdInformeDisponibilidad,IdUnidadFlota)
);
GO
CREATE UNIQUE INDEX UX_INFORME_VIGENTE ON dbo.INFORME_DISPONIBILIDAD(IdUnidadFlota) WHERE Vigente=1;
GO
CREATE UNIQUE INDEX UX_INFORME_INTERVENCION ON dbo.INFORME_DISPONIBILIDAD(IdIntervencionMantenimiento) WHERE IdIntervencionMantenimiento IS NOT NULL;
