CREATE TABLE dbo.INTERVENCION_MANTENIMIENTO
(
    IdIntervencionMantenimiento INT IDENTITY CONSTRAINT PK_INTERVENCION_MANTENIMIENTO PRIMARY KEY,
    IdOrdenMantenimiento INT NOT NULL CONSTRAINT FK_INTERVENCION_ORDEN REFERENCES dbo.ORDEN_MANTENIMIENTO(IdOrdenMantenimiento),
    FechaInicio DATETIME NOT NULL,
    FechaFin DATETIME NULL,
    Kilometraje DECIMAL(18,3) NOT NULL CONSTRAINT CK_INTERVENCION_KM CHECK(Kilometraje>=0),
    TrabajoRealizado NVARCHAR(1000) NOT NULL,
    Resultado VARCHAR(30) NOT NULL CONSTRAINT CK_INTERVENCION_RESULTADO CHECK(Resultado IN ('EnCurso','Satisfactoria','RequiereTareas')),
    Observaciones NVARCHAR(1000) NULL,
    CONSTRAINT CK_INTERVENCION_FECHAS CHECK((Resultado='EnCurso' AND FechaFin IS NULL) OR (Resultado<>'EnCurso' AND FechaFin>=FechaInicio AND FechaFin IS NOT NULL))
);
GO
CREATE UNIQUE INDEX UX_INTERVENCION_ACTIVA ON dbo.INTERVENCION_MANTENIMIENTO(IdOrdenMantenimiento) WHERE FechaFin IS NULL;
