CREATE TABLE dbo.PARTE_ESTADO_UNIDAD
(
    IdParteEstadoUnidad INT IDENTITY CONSTRAINT PK_PARTE_ESTADO_UNIDAD PRIMARY KEY,
    IdUnidadFlota INT NOT NULL CONSTRAINT FK_PARTE_UNIDAD REFERENCES dbo.UNIDAD_FLOTA(IdUnidadFlota),
    FechaHora DATETIME NOT NULL,
    Kilometraje DECIMAL(18,3) NOT NULL CONSTRAINT CK_PARTE_KM CHECK(Kilometraje>=0),
    TipoNovedad NVARCHAR(30) NOT NULL,
    Descripcion NVARCHAR(500) NOT NULL,
    RequiereMantenimiento BIT NOT NULL,
    EstadoParte VARCHAR(30) NOT NULL CONSTRAINT CK_PARTE_ESTADO CHECK(EstadoParte IN ('Pendiente','Programado','Resuelto')),
    CONSTRAINT UQ_PARTE_UNIDAD UNIQUE(IdParteEstadoUnidad,IdUnidadFlota)
);
