CREATE TABLE dbo.PLAN_DISTRIBUCION
(
    Id_Plan INT IDENTITY PRIMARY KEY,
    Id_Requerimiento INT NOT NULL UNIQUE REFERENCES dbo.REQUERIMIENTO_DISTRIBUCION(Id_Requerimiento),
    Numero NVARCHAR(50) NOT NULL UNIQUE,
    Fecha DATETIME NOT NULL,
    Estado VARCHAR(20) NOT NULL CHECK (Estado = 'Confirmado')
);
