CREATE TABLE [dbo].[ROL_COMPONENTE] (
    [Id_Rol]        INT NOT NULL,
    [Id_Componente] INT NOT NULL,
    CONSTRAINT [PK_ROL_COMPONENTE] PRIMARY KEY CLUSTERED ([Id_Rol] ASC, [Id_Componente] ASC),
    CONSTRAINT [CK_ROL_COMPONENTE_NO_SELF] CHECK ([Id_Rol]<>[Id_Componente]),
    CONSTRAINT [FK_ROL_COMPONENTE_COMPONENTE] FOREIGN KEY ([Id_Componente]) REFERENCES [dbo].[PERMISO] ([Id_Permiso]),
    CONSTRAINT [FK_ROL_COMPONENTE_ROL] FOREIGN KEY ([Id_Rol]) REFERENCES [dbo].[PERMISO] ([Id_Permiso])
);

