CREATE TABLE dbo.UNIDAD_FLOTA
(
    IdUnidadFlota INT IDENTITY CONSTRAINT PK_UNIDAD_FLOTA PRIMARY KEY,
    Dominio NVARCHAR(10) NOT NULL CONSTRAINT UQ_UNIDAD_DOMINIO UNIQUE,
    Tipo NVARCHAR(50) NOT NULL,
    Marca NVARCHAR(50) NOT NULL,
    Modelo NVARCHAR(50) NOT NULL,
    Anio INT NOT NULL CONSTRAINT CK_UNIDAD_ANIO CHECK(Anio BETWEEN 1900 AND 2100),
    Capacidad DECIMAL(18,3) NOT NULL CONSTRAINT CK_UNIDAD_CAPACIDAD CHECK(Capacidad>0),
    KilometrajeActual DECIMAL(18,3) NOT NULL CONSTRAINT CK_UNIDAD_KM CHECK(KilometrajeActual>=0),
    EstadoOperativo VARCHAR(30) NOT NULL CONSTRAINT CK_UNIDAD_ESTADO CHECK(EstadoOperativo IN ('Disponible','FueraServicio','EnMantenimiento','PendienteVerificacion')),
    Activa BIT NOT NULL CONSTRAINT DF_UNIDAD_ACTIVA DEFAULT 1
);
