using System;
using System.Drawing;
using System.Windows.Forms;
namespace IngSoft
{
    partial class FrmEjecucionViaje
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel layout;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            SuspendLayout();
            layout = new TableLayoutPanel();
            layout.Dock = DockStyle.Fill;
            layout.ColumnCount = 1;
            layout.RowCount = 4;
            layout.Padding = new Padding(8);
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70));
            grp0 = new GroupBox();
            grp0.Name = "grp0";
            grp0.Text = "Viajes";
            grp0.Dock = DockStyle.Fill;
            panel0 = new FlowLayoutPanel();
            panel0.Name = "panel0";
            panel0.Dock = DockStyle.Top; panel0.AutoSize = true; panel0.WrapContents = true; panel0.Padding = new Padding(4);
            btnActualizar = new Button();
            btnActualizar.Name = "btnActualizar";
            btnActualizar.Text = "Actualizar";
            btnActualizar.Width = 130; btnActualizar.AutoSize = true; btnActualizar.Click += btnActualizar_Click;
            panel0.Controls.Add(btnActualizar);
            dgvViajes = new DataGridView();
            dgvViajes.Name = "dgvViajes";
            dgvViajes.Dock = DockStyle.Fill; dgvViajes.AutoGenerateColumns = false; dgvViajes.AllowUserToAddRows = false; dgvViajes.AllowUserToDeleteRows = false; dgvViajes.MultiSelect = false; dgvViajes.ReadOnly = true; dgvViajes.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvViajesNumero = new DataGridViewTextBoxColumn();
            dgvViajesNumero.Name = "dgvViajesNumero";
            dgvViajesNumero.DataPropertyName = "Numero"; dgvViajesNumero.HeaderText = "Viaje"; dgvViajesNumero.ReadOnly = false; 
            dgvViajes.Columns.Add(dgvViajesNumero);
            dgvViajesFechaPrevista = new DataGridViewTextBoxColumn();
            dgvViajesFechaPrevista.Name = "dgvViajesFechaPrevista";
            dgvViajesFechaPrevista.DataPropertyName = "FechaPrevista"; dgvViajesFechaPrevista.HeaderText = "Fecha prevista"; dgvViajesFechaPrevista.ReadOnly = false; dgvViajesFechaPrevista.DefaultCellStyle.Format = "g";
            dgvViajes.Columns.Add(dgvViajesFechaPrevista);
            dgvViajesEstado = new DataGridViewTextBoxColumn();
            dgvViajesEstado.Name = "dgvViajesEstado";
            dgvViajesEstado.DataPropertyName = "Estado"; dgvViajesEstado.HeaderText = "Estado"; dgvViajesEstado.ReadOnly = false; 
            dgvViajes.Columns.Add(dgvViajesEstado);
            dgvViajesFechaInicio = new DataGridViewTextBoxColumn();
            dgvViajesFechaInicio.Name = "dgvViajesFechaInicio";
            dgvViajesFechaInicio.DataPropertyName = "FechaInicio"; dgvViajesFechaInicio.HeaderText = "Inicio"; dgvViajesFechaInicio.ReadOnly = false; dgvViajesFechaInicio.DefaultCellStyle.Format = "g";
            dgvViajes.Columns.Add(dgvViajesFechaInicio);
            grp0.Controls.Add(dgvViajes);
            grp0.Controls.Add(panel0);
            grp1 = new GroupBox();
            grp1.Name = "grp1";
            grp1.Text = "Documento y carga de despacho";
            grp1.Dock = DockStyle.Fill;
            panel1 = new FlowLayoutPanel();
            panel1.Name = "panel1";
            panel1.Dock = DockStyle.Top; panel1.AutoSize = true; panel1.WrapContents = true; panel1.Padding = new Padding(4);
            lblDocumento = new Label();
            lblDocumento.Name = "lblDocumento";
            lblDocumento.Width = 130; lblDocumento.AutoSize = true; lblDocumento.Margin = new Padding(4,8,4,4);
            panel1.Controls.Add(lblDocumento);
            dgvCarga = new DataGridView();
            dgvCarga.Name = "dgvCarga";
            dgvCarga.Dock = DockStyle.Fill; dgvCarga.AutoGenerateColumns = false; dgvCarga.AllowUserToAddRows = false; dgvCarga.AllowUserToDeleteRows = false; dgvCarga.MultiSelect = false; dgvCarga.ReadOnly = true; dgvCarga.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvCargaCodigo = new DataGridViewTextBoxColumn();
            dgvCargaCodigo.Name = "dgvCargaCodigo";
            dgvCargaCodigo.DataPropertyName = "Codigo"; dgvCargaCodigo.HeaderText = "Código"; dgvCargaCodigo.ReadOnly = false; 
            dgvCarga.Columns.Add(dgvCargaCodigo);
            dgvCargaDescripcion = new DataGridViewTextBoxColumn();
            dgvCargaDescripcion.Name = "dgvCargaDescripcion";
            dgvCargaDescripcion.DataPropertyName = "Descripcion"; dgvCargaDescripcion.HeaderText = "Mercadería"; dgvCargaDescripcion.ReadOnly = false; 
            dgvCarga.Columns.Add(dgvCargaDescripcion);
            dgvCargaCantidadPrevista = new DataGridViewTextBoxColumn();
            dgvCargaCantidadPrevista.Name = "dgvCargaCantidadPrevista";
            dgvCargaCantidadPrevista.DataPropertyName = "CantidadPrevista"; dgvCargaCantidadPrevista.HeaderText = "Prevista"; dgvCargaCantidadPrevista.ReadOnly = false; dgvCargaCantidadPrevista.DefaultCellStyle.Format = "N3";
            dgvCarga.Columns.Add(dgvCargaCantidadPrevista);
            dgvCargaCantidadPreparada = new DataGridViewTextBoxColumn();
            dgvCargaCantidadPreparada.Name = "dgvCargaCantidadPreparada";
            dgvCargaCantidadPreparada.DataPropertyName = "CantidadPreparada"; dgvCargaCantidadPreparada.HeaderText = "Preparada"; dgvCargaCantidadPreparada.ReadOnly = false; dgvCargaCantidadPreparada.DefaultCellStyle.Format = "N3";
            dgvCarga.Columns.Add(dgvCargaCantidadPreparada);
            grp1.Controls.Add(dgvCarga);
            grp1.Controls.Add(panel1);
            grp2 = new GroupBox();
            grp2.Name = "grp2";
            grp2.Text = "Entregas previstas";
            grp2.Dock = DockStyle.Fill;
            panel2 = new FlowLayoutPanel();
            panel2.Name = "panel2";
            panel2.Dock = DockStyle.Top; panel2.AutoSize = true; panel2.WrapContents = true; panel2.Padding = new Padding(4);
            dgvEntregas = new DataGridView();
            dgvEntregas.Name = "dgvEntregas";
            dgvEntregas.Dock = DockStyle.Fill; dgvEntregas.AutoGenerateColumns = false; dgvEntregas.AllowUserToAddRows = false; dgvEntregas.AllowUserToDeleteRows = false; dgvEntregas.MultiSelect = false; dgvEntregas.ReadOnly = true; dgvEntregas.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvEntregasDestino = new DataGridViewTextBoxColumn();
            dgvEntregasDestino.Name = "dgvEntregasDestino";
            dgvEntregasDestino.DataPropertyName = "Destino"; dgvEntregasDestino.HeaderText = "Destino"; dgvEntregasDestino.ReadOnly = false; 
            dgvEntregas.Columns.Add(dgvEntregasDestino);
            dgvEntregasFechaPrevista = new DataGridViewTextBoxColumn();
            dgvEntregasFechaPrevista.Name = "dgvEntregasFechaPrevista";
            dgvEntregasFechaPrevista.DataPropertyName = "FechaPrevista"; dgvEntregasFechaPrevista.HeaderText = "Fecha prevista"; dgvEntregasFechaPrevista.ReadOnly = false; dgvEntregasFechaPrevista.DefaultCellStyle.Format = "g";
            dgvEntregas.Columns.Add(dgvEntregasFechaPrevista);
            dgvEntregasEstado = new DataGridViewTextBoxColumn();
            dgvEntregasEstado.Name = "dgvEntregasEstado";
            dgvEntregasEstado.DataPropertyName = "Estado"; dgvEntregasEstado.HeaderText = "Estado"; dgvEntregasEstado.ReadOnly = false; 
            dgvEntregas.Columns.Add(dgvEntregasEstado);
            grp2.Controls.Add(dgvEntregas);
            grp2.Controls.Add(panel2);
            grp3 = new GroupBox();
            grp3.Name = "grp3";
            grp3.Text = "Inicio del viaje";
            grp3.Dock = DockStyle.Fill;
            panel3 = new FlowLayoutPanel();
            panel3.Name = "panel3";
            panel3.Dock = DockStyle.Top; panel3.AutoSize = true; panel3.WrapContents = true; panel3.Padding = new Padding(4);
            btnIniciar = new Button();
            btnIniciar.Name = "btnIniciar";
            btnIniciar.Text = "Confirmar inicio";
            btnIniciar.Width = 130; btnIniciar.AutoSize = true; btnIniciar.Click += btnIniciar_Click;
            panel3.Controls.Add(btnIniciar);
            grp3.Controls.Add(panel3);
            layout.Controls.Add(grp0, 0, 0);
            layout.Controls.Add(grp1, 0, 1);
            layout.Controls.Add(grp2, 0, 2);
            layout.Controls.Add(grp3, 0, 3);
            Controls.Add(layout);
            Name = "FrmEjecucionViaje"; Text = "Registrar ejecución de viaje";
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1120, 820); MinimumSize = new Size(960, 760);
            ResumeLayout(false);
        }
        private GroupBox grp0;
        private FlowLayoutPanel panel0;
        private Button btnActualizar;
        private DataGridView dgvViajes;
        private DataGridViewTextBoxColumn dgvViajesNumero;
        private DataGridViewTextBoxColumn dgvViajesFechaPrevista;
        private DataGridViewTextBoxColumn dgvViajesEstado;
        private DataGridViewTextBoxColumn dgvViajesFechaInicio;
        private GroupBox grp1;
        private FlowLayoutPanel panel1;
        private Label lblDocumento;
        private DataGridView dgvCarga;
        private DataGridViewTextBoxColumn dgvCargaCodigo;
        private DataGridViewTextBoxColumn dgvCargaDescripcion;
        private DataGridViewTextBoxColumn dgvCargaCantidadPrevista;
        private DataGridViewTextBoxColumn dgvCargaCantidadPreparada;
        private GroupBox grp2;
        private FlowLayoutPanel panel2;
        private DataGridView dgvEntregas;
        private DataGridViewTextBoxColumn dgvEntregasDestino;
        private DataGridViewTextBoxColumn dgvEntregasFechaPrevista;
        private DataGridViewTextBoxColumn dgvEntregasEstado;
        private GroupBox grp3;
        private FlowLayoutPanel panel3;
        private Button btnIniciar;
    }
}
