using System;
using System.Drawing;
using System.Windows.Forms;
namespace IngSoft
{
    partial class FrmPlanificacionDistribucion
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel layout;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            SuspendLayout();
            layout = new TableLayoutPanel();
            layout.Dock = DockStyle.Fill;
            layout.ColumnCount = 1;
            layout.RowCount = 5;
            layout.Padding = new Padding(8);
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 140));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 72));
            grp0 = new GroupBox();
            grp0.Name = "grp0";
            grp0.Text = "Requerimiento y plan";
            grp0.Dock = DockStyle.Fill;
            panel0 = new FlowLayoutPanel();
            panel0.Name = "panel0";
            panel0.Dock = DockStyle.Top; panel0.AutoSize = true; panel0.WrapContents = true; panel0.Padding = new Padding(4);
            lblRequerimiento = new Label();
            lblRequerimiento.Name = "lblRequerimiento";
            lblRequerimiento.Text = "Pendiente";
            lblRequerimiento.Width = 130; lblRequerimiento.AutoSize = true; lblRequerimiento.Margin = new Padding(4,8,4,4);
            panel0.Controls.Add(lblRequerimiento);
            cmbRequerimiento = new ComboBox();
            cmbRequerimiento.Name = "cmbRequerimiento";
            cmbRequerimiento.Width = 160; cmbRequerimiento.DropDownStyle = ComboBoxStyle.DropDownList; cmbRequerimiento.DisplayMember = "Numero"; cmbRequerimiento.ValueMember = "IdRequerimiento";
            panel0.Controls.Add(cmbRequerimiento);
            txtOrigenSeleccionado = new TextBox();
            txtOrigenSeleccionado.Name = "txtOrigenSeleccionado";
            txtOrigenSeleccionado.Width = 190; txtOrigenSeleccionado.MaxLength = 200;
            panel0.Controls.Add(txtOrigenSeleccionado);
            lblPlan = new Label();
            lblPlan.Name = "lblPlan";
            lblPlan.Text = "N.º plan";
            lblPlan.Width = 130; lblPlan.AutoSize = true; lblPlan.Margin = new Padding(4,8,4,4);
            panel0.Controls.Add(lblPlan);
            txtPlan = new TextBox();
            txtPlan.Name = "txtPlan";
            txtPlan.Width = 130; txtPlan.MaxLength = 50;
            panel0.Controls.Add(txtPlan);
            btnActualizar = new Button();
            btnActualizar.Name = "btnActualizar";
            btnActualizar.Text = "Actualizar";
            btnActualizar.Width = 130; btnActualizar.AutoSize = true; btnActualizar.Click += btnActualizar_Click;
            panel0.Controls.Add(btnActualizar);
            panel0.SetFlowBreak(btnActualizar, true);
            lblNuevoReq = new Label();
            lblNuevoReq.Name = "lblNuevoReq";
            lblNuevoReq.Text = "Nuevo requerimiento: número / origen";
            lblNuevoReq.Width = 130; lblNuevoReq.AutoSize = true; lblNuevoReq.Margin = new Padding(4,8,4,4);
            panel0.Controls.Add(lblNuevoReq);
            txtRequerimiento = new TextBox();
            txtRequerimiento.Name = "txtRequerimiento";
            txtRequerimiento.Width = 130; txtRequerimiento.MaxLength = 50;
            panel0.Controls.Add(txtRequerimiento);
            txtOrigen = new TextBox();
            txtOrigen.Name = "txtOrigen";
            txtOrigen.Width = 180; txtOrigen.MaxLength = 200;
            panel0.Controls.Add(txtOrigen);
            btnRecibir = new Button();
            btnRecibir.Name = "btnRecibir";
            btnRecibir.Text = "Recibir requerimiento";
            btnRecibir.Width = 130; btnRecibir.AutoSize = true; btnRecibir.Click += btnRecibir_Click;
            panel0.Controls.Add(btnRecibir);
            grp0.Controls.Add(panel0);
            grp1 = new GroupBox();
            grp1.Name = "grp1";
            grp1.Text = "Viajes del plan";
            grp1.Dock = DockStyle.Fill;
            panel1 = new FlowLayoutPanel();
            panel1.Name = "panel1";
            panel1.Dock = DockStyle.Top; panel1.AutoSize = true; panel1.WrapContents = true; panel1.Padding = new Padding(4);
            lblViaje = new Label();
            lblViaje.Name = "lblViaje";
            lblViaje.Text = "N.º viaje";
            lblViaje.Width = 130; lblViaje.AutoSize = true; lblViaje.Margin = new Padding(4,8,4,4);
            panel1.Controls.Add(lblViaje);
            txtViaje = new TextBox();
            txtViaje.Name = "txtViaje";
            txtViaje.Width = 130; txtViaje.MaxLength = 50;
            panel1.Controls.Add(txtViaje);
            lblFechaViaje = new Label();
            lblFechaViaje.Name = "lblFechaViaje";
            lblFechaViaje.Text = "Salida prevista";
            lblFechaViaje.Width = 130; lblFechaViaje.AutoSize = true; lblFechaViaje.Margin = new Padding(4,8,4,4);
            panel1.Controls.Add(lblFechaViaje);
            dtpViaje = new DateTimePicker();
            dtpViaje.Name = "dtpViaje";
            dtpViaje.Width = 155; dtpViaje.Format = DateTimePickerFormat.Custom; dtpViaje.CustomFormat = "dd/MM/yyyy HH:mm";
            panel1.Controls.Add(dtpViaje);
            btnViaje = new Button();
            btnViaje.Name = "btnViaje";
            btnViaje.Text = "Agregar viaje";
            btnViaje.Width = 130; btnViaje.AutoSize = true; btnViaje.Click += btnViaje_Click;
            panel1.Controls.Add(btnViaje);
            btnQuitarViaje = new Button();
            btnQuitarViaje.Name = "btnQuitarViaje";
            btnQuitarViaje.Text = "Quitar viaje";
            btnQuitarViaje.Width = 130; btnQuitarViaje.AutoSize = true; btnQuitarViaje.Click += btnQuitarViaje_Click;
            panel1.Controls.Add(btnQuitarViaje);
            dgvViajes = new DataGridView();
            dgvViajes.Name = "dgvViajes";
            dgvViajes.Dock = DockStyle.Fill; dgvViajes.AutoGenerateColumns = false; dgvViajes.AllowUserToAddRows = false; dgvViajes.AllowUserToDeleteRows = false; dgvViajes.MultiSelect = false; dgvViajes.ReadOnly = false; dgvViajes.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvViajesNumero = new DataGridViewTextBoxColumn();
            dgvViajesNumero.Name = "dgvViajesNumero";
            dgvViajesNumero.DataPropertyName = "Numero"; dgvViajesNumero.HeaderText = "Número"; dgvViajesNumero.ReadOnly = false; 
            dgvViajes.Columns.Add(dgvViajesNumero);
            dgvViajesFechaPrevista = new DataGridViewTextBoxColumn();
            dgvViajesFechaPrevista.Name = "dgvViajesFechaPrevista";
            dgvViajesFechaPrevista.DataPropertyName = "FechaPrevista"; dgvViajesFechaPrevista.HeaderText = "Salida prevista"; dgvViajesFechaPrevista.ReadOnly = false; dgvViajesFechaPrevista.DefaultCellStyle.Format = "g";
            dgvViajes.Columns.Add(dgvViajesFechaPrevista);
            grp1.Controls.Add(dgvViajes);
            grp1.Controls.Add(panel1);
            grp2 = new GroupBox();
            grp2.Name = "grp2";
            grp2.Text = "Entregas del viaje seleccionado";
            grp2.Dock = DockStyle.Fill;
            panel2 = new FlowLayoutPanel();
            panel2.Name = "panel2";
            panel2.Dock = DockStyle.Top; panel2.AutoSize = true; panel2.WrapContents = true; panel2.Padding = new Padding(4);
            lblDestino = new Label();
            lblDestino.Name = "lblDestino";
            lblDestino.Text = "Destino";
            lblDestino.Width = 130; lblDestino.AutoSize = true; lblDestino.Margin = new Padding(4,8,4,4);
            panel2.Controls.Add(lblDestino);
            txtDestino = new TextBox();
            txtDestino.Name = "txtDestino";
            txtDestino.Width = 230; txtDestino.MaxLength = 200;
            panel2.Controls.Add(txtDestino);
            dtpEntrega = new DateTimePicker();
            dtpEntrega.Name = "dtpEntrega";
            dtpEntrega.Width = 155; dtpEntrega.Format = DateTimePickerFormat.Custom; dtpEntrega.CustomFormat = "dd/MM/yyyy HH:mm";
            panel2.Controls.Add(dtpEntrega);
            btnEntrega = new Button();
            btnEntrega.Name = "btnEntrega";
            btnEntrega.Text = "Agregar entrega";
            btnEntrega.Width = 130; btnEntrega.AutoSize = true; btnEntrega.Click += btnEntrega_Click;
            panel2.Controls.Add(btnEntrega);
            btnQuitarEntrega = new Button();
            btnQuitarEntrega.Name = "btnQuitarEntrega";
            btnQuitarEntrega.Text = "Quitar entrega";
            btnQuitarEntrega.Width = 130; btnQuitarEntrega.AutoSize = true; btnQuitarEntrega.Click += btnQuitarEntrega_Click;
            panel2.Controls.Add(btnQuitarEntrega);
            dgvEntregas = new DataGridView();
            dgvEntregas.Name = "dgvEntregas";
            dgvEntregas.Dock = DockStyle.Fill; dgvEntregas.AutoGenerateColumns = false; dgvEntregas.AllowUserToAddRows = false; dgvEntregas.AllowUserToDeleteRows = false; dgvEntregas.MultiSelect = false; dgvEntregas.ReadOnly = false; dgvEntregas.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvEntregasDestino = new DataGridViewTextBoxColumn();
            dgvEntregasDestino.Name = "dgvEntregasDestino";
            dgvEntregasDestino.DataPropertyName = "Destino"; dgvEntregasDestino.HeaderText = "Destino"; dgvEntregasDestino.ReadOnly = false; 
            dgvEntregas.Columns.Add(dgvEntregasDestino);
            dgvEntregasFechaPrevista = new DataGridViewTextBoxColumn();
            dgvEntregasFechaPrevista.Name = "dgvEntregasFechaPrevista";
            dgvEntregasFechaPrevista.DataPropertyName = "FechaPrevista"; dgvEntregasFechaPrevista.HeaderText = "Fecha prevista"; dgvEntregasFechaPrevista.ReadOnly = false; dgvEntregasFechaPrevista.DefaultCellStyle.Format = "g";
            dgvEntregas.Columns.Add(dgvEntregasFechaPrevista);
            grp2.Controls.Add(dgvEntregas);
            grp2.Controls.Add(panel2);
            grp3 = new GroupBox();
            grp3.Name = "grp3";
            grp3.Text = "Carga prevista del viaje seleccionado";
            grp3.Dock = DockStyle.Fill;
            panel3 = new FlowLayoutPanel();
            panel3.Name = "panel3";
            panel3.Dock = DockStyle.Top; panel3.AutoSize = true; panel3.WrapContents = true; panel3.Padding = new Padding(4);
            cmbMercaderia = new ComboBox();
            cmbMercaderia.Name = "cmbMercaderia";
            cmbMercaderia.Width = 200; cmbMercaderia.DropDownStyle = ComboBoxStyle.DropDownList; cmbMercaderia.DisplayMember = "Etiqueta"; cmbMercaderia.ValueMember = "IdMercaderia";
            panel3.Controls.Add(cmbMercaderia);
            lblCantidad = new Label();
            lblCantidad.Name = "lblCantidad";
            lblCantidad.Text = "Cantidad prevista";
            lblCantidad.Width = 130; lblCantidad.AutoSize = true; lblCantidad.Margin = new Padding(4,8,4,4);
            panel3.Controls.Add(lblCantidad);
            nudCantidad = new NumericUpDown();
            nudCantidad.Name = "nudCantidad";
            nudCantidad.Width = 130; nudCantidad.DecimalPlaces = 3; nudCantidad.Maximum = 999999999m;
            panel3.Controls.Add(nudCantidad);
            btnCarga = new Button();
            btnCarga.Name = "btnCarga";
            btnCarga.Text = "Agregar carga";
            btnCarga.Width = 130; btnCarga.AutoSize = true; btnCarga.Click += btnCarga_Click;
            panel3.Controls.Add(btnCarga);
            btnQuitarCarga = new Button();
            btnQuitarCarga.Name = "btnQuitarCarga";
            btnQuitarCarga.Text = "Quitar carga";
            btnQuitarCarga.Width = 130; btnQuitarCarga.AutoSize = true; btnQuitarCarga.Click += btnQuitarCarga_Click;
            panel3.Controls.Add(btnQuitarCarga);
            dgvCarga = new DataGridView();
            dgvCarga.Name = "dgvCarga";
            dgvCarga.Dock = DockStyle.Fill; dgvCarga.AutoGenerateColumns = false; dgvCarga.AllowUserToAddRows = false; dgvCarga.AllowUserToDeleteRows = false; dgvCarga.MultiSelect = false; dgvCarga.ReadOnly = false; dgvCarga.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvCargaIdMercaderia = new DataGridViewComboBoxColumn();
            dgvCargaIdMercaderia.Name = "dgvCargaIdMercaderia";
            dgvCargaIdMercaderia.DataPropertyName = "IdMercaderia"; dgvCargaIdMercaderia.HeaderText = "Mercadería"; dgvCargaIdMercaderia.ReadOnly = true; 
            dgvCarga.Columns.Add(dgvCargaIdMercaderia);
            dgvCargaCantidadPrevista = new DataGridViewTextBoxColumn();
            dgvCargaCantidadPrevista.Name = "dgvCargaCantidadPrevista";
            dgvCargaCantidadPrevista.DataPropertyName = "CantidadPrevista"; dgvCargaCantidadPrevista.HeaderText = "Cantidad prevista"; dgvCargaCantidadPrevista.ReadOnly = false; dgvCargaCantidadPrevista.DefaultCellStyle.Format = "N3";
            dgvCarga.Columns.Add(dgvCargaCantidadPrevista);
            grp3.Controls.Add(dgvCarga);
            grp3.Controls.Add(panel3);
            grp4 = new GroupBox();
            grp4.Name = "grp4";
            grp4.Text = "Alta de producto en catálogo";
            grp4.Dock = DockStyle.Fill;
            panel4 = new FlowLayoutPanel();
            panel4.Name = "panel4";
            panel4.Dock = DockStyle.Top; panel4.AutoSize = true; panel4.WrapContents = true; panel4.Padding = new Padding(4);
            lblCodigo = new Label();
            lblCodigo.Name = "lblCodigo";
            lblCodigo.Text = "Código";
            lblCodigo.Width = 130; lblCodigo.AutoSize = true; lblCodigo.Margin = new Padding(4,8,4,4);
            panel4.Controls.Add(lblCodigo);
            txtCodigo = new TextBox();
            txtCodigo.Name = "txtCodigo";
            txtCodigo.Width = 130; txtCodigo.MaxLength = 50;
            panel4.Controls.Add(txtCodigo);
            lblDescripcion = new Label();
            lblDescripcion.Name = "lblDescripcion";
            lblDescripcion.Text = "Descripción";
            lblDescripcion.Width = 130; lblDescripcion.AutoSize = true; lblDescripcion.Margin = new Padding(4,8,4,4);
            panel4.Controls.Add(lblDescripcion);
            txtDescripcion = new TextBox();
            txtDescripcion.Name = "txtDescripcion";
            txtDescripcion.Width = 230; txtDescripcion.MaxLength = 200;
            panel4.Controls.Add(txtDescripcion);
            btnProducto = new Button();
            btnProducto.Name = "btnProducto";
            btnProducto.Text = "Crear producto";
            btnProducto.Width = 130; btnProducto.AutoSize = true; btnProducto.Click += btnProducto_Click;
            panel4.Controls.Add(btnProducto);
            btnConfirmar = new Button();
            btnConfirmar.Name = "btnConfirmar";
            btnConfirmar.Text = "Confirmar plan";
            btnConfirmar.Width = 130; btnConfirmar.AutoSize = true; btnConfirmar.Click += btnConfirmar_Click;
            panel4.Controls.Add(btnConfirmar);
            grp4.Controls.Add(panel4);
            layout.Controls.Add(grp0, 0, 0);
            layout.Controls.Add(grp1, 0, 1);
            layout.Controls.Add(grp2, 0, 2);
            layout.Controls.Add(grp3, 0, 3);
            layout.Controls.Add(grp4, 0, 4);
            Controls.Add(layout);
            Name = "FrmPlanificacionDistribucion"; Text = "Planificar distribución";
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1120, 820); MinimumSize = new Size(960, 760);
            ResumeLayout(false);
        }
        private GroupBox grp0;
        private FlowLayoutPanel panel0;
        private Label lblRequerimiento;
        private ComboBox cmbRequerimiento;
        private TextBox txtOrigenSeleccionado;
        private Label lblPlan;
        private TextBox txtPlan;
        private Button btnActualizar;
        private Label lblNuevoReq;
        private TextBox txtRequerimiento;
        private TextBox txtOrigen;
        private Button btnRecibir;
        private GroupBox grp1;
        private FlowLayoutPanel panel1;
        private Label lblViaje;
        private TextBox txtViaje;
        private Label lblFechaViaje;
        private DateTimePicker dtpViaje;
        private Button btnViaje;
        private Button btnQuitarViaje;
        private DataGridView dgvViajes;
        private DataGridViewTextBoxColumn dgvViajesNumero;
        private DataGridViewTextBoxColumn dgvViajesFechaPrevista;
        private GroupBox grp2;
        private FlowLayoutPanel panel2;
        private Label lblDestino;
        private TextBox txtDestino;
        private DateTimePicker dtpEntrega;
        private Button btnEntrega;
        private Button btnQuitarEntrega;
        private DataGridView dgvEntregas;
        private DataGridViewTextBoxColumn dgvEntregasDestino;
        private DataGridViewTextBoxColumn dgvEntregasFechaPrevista;
        private GroupBox grp3;
        private FlowLayoutPanel panel3;
        private ComboBox cmbMercaderia;
        private Label lblCantidad;
        private NumericUpDown nudCantidad;
        private Button btnCarga;
        private Button btnQuitarCarga;
        private DataGridView dgvCarga;
        private DataGridViewComboBoxColumn dgvCargaIdMercaderia;
        private DataGridViewTextBoxColumn dgvCargaCantidadPrevista;
        private GroupBox grp4;
        private FlowLayoutPanel panel4;
        private Label lblCodigo;
        private TextBox txtCodigo;
        private Label lblDescripcion;
        private TextBox txtDescripcion;
        private Button btnProducto;
        private Button btnConfirmar;
    }
}
