using System;
using System.Drawing;
using System.Windows.Forms;
namespace IngSoft
{
    partial class FrmPrepararDespacho
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel layout;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            SuspendLayout();
            layout = new TableLayoutPanel();
            layout.Dock = DockStyle.Fill;
            layout.ColumnCount = 1;
            layout.RowCount = 3;
            layout.Padding = new Padding(4);
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            grp0 = new GroupBox();
            grp0.Name = "grp0";
            grp0.Text = "Viajes y estado de preparación";
            grp0.Dock = DockStyle.Fill;
            panel0 = new FlowLayoutPanel();
            panel0.Name = "panel0";
            panel0.Dock = DockStyle.Top; panel0.AutoSize = true; panel0.WrapContents = true; panel0.Padding = new Padding(2);
            btnActualizar = new Button();
            btnActualizar.Name = "btnActualizar";
            btnActualizar.Text = "Actualizar";
            btnActualizar.AutoSize = true; btnActualizar.AutoSizeMode = AutoSizeMode.GrowAndShrink; btnActualizar.MinimumSize = new Size(80, 26); btnActualizar.Padding = new Padding(4, 0, 4, 0); btnActualizar.Click += btnActualizar_Click;
            panel0.Controls.Add(btnActualizar);
            dgvViajes = new DataGridView();
            dgvViajes.Name = "dgvViajes";
            dgvViajes.Dock = DockStyle.Fill; dgvViajes.AutoGenerateColumns = false; dgvViajes.AllowUserToAddRows = false; dgvViajes.AllowUserToDeleteRows = false; dgvViajes.MultiSelect = false; dgvViajes.ReadOnly = true; dgvViajes.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvViajesNumero = new DataGridViewTextBoxColumn();
            dgvViajesNumero.Name = "dgvViajesNumero";
            dgvViajesNumero.DataPropertyName = "Numero"; dgvViajesNumero.HeaderText = "Viaje"; dgvViajesNumero.ReadOnly = false; 
            dgvViajes.Columns.Add(dgvViajesNumero);
            dgvViajesFechaPrevista = new DataGridViewTextBoxColumn();
            dgvViajesFechaPrevista.Name = "dgvViajesFechaPrevista";
            dgvViajesFechaPrevista.DataPropertyName = "FechaPrevista"; dgvViajesFechaPrevista.HeaderText = "Fecha prevista"; dgvViajesFechaPrevista.ReadOnly = false; dgvViajesFechaPrevista.DefaultCellStyle.Format = "g";
            dgvViajes.Columns.Add(dgvViajesFechaPrevista);
            dgvViajesEstado = new DataGridViewTextBoxColumn();
            dgvViajesEstado.Name = "dgvViajesEstado";
            dgvViajesEstado.DataPropertyName = "Estado"; dgvViajesEstado.HeaderText = "Estado"; dgvViajesEstado.ReadOnly = false; 
            dgvViajes.Columns.Add(dgvViajesEstado);
            grp0.Controls.Add(dgvViajes);
            grp0.Controls.Add(panel0);
            grp1 = new GroupBox();
            grp1.Name = "grp1";
            grp1.Text = "Comparación de cantidades";
            grp1.Dock = DockStyle.Fill;
            panel1 = new FlowLayoutPanel();
            panel1.Name = "panel1";
            panel1.Dock = DockStyle.Top; panel1.AutoSize = true; panel1.WrapContents = true; panel1.Padding = new Padding(4);
            dgvCarga = new DataGridView();
            dgvCarga.Name = "dgvCarga";
            dgvCarga.Dock = DockStyle.Fill; dgvCarga.AutoGenerateColumns = false; dgvCarga.AllowUserToAddRows = false; dgvCarga.AllowUserToDeleteRows = false; dgvCarga.MultiSelect = false; dgvCarga.ReadOnly = false; dgvCarga.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvCargaCodigo = new DataGridViewTextBoxColumn();
            dgvCargaCodigo.Name = "dgvCargaCodigo";
            dgvCargaCodigo.DataPropertyName = "Codigo"; dgvCargaCodigo.HeaderText = "Código"; dgvCargaCodigo.ReadOnly = true; 
            dgvCarga.Columns.Add(dgvCargaCodigo);
            dgvCargaDescripcion = new DataGridViewTextBoxColumn();
            dgvCargaDescripcion.Name = "dgvCargaDescripcion";
            dgvCargaDescripcion.DataPropertyName = "Descripcion"; dgvCargaDescripcion.HeaderText = "Mercadería"; dgvCargaDescripcion.ReadOnly = true; 
            dgvCarga.Columns.Add(dgvCargaDescripcion);
            dgvCargaCantidadPrevista = new DataGridViewTextBoxColumn();
            dgvCargaCantidadPrevista.Name = "dgvCargaCantidadPrevista";
            dgvCargaCantidadPrevista.DataPropertyName = "CantidadPrevista"; dgvCargaCantidadPrevista.HeaderText = "Prevista"; dgvCargaCantidadPrevista.ReadOnly = true; dgvCargaCantidadPrevista.DefaultCellStyle.Format = "N3";
            dgvCarga.Columns.Add(dgvCargaCantidadPrevista);
            dgvCargaCantidadPreparada = new DataGridViewTextBoxColumn();
            dgvCargaCantidadPreparada.Name = "dgvCargaCantidadPreparada";
            dgvCargaCantidadPreparada.DataPropertyName = "CantidadPreparada"; dgvCargaCantidadPreparada.HeaderText = "Preparada"; dgvCargaCantidadPreparada.ReadOnly = false; dgvCargaCantidadPreparada.DefaultCellStyle.Format = "N3";
            dgvCarga.Columns.Add(dgvCargaCantidadPreparada);
            dgvCargaDiferencia = new DataGridViewTextBoxColumn();
            dgvCargaDiferencia.Name = "dgvCargaDiferencia";
            dgvCargaDiferencia.DataPropertyName = "Diferencia"; dgvCargaDiferencia.HeaderText = "Diferencia"; dgvCargaDiferencia.ReadOnly = true; dgvCargaDiferencia.DefaultCellStyle.Format = "N3";
            dgvCarga.Columns.Add(dgvCargaDiferencia);
            grp1.Controls.Add(dgvCarga);
            grp1.Controls.Add(panel1);
            grp2 = new GroupBox();
            grp2.Name = "grp2";
            grp2.Text = "Documento de despacho";
            grp2.Dock = DockStyle.Fill; grp2.AutoSize = true; grp2.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            panel2 = new FlowLayoutPanel();
            panel2.Name = "panel2";
            panel2.Dock = DockStyle.Top; panel2.AutoSize = true; panel2.WrapContents = true; panel2.Padding = new Padding(4);
            lblNumero = new Label();
            lblNumero.Name = "lblNumero";
            lblNumero.Text = "N.º despacho";
            lblNumero.Width = 130; lblNumero.AutoSize = true; lblNumero.Margin = new Padding(3,6,3,3);
            panel2.Controls.Add(lblNumero);
            txtNumero = new TextBox();
            txtNumero.Name = "txtNumero";
            txtNumero.Width = 170; txtNumero.MaxLength = 50;
            panel2.Controls.Add(txtNumero);
            lblObservaciones = new Label();
            lblObservaciones.Name = "lblObservaciones";
            lblObservaciones.Text = "Observaciones / diferencias";
            lblObservaciones.Width = 130; lblObservaciones.AutoSize = true; lblObservaciones.Margin = new Padding(3,6,3,3);
            panel2.Controls.Add(lblObservaciones);
            txtObservaciones = new TextBox();
            txtObservaciones.Name = "txtObservaciones";
            txtObservaciones.Width = 390; txtObservaciones.MaxLength = 1000;
            panel2.Controls.Add(txtObservaciones);
            btnGuardar = new Button();
            btnGuardar.Name = "btnGuardar";
            btnGuardar.Text = "Guardar preparación";
            btnGuardar.AutoSize = true; btnGuardar.AutoSizeMode = AutoSizeMode.GrowAndShrink; btnGuardar.MinimumSize = new Size(80, 26); btnGuardar.Padding = new Padding(4, 0, 4, 0); btnGuardar.Click += btnGuardar_Click;
            panel2.Controls.Add(btnGuardar);
            lblEstado = new Label();
            lblEstado.Name = "lblEstado";
            lblEstado.Width = 130; lblEstado.AutoSize = true; lblEstado.Margin = new Padding(3,6,3,3);
            panel2.Controls.Add(lblEstado);
            grp2.Controls.Add(panel2);
            TDPresentacion.AjustarAltura(grp2, panel2);
            layout.Controls.Add(grp0, 0, 0);
            layout.Controls.Add(grp1, 0, 1);
            layout.Controls.Add(grp2, 0, 2);
            Controls.Add(layout);
            Name = "FrmPrepararDespacho"; Text = "Preparar despacho";
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1080, 680); MinimumSize = new Size(900, 600);
            ResumeLayout(false);
        }
        private GroupBox grp0;
        private FlowLayoutPanel panel0;
        private Button btnActualizar;
        private DataGridView dgvViajes;
        private DataGridViewTextBoxColumn dgvViajesNumero;
        private DataGridViewTextBoxColumn dgvViajesFechaPrevista;
        private DataGridViewTextBoxColumn dgvViajesEstado;
        private GroupBox grp1;
        private FlowLayoutPanel panel1;
        private DataGridView dgvCarga;
        private DataGridViewTextBoxColumn dgvCargaCodigo;
        private DataGridViewTextBoxColumn dgvCargaDescripcion;
        private DataGridViewTextBoxColumn dgvCargaCantidadPrevista;
        private DataGridViewTextBoxColumn dgvCargaCantidadPreparada;
        private DataGridViewTextBoxColumn dgvCargaDiferencia;
        private GroupBox grp2;
        private FlowLayoutPanel panel2;
        private Label lblNumero;
        private TextBox txtNumero;
        private Label lblObservaciones;
        private TextBox txtObservaciones;
        private Button btnGuardar;
        private Label lblEstado;
    }
}
