using System;
using System.Drawing;
using System.Windows.Forms;
namespace IngSoft
{
    partial class FrmRegistroEntrega
    {
        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel layout;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            SuspendLayout();
            layout = new TableLayoutPanel();
            layout.Dock = DockStyle.Fill;
            layout.ColumnCount = 1;
            layout.RowCount = 3;
            layout.Padding = new Padding(8);
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 150));
            grp0 = new GroupBox();
            grp0.Name = "grp0";
            grp0.Text = "Viajes en curso";
            grp0.Dock = DockStyle.Fill;
            panel0 = new FlowLayoutPanel();
            panel0.Name = "panel0";
            panel0.Dock = DockStyle.Top; panel0.AutoSize = true; panel0.WrapContents = true; panel0.Padding = new Padding(4);
            btnActualizar = new Button();
            btnActualizar.Name = "btnActualizar";
            btnActualizar.Text = "Actualizar";
            btnActualizar.Width = 130; btnActualizar.AutoSize = true; btnActualizar.Click += btnActualizar_Click;
            panel0.Controls.Add(btnActualizar);
            dgvViajes = new DataGridView();
            dgvViajes.Name = "dgvViajes";
            dgvViajes.Dock = DockStyle.Fill; dgvViajes.AutoGenerateColumns = false; dgvViajes.AllowUserToAddRows = false; dgvViajes.AllowUserToDeleteRows = false; dgvViajes.MultiSelect = false; dgvViajes.ReadOnly = true; dgvViajes.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvViajesNumero = new DataGridViewTextBoxColumn();
            dgvViajesNumero.Name = "dgvViajesNumero";
            dgvViajesNumero.DataPropertyName = "Numero"; dgvViajesNumero.HeaderText = "Viaje"; dgvViajesNumero.ReadOnly = false; 
            dgvViajes.Columns.Add(dgvViajesNumero);
            dgvViajesFechaPrevista = new DataGridViewTextBoxColumn();
            dgvViajesFechaPrevista.Name = "dgvViajesFechaPrevista";
            dgvViajesFechaPrevista.DataPropertyName = "FechaPrevista"; dgvViajesFechaPrevista.HeaderText = "Fecha prevista"; dgvViajesFechaPrevista.ReadOnly = false; dgvViajesFechaPrevista.DefaultCellStyle.Format = "g";
            dgvViajes.Columns.Add(dgvViajesFechaPrevista);
            dgvViajesEstado = new DataGridViewTextBoxColumn();
            dgvViajesEstado.Name = "dgvViajesEstado";
            dgvViajesEstado.DataPropertyName = "Estado"; dgvViajesEstado.HeaderText = "Estado"; dgvViajesEstado.ReadOnly = false; 
            dgvViajes.Columns.Add(dgvViajesEstado);
            grp0.Controls.Add(dgvViajes);
            grp0.Controls.Add(panel0);
            grp1 = new GroupBox();
            grp1.Name = "grp1";
            grp1.Text = "Entregas y comprobantes";
            grp1.Dock = DockStyle.Fill;
            panel1 = new FlowLayoutPanel();
            panel1.Name = "panel1";
            panel1.Dock = DockStyle.Top; panel1.AutoSize = true; panel1.WrapContents = true; panel1.Padding = new Padding(4);
            dgvEntregas = new DataGridView();
            dgvEntregas.Name = "dgvEntregas";
            dgvEntregas.Dock = DockStyle.Fill; dgvEntregas.AutoGenerateColumns = false; dgvEntregas.AllowUserToAddRows = false; dgvEntregas.AllowUserToDeleteRows = false; dgvEntregas.MultiSelect = false; dgvEntregas.ReadOnly = true; dgvEntregas.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvEntregasDestino = new DataGridViewTextBoxColumn();
            dgvEntregasDestino.Name = "dgvEntregasDestino";
            dgvEntregasDestino.DataPropertyName = "Destino"; dgvEntregasDestino.HeaderText = "Destino"; dgvEntregasDestino.ReadOnly = false; 
            dgvEntregas.Columns.Add(dgvEntregasDestino);
            dgvEntregasFechaPrevista = new DataGridViewTextBoxColumn();
            dgvEntregasFechaPrevista.Name = "dgvEntregasFechaPrevista";
            dgvEntregasFechaPrevista.DataPropertyName = "FechaPrevista"; dgvEntregasFechaPrevista.HeaderText = "Fecha prevista"; dgvEntregasFechaPrevista.ReadOnly = false; dgvEntregasFechaPrevista.DefaultCellStyle.Format = "g";
            dgvEntregas.Columns.Add(dgvEntregasFechaPrevista);
            dgvEntregasEstado = new DataGridViewTextBoxColumn();
            dgvEntregasEstado.Name = "dgvEntregasEstado";
            dgvEntregasEstado.DataPropertyName = "Estado"; dgvEntregasEstado.HeaderText = "Estado"; dgvEntregasEstado.ReadOnly = false; 
            dgvEntregas.Columns.Add(dgvEntregasEstado);
            dgvEntregasFechaRealizada = new DataGridViewTextBoxColumn();
            dgvEntregasFechaRealizada.Name = "dgvEntregasFechaRealizada";
            dgvEntregasFechaRealizada.DataPropertyName = "FechaRealizada"; dgvEntregasFechaRealizada.HeaderText = "Fecha real"; dgvEntregasFechaRealizada.ReadOnly = false; dgvEntregasFechaRealizada.DefaultCellStyle.Format = "g";
            dgvEntregas.Columns.Add(dgvEntregasFechaRealizada);
            dgvEntregasObservaciones = new DataGridViewTextBoxColumn();
            dgvEntregasObservaciones.Name = "dgvEntregasObservaciones";
            dgvEntregasObservaciones.DataPropertyName = "Observaciones"; dgvEntregasObservaciones.HeaderText = "Observaciones"; dgvEntregasObservaciones.ReadOnly = false; 
            dgvEntregas.Columns.Add(dgvEntregasObservaciones);
            dgvEntregasNumeroComprobante = new DataGridViewTextBoxColumn();
            dgvEntregasNumeroComprobante.Name = "dgvEntregasNumeroComprobante";
            dgvEntregasNumeroComprobante.DataPropertyName = "NumeroComprobante"; dgvEntregasNumeroComprobante.HeaderText = "Comprobante"; dgvEntregasNumeroComprobante.ReadOnly = false; 
            dgvEntregas.Columns.Add(dgvEntregasNumeroComprobante);
            grp1.Controls.Add(dgvEntregas);
            grp1.Controls.Add(panel1);
            grp2 = new GroupBox();
            grp2.Name = "grp2";
            grp2.Text = "Resultado de la entrega seleccionada";
            grp2.Dock = DockStyle.Fill;
            panel2 = new FlowLayoutPanel();
            panel2.Name = "panel2";
            panel2.Dock = DockStyle.Top; panel2.AutoSize = true; panel2.WrapContents = true; panel2.Padding = new Padding(4);
            lblResultado = new Label();
            lblResultado.Name = "lblResultado";
            lblResultado.Text = "Resultado";
            lblResultado.Width = 130; lblResultado.AutoSize = true; lblResultado.Margin = new Padding(4,8,4,4);
            panel2.Controls.Add(lblResultado);
            cmbResultado = new ComboBox();
            cmbResultado.Name = "cmbResultado";
            cmbResultado.Width = 180; cmbResultado.DropDownStyle = ComboBoxStyle.DropDownList; cmbResultado.DisplayMember = "Value"; cmbResultado.ValueMember = "Key";
            panel2.Controls.Add(cmbResultado);
            lblFecha = new Label();
            lblFecha.Name = "lblFecha";
            lblFecha.Text = "Fecha y hora";
            lblFecha.Width = 130; lblFecha.AutoSize = true; lblFecha.Margin = new Padding(4,8,4,4);
            panel2.Controls.Add(lblFecha);
            dtpRealizada = new DateTimePicker();
            dtpRealizada.Name = "dtpRealizada";
            dtpRealizada.Width = 175; dtpRealizada.Format = DateTimePickerFormat.Custom; dtpRealizada.CustomFormat = "dd/MM/yyyy HH:mm";
            panel2.Controls.Add(dtpRealizada);
            lblObservaciones = new Label();
            lblObservaciones.Name = "lblObservaciones";
            lblObservaciones.Text = "Observaciones";
            lblObservaciones.Width = 130; lblObservaciones.AutoSize = true; lblObservaciones.Margin = new Padding(4,8,4,4);
            panel2.Controls.Add(lblObservaciones);
            txtObservaciones = new TextBox();
            txtObservaciones.Name = "txtObservaciones";
            txtObservaciones.Width = 400; txtObservaciones.MaxLength = 1000;
            panel2.Controls.Add(txtObservaciones);
            btnRegistrar = new Button();
            btnRegistrar.Name = "btnRegistrar";
            btnRegistrar.Text = "Registrar resultado";
            btnRegistrar.Width = 130; btnRegistrar.AutoSize = true; btnRegistrar.Click += btnRegistrar_Click;
            panel2.Controls.Add(btnRegistrar);
            grp2.Controls.Add(panel2);
            layout.Controls.Add(grp0, 0, 0);
            layout.Controls.Add(grp1, 0, 1);
            layout.Controls.Add(grp2, 0, 2);
            Controls.Add(layout);
            Name = "FrmRegistroEntrega"; Text = "Registrar entrega";
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1120, 820); MinimumSize = new Size(960, 760);
            ResumeLayout(false);
        }
        private GroupBox grp0;
        private FlowLayoutPanel panel0;
        private Button btnActualizar;
        private DataGridView dgvViajes;
        private DataGridViewTextBoxColumn dgvViajesNumero;
        private DataGridViewTextBoxColumn dgvViajesFechaPrevista;
        private DataGridViewTextBoxColumn dgvViajesEstado;
        private GroupBox grp1;
        private FlowLayoutPanel panel1;
        private DataGridView dgvEntregas;
        private DataGridViewTextBoxColumn dgvEntregasDestino;
        private DataGridViewTextBoxColumn dgvEntregasFechaPrevista;
        private DataGridViewTextBoxColumn dgvEntregasEstado;
        private DataGridViewTextBoxColumn dgvEntregasFechaRealizada;
        private DataGridViewTextBoxColumn dgvEntregasObservaciones;
        private DataGridViewTextBoxColumn dgvEntregasNumeroComprobante;
        private GroupBox grp2;
        private FlowLayoutPanel panel2;
        private Label lblResultado;
        private ComboBox cmbResultado;
        private Label lblFecha;
        private DateTimePicker dtpRealizada;
        private Label lblObservaciones;
        private TextBox txtObservaciones;
        private Button btnRegistrar;
    }
}
