/*
Seed de traducciones base: Español Argentina.

Este script inserta solamente las traducciones que no existen.
No actualiza traducciones existentes para no pisar cambios hechos desde la aplicación por un administrador.
*/

DECLARE @IdIdioma_es_AR INT;

SELECT @IdIdioma_es_AR = Id_Idioma
FROM dbo.IDIOMA
WHERE Codigo_Idioma = N'es-AR';

IF @IdIdioma_es_AR IS NULL
BEGIN
    RAISERROR('No existe el idioma es-AR. Revisar el script 001_idiomas.sql.', 16, 1);
    RETURN;
END;

DECLARE @Traducciones_es_AR TABLE (
    Clave_Traduccion NVARCHAR(200) NOT NULL PRIMARY KEY,
    Valor_Traduccion NVARCHAR(1000) NULL
);

INSERT INTO @Traducciones_es_AR (
    Clave_Traduccion,
    Valor_Traduccion
)
VALUES
    (N'Common.btnAceptar.Text', N'Aceptar'),
    (N'Common.btnBorrar.Text', N'Borrar'),
    (N'Common.btnBuscar.Text', N'Buscar'),
    (N'Common.btnCancelar.Text', N'Cancelar'),
    (N'Common.btnEditar.Text', N'Editar'),
    (N'Common.btnGuardar.Text', N'Guardar'),
    (N'Common.btnNuevo.Text', N'Nuevo'),
    (N'Common.btnSalir.Text', N'Salir'),
    (N'Common.msgConfirmar', N'Confirmar'),
    (N'Common.msgError', N'Error'),
    (N'FrmABMRoles.Title', N'Administración de roles'),
    (N'FrmABMRoles.btnAsignar.Text', N'Asignar'),
    (N'FrmABMRoles.btnInsertar.Text', N'Insertar'),
    (N'FrmABMRoles.btnQuitar.Text', N'Quitar'),
    (N'FrmABMRoles.btnborrar.Text', N'Borrar'),
    (N'FrmABMRoles.btnlistar.Text', N'Listar'),
    (N'FrmABMRoles.btnmodificar.Text', N'Modificar'),
    (N'FrmABMRoles.groupBox1.Text', N'Roles'),
    (N'FrmABMRoles.groupBox2.Text', N'Permisos'),
    (N'FrmABMRoles.lblPermiso.Text', N'Permiso'),
    (N'FrmABMRoles.lblIdRol.Text', N'Id rol'),
    (N'FrmABMRoles.lblNombreRol.Text', N'Nombre'),
    (N'FrmABMUsuarios.Title', N'Administración de usuarios'),
    (N'FrmABMUsuarios.btnInsertar.Text', N'Insertar'),
    (N'FrmABMUsuarios.btnRestaurarVersAnt.Text', N'Restaurar versión'),
    (N'FrmABMUsuarios.btnborrar.Text', N'Borrar'),
    (N'FrmABMUsuarios.btnlistar.Text', N'Listar'),
    (N'FrmABMUsuarios.btnmodificar.Text', N'Modificar'),
    (N'FrmABMUsuarios.groupBox1.Text', N'Recuperar estados previos'),
    (N'FrmABMUsuarios.lblClave.Text', N'Clave'),
    (N'FrmABMUsuarios.lblD.Text', N'ID'),
    (N'FrmABMUsuarios.lblIdUsuarioSeleccionado.Text', N'Id seleccionado'),
    (N'FrmABMUsuarios.lblNombre.Text', N'Nombre'),
    (N'FrmABMUsuarios.lblPerfil.Text', N'Perfil'),
    (N'FrmABMUsuarios.lblUsuarioSeleccionado.Text', N'Usuario seleccionado'),
    (N'FrmABMUsuarios.msgClaveNoCumple', N'La clave no cumple con los requisitos. Debe tener al menos 6 caracteres, una letra mayúscula y un número.'),
    (N'FrmApp.Title', N'Sistema de gestión administrativa'),
    (N'FrmApp.archivoToolStripMenuItem.Text', N'Archivo'),
    (N'FrmApp.bitácoraToolStripMenuItem.Text', N'Bitácora'),
    (N'FrmApp.cerrarSesiónToolStripMenuItem.Text', N'Cerrar sesión'),
    (N'FrmApp.clientesToolStripMenuItem.Text', N'Nueva venta'),
    (N'FrmApp.gestiónToolStripMenuItem.Text', N'Gestión'),
    (N'FrmApp.historialToolStripMenuItem.Text', N'Historial'),
    (N'FrmApp.idiomasToolStripMenuItem.Text', N'Idiomas'),
    (N'FrmApp.msgConfirmarCerrarSesion', N'¿Realmente desea cerrar sesión?'),
    (N'FrmApp.msgConfirmarSalir', N'¿Realmente desea cerrar sesión y salir?'),
    (N'FrmApp.msgErrorAbrirIdiomas', N'No se pudo abrir el formulario de idiomas.'),
    (N'FrmApp.msgTituloConfirmarSalida', N'Confirmar salida'),
    (N'FrmApp.perfilesToolStripMenuItem.Text', N'Perfiles'),
    (N'FrmApp.productosToolStripMenuItem.Text', N'Clientes'),
    (N'FrmApp.productosToolStripMenuItem1.Text', N'Productos'),
    (N'FrmApp.salirToolStripMenuItem.Text', N'Salir'),
    (N'FrmApp.seguridadToolStripMenuItem.Text', N'Seguridad'),
    (N'FrmApp.usuariosToolStripMenuItem.Text', N'Usuarios'),
    (N'FrmBitacora.Title', N'Bitácora'),
    (N'FrmBitacora.btnBuscar.Text', N'Buscar'),
    (N'FrmBitacora.gbFiltros.Text', N'Filtros'),
    (N'FrmBitacora.lblFechaDesde.Text', N'Fecha desde'),
    (N'FrmBitacora.lblFechaHasta.Text', N'Fecha hasta'),
    (N'FrmBitacora.lblUsuario.Text', N'Usuario'),
    (N'FrmIdioma.Title', N'Gestión de idiomas'),
    (N'FrmIdioma.btnActivar.Text', N'Activar'),
    (N'FrmIdioma.btnBorrar.Text', N'Borrar'),
    (N'FrmIdioma.btnCargarTraducciones.Text', N'Cargar traducciones'),
    (N'FrmIdioma.btnDesactivar.Text', N'Desactivar'),
    (N'FrmIdioma.btnEditar.Text', N'Editar'),
    (N'FrmIdioma.btnGuardarTraducciones.Text', N'Guardar traducciones'),
    (N'FrmIdioma.btnNuevo.Text', N'Nuevo'),
    (N'FrmIdioma.btnSetDefault.Text', N'Predeterminado'),
    (N'FrmIdioma.gbIdiomas.Text', N'Idiomas disponibles'),
    (N'FrmIdioma.gbTraducciones.Text', N'Traducciones del idioma seleccionado'),
    (N'FrmIdioma.dgvIdiomas.Codigo.HeaderText', N'Código'),
    (N'FrmIdioma.dgvIdiomas.Habilitado.HeaderText', N'Habilitado'),
    (N'FrmIdioma.dgvIdiomas.EsDefault.HeaderText', N'Predeterminado'),
    (N'FrmIdioma.dgvIdiomas.Id_Idioma.HeaderText', N'Id'),
    (N'FrmIdioma.dgvIdiomas.Nombre.HeaderText', N'Nombre'),
    (N'FrmIdioma.dgvTraducciones.Clave.HeaderText', N'Clave'),
    (N'FrmIdioma.dgvTraducciones.Id_Idioma.HeaderText', N'Idioma'),
    (N'FrmIdioma.dgvTraducciones.Id_Traduccion.HeaderText', N'Id'),
    (N'FrmIdioma.dgvTraducciones.Valor.HeaderText', N'Valor'),
    (N'FrmIdioma.msgAccesoDenegado', N'Acceso denegado. Requiere rol administrador.'),
    (N'FrmIdioma.msgBorrarIdioma', N'¿Borrar idioma?'),
    (N'FrmIdioma.msgConfirmar', N'Confirmar'),
    (N'FrmIdioma.msgTraduccionesGuardadas', N'Traducciones guardadas.'),
    (N'FrmIdiomaEditor.Title', N'Idioma'),
    (N'FrmIdiomaEditor.btnCancel.Text', N'Cancelar'),
    (N'FrmIdiomaEditor.btnOk.Text', N'OK'),
    (N'FrmIdiomaEditor.chkHabilitado.Text', N'Habilitado'),
    (N'FrmIdiomaEditor.lblCodigo.Text', N'Código:'),
    (N'FrmIdiomaEditor.lblNombre.Text', N'Nombre:'),
    (N'FrmLogin.Title', N'Login'),
    (N'FrmLogin.btnIngresar.Text', N'Ingresar'),
    (N'FrmLogin.btnSalir.Text', N'Salir'),
    (N'FrmLogin.cmbIdiomasLogin.Text', N'Idioma'),
    (N'FrmLogin.lblClave.Text', N'Clave'),
    (N'FrmLogin.lblUsuario.Text', N'Usuario'),
    (N'FrmLogin.msgCamposRequeridos', N'Debe completar todos los campos.'),
    (N'FrmLogin.msgCredencialesInvalidas', N'Usuario y/o clave incorrecta o inexistente.'),
    (N'FrmLogin.msgIngresoExitoso', N'Ingreso exitoso.'),
    (N'FrmLogin.msgSistemaNoDisponible', N'El sistema no está disponible en este momento. Por favor, intente más tarde.'),
    (N'frmRestore.Title', N'Restauración de integridad'),
    (N'frmRestore.btnCancelar.Text', N'Cancelar'),
    (N'frmRestore.btnRecalcular.Text', N'Recalcular'),
    (N'frmRestore.btnRestore.Text', N'Restaurar base de datos'),
    (N'frmRestore.lblIntegridadDVV.Text', N'Integridad de tabla'),
    (N'frmRestore.lblRegistros.Text', N'Integridad de registros'),
    (N'frmRestore.msgIntegridadDVVCorrecta', N'Integridad correcta de tabla.'),
    (N'frmRestore.msgIntegridadDVVFallida', N'Integridad fallida de tabla.'),
    (N'frmRestore.msgIntegridadRegistrosCorrecta', N'Integridad correcta de registros.'),
    (N'frmRestore.msgIntegridadRegistrosFallida', N'Integridad fallida de registros.'),
    (N'frmRestore.msgRestauracionError', N'Error al restaurar la base de datos.'),
    (N'frmRestore.msgRestauracionExitosa', N'Restauración completada con éxito.');

-- TD: traducciones de transporte y distribución
INSERT INTO @Traducciones_es_AR (Clave_Traduccion, Valor_Traduccion)
VALUES
    (N'TD.SinPermiso', N'No tiene permiso para esta operación.'),
    (N'TD.DatosInvalidos', N'Complete los datos obligatorios y revise su formato y longitud.'),
    (N'TD.Duplicado', N'El número, código o producto ya está registrado. Actualice los datos.'),
    (N'TD.EstadoInvalido', N'La operación no está habilitada en el estado actual. Actualice los datos.'),
    (N'TD.PlanIncompleto', N'Cada plan requiere viajes; cada viaje requiere entregas y carga prevista.'),
    (N'TD.CantidadInvalida', N'Ingrese cantidades positivas, con hasta tres decimales.'),
    (N'TD.FechaEntrega', N'Revise destinos y fechas: la entrega no puede preceder al viaje.'),
    (N'TD.Error', N'No se pudo completar la operación. Revise la conexión y actualice los datos.'),
    (N'TD.Seleccionar', N'Seleccione un registro.'),
    (N'TD.Guardado', N'Operación registrada correctamente.'),
    (N'TD.Confirmar', N'¿Confirma la operación?'),
    (N'TD.Formato', N'El valor ingresado no tiene un formato válido.'),
    (N'FrmApp.menuTD.Text', N'Transporte y distribución'),
    (N'FrmPlanificacionDistribucion.Title', N'Planificar distribución'),
    (N'FrmPlanificacionDistribucion.grp0.Text', N'Requerimiento y plan'),
    (N'FrmPlanificacionDistribucion.lblRequerimiento.Text', N'Pendiente'),
    (N'FrmPlanificacionDistribucion.lblPlan.Text', N'N.º plan'),
    (N'FrmPlanificacionDistribucion.btnActualizar.Text', N'Actualizar'),
    (N'FrmPlanificacionDistribucion.lblNuevoReq.Text', N'Nuevo requerimiento: número / origen'),
    (N'FrmPlanificacionDistribucion.btnRecibir.Text', N'Recibir requerimiento'),
    (N'FrmPlanificacionDistribucion.grp1.Text', N'Viajes del plan'),
    (N'FrmPlanificacionDistribucion.lblViaje.Text', N'N.º viaje'),
    (N'FrmPlanificacionDistribucion.lblFechaViaje.Text', N'Salida prevista'),
    (N'FrmPlanificacionDistribucion.btnViaje.Text', N'Agregar viaje'),
    (N'FrmPlanificacionDistribucion.btnQuitarViaje.Text', N'Quitar viaje'),
    (N'FrmPlanificacionDistribucion.dgvViajes.Numero.HeaderText', N'Número'),
    (N'FrmPlanificacionDistribucion.dgvViajes.FechaPrevista.HeaderText', N'Salida prevista'),
    (N'FrmPlanificacionDistribucion.grp2.Text', N'Entregas del viaje seleccionado'),
    (N'FrmPlanificacionDistribucion.lblDestino.Text', N'Destino'),
    (N'FrmPlanificacionDistribucion.btnEntrega.Text', N'Agregar entrega'),
    (N'FrmPlanificacionDistribucion.btnQuitarEntrega.Text', N'Quitar entrega'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmPlanificacionDistribucion.grp3.Text', N'Carga prevista del viaje seleccionado'),
    (N'FrmPlanificacionDistribucion.lblCantidad.Text', N'Cantidad prevista'),
    (N'FrmPlanificacionDistribucion.btnCarga.Text', N'Agregar carga'),
    (N'FrmPlanificacionDistribucion.btnQuitarCarga.Text', N'Quitar carga'),
    (N'FrmPlanificacionDistribucion.dgvCarga.IdMercaderia.HeaderText', N'Mercadería'),
    (N'FrmPlanificacionDistribucion.dgvCarga.CantidadPrevista.HeaderText', N'Cantidad prevista'),
    (N'FrmPlanificacionDistribucion.grp4.Text', N'Alta de producto en catálogo'),
    (N'FrmPlanificacionDistribucion.lblCodigo.Text', N'Código'),
    (N'FrmPlanificacionDistribucion.lblDescripcion.Text', N'Descripción'),
    (N'FrmPlanificacionDistribucion.btnProducto.Text', N'Crear producto'),
    (N'FrmPlanificacionDistribucion.btnConfirmar.Text', N'Confirmar plan'),
    (N'FrmApp.menuTD01.Text', N'Planificar distribución'),
    (N'TD.CantidadPreparadaInvalida', N'La cantidad preparada debe ser cero o positiva, con hasta tres decimales.'),
    (N'TD.ExpliqueDiferencia', N'Registre el motivo de las diferencias en observaciones.'),
    (N'TD.DespachoPendiente', N'Diferencias registradas. El despacho queda pendiente y el viaje no puede iniciarse.'),
    (N'TD.Estado.Pendiente', N'Pendiente'),
    (N'TD.Estado.Confirmado', N'Confirmado'),
    (N'TD.Estado.Planificado', N'Planificado'),
    (N'TD.Estado.Preparado', N'Preparado'),
    (N'TD.Estado.EnCurso', N'En curso'),
    (N'TD.Estado.Cerrado', N'Cerrado'),
    (N'TD.Estado.Entregada', N'Entregada'),
    (N'TD.Estado.Parcial', N'Parcial'),
    (N'TD.Estado.Incumplida', N'Incumplida'),
    (N'FrmApp.menuTD02.Text', N'Preparar despacho'),
    (N'FrmPrepararDespacho.Title', N'Preparar despacho'),
    (N'FrmPrepararDespacho.grp0.Text', N'Viajes y estado de preparación'),
    (N'FrmPrepararDespacho.btnActualizar.Text', N'Actualizar'),
    (N'FrmPrepararDespacho.dgvViajes.Numero.HeaderText', N'Viaje'),
    (N'FrmPrepararDespacho.dgvViajes.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmPrepararDespacho.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmPrepararDespacho.grp1.Text', N'Comparación de cantidades'),
    (N'FrmPrepararDespacho.dgvCarga.Codigo.HeaderText', N'Código'),
    (N'FrmPrepararDespacho.dgvCarga.Descripcion.HeaderText', N'Mercadería'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPrevista.HeaderText', N'Prevista'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPreparada.HeaderText', N'Preparada'),
    (N'FrmPrepararDespacho.dgvCarga.Diferencia.HeaderText', N'Diferencia'),
    (N'FrmPrepararDespacho.grp2.Text', N'Documento de despacho'),
    (N'FrmPrepararDespacho.lblNumero.Text', N'N.º despacho'),
    (N'FrmPrepararDespacho.lblObservaciones.Text', N'Observaciones / diferencias'),
    (N'FrmPrepararDespacho.btnGuardar.Text', N'Guardar preparación'),
    (N'TD.InicioNoHabilitado', N'El viaje requiere un despacho confirmado y una carga sin diferencias.'),
    (N'TD.SinDespacho', N'Sin despacho'),
    (N'FrmApp.menuTD03.Text', N'Registrar ejecución de viaje'),
    (N'FrmEjecucionViaje.Title', N'Registrar ejecución de viaje'),
    (N'FrmEjecucionViaje.grp0.Text', N'Viajes'),
    (N'FrmEjecucionViaje.btnActualizar.Text', N'Actualizar'),
    (N'FrmEjecucionViaje.dgvViajes.Numero.HeaderText', N'Viaje'),
    (N'FrmEjecucionViaje.dgvViajes.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmEjecucionViaje.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmEjecucionViaje.dgvViajes.FechaInicio.HeaderText', N'Inicio'),
    (N'FrmEjecucionViaje.grp1.Text', N'Documento y carga de despacho'),
    (N'FrmEjecucionViaje.dgvCarga.Codigo.HeaderText', N'Código'),
    (N'FrmEjecucionViaje.dgvCarga.Descripcion.HeaderText', N'Mercadería'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPrevista.HeaderText', N'Prevista'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPreparada.HeaderText', N'Preparada'),
    (N'FrmEjecucionViaje.grp2.Text', N'Entregas previstas'),
    (N'FrmEjecucionViaje.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmEjecucionViaje.dgvEntregas.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmEjecucionViaje.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmEjecucionViaje.grp3.Text', N'Inicio del viaje'),
    (N'FrmEjecucionViaje.btnIniciar.Text', N'Confirmar inicio'),
    (N'TD.FechaResultado', N'La fecha debe estar entre el inicio del viaje y el momento actual.'),
    (N'TD.ExpliqueResultado', N'Indique el motivo del resultado parcial o incumplido.'),
    (N'FrmApp.menuTD04.Text', N'Registrar entrega'),
    (N'FrmRegistroEntrega.Title', N'Registrar entrega'),
    (N'FrmRegistroEntrega.grp0.Text', N'Viajes en curso'),
    (N'FrmRegistroEntrega.btnActualizar.Text', N'Actualizar'),
    (N'FrmRegistroEntrega.dgvViajes.Numero.HeaderText', N'Viaje'),
    (N'FrmRegistroEntrega.dgvViajes.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmRegistroEntrega.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmRegistroEntrega.grp1.Text', N'Entregas y comprobantes'),
    (N'FrmRegistroEntrega.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmRegistroEntrega.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaRealizada.HeaderText', N'Fecha real'),
    (N'FrmRegistroEntrega.dgvEntregas.Observaciones.HeaderText', N'Observaciones'),
    (N'FrmRegistroEntrega.dgvEntregas.NumeroComprobante.HeaderText', N'Comprobante'),
    (N'FrmRegistroEntrega.grp2.Text', N'Resultado de la entrega seleccionada'),
    (N'FrmRegistroEntrega.lblResultado.Text', N'Resultado'),
    (N'FrmRegistroEntrega.lblFecha.Text', N'Fecha y hora'),
    (N'FrmRegistroEntrega.lblObservaciones.Text', N'Observaciones'),
    (N'FrmRegistroEntrega.btnRegistrar.Text', N'Registrar resultado'),
    (N'TD.CierreNoHabilitado', N'Sólo se cierra un viaje en curso con todas sus entregas completas y sus comprobantes. Revise los resultados pendientes, parciales o incumplidos.'),
    (N'FrmCumplimientoViaje.Resumen', N'Cumplimiento: {0:N2}% | Total: {1} | Entregadas: {2} | Parciales: {3} | Incumplidas: {4} | Pendientes: {5} | Comprobantes: {6}'),
    (N'FrmApp.menuTD05.Text', N'Controlar cumplimiento de viaje'),
    (N'FrmCumplimientoViaje.Title', N'Controlar cumplimiento de viaje'),
    (N'FrmCumplimientoViaje.grp0.Text', N'Viajes'),
    (N'FrmCumplimientoViaje.btnActualizar.Text', N'Actualizar'),
    (N'FrmCumplimientoViaje.dgvViajes.Numero.HeaderText', N'Viaje'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmCumplimientoViaje.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaInicio.HeaderText', N'Inicio'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaFinalizacion.HeaderText', N'Cierre'),
    (N'FrmCumplimientoViaje.grp1.Text', N'Resultados y comprobantes'),
    (N'FrmCumplimientoViaje.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmCumplimientoViaje.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaRealizada.HeaderText', N'Fecha real'),
    (N'FrmCumplimientoViaje.dgvEntregas.Observaciones.HeaderText', N'Observaciones'),
    (N'FrmCumplimientoViaje.dgvEntregas.NumeroComprobante.HeaderText', N'Comprobante'),
    (N'FrmCumplimientoViaje.grp2.Text', N'Cumplimiento'),
    (N'FrmCumplimientoViaje.btnCerrar.Text', N'Cerrar viaje');
-- Fin traducciones TD


INSERT INTO dbo.TRADUCCION (
    Id_Idioma,
    Clave_Traduccion,
    Valor_Traduccion
)
SELECT
    @IdIdioma_es_AR,
    origen.Clave_Traduccion,
    origen.Valor_Traduccion
FROM @Traducciones_es_AR AS origen
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.TRADUCCION AS destino
    WHERE destino.Id_Idioma = @IdIdioma_es_AR
      AND destino.Clave_Traduccion = origen.Clave_Traduccion
);
