/*
Seed de traducciones base: Español Argentina.

Este script inserta solamente las traducciones que no existen.
No actualiza traducciones existentes para no pisar cambios hechos desde la aplicación por un administrador.
*/

DECLARE @IdIdioma_es_AR INT;

SELECT @IdIdioma_es_AR = Id_Idioma
FROM dbo.IDIOMA
WHERE Codigo_Idioma = N'es-AR';

IF @IdIdioma_es_AR IS NULL
BEGIN
    RAISERROR('No existe el idioma es-AR. Revisar el script 001_idiomas.sql.', 16, 1);
    RETURN;
END;

DECLARE @Traducciones_es_AR TABLE (
    Clave_Traduccion NVARCHAR(200) NOT NULL PRIMARY KEY,
    Valor_Traduccion NVARCHAR(1000) NULL
);

INSERT INTO @Traducciones_es_AR (
    Clave_Traduccion,
    Valor_Traduccion
)
VALUES
    (N'Common.btnAceptar.Text', N'Aceptar'),
    (N'Common.btnBorrar.Text', N'Borrar'),
    (N'Common.btnBuscar.Text', N'Buscar'),
    (N'Common.btnCancelar.Text', N'Cancelar'),
    (N'Common.btnEditar.Text', N'Editar'),
    (N'Common.btnGuardar.Text', N'Guardar'),
    (N'Common.btnNuevo.Text', N'Nuevo'),
    (N'Common.btnSalir.Text', N'Salir'),
    (N'Common.msgConfirmar', N'Confirmar'),
    (N'Common.msgError', N'Error'),
    (N'FrmABMRoles.Title', N'Administración de roles'),
    (N'FrmABMRoles.btnAsignar.Text', N'Asignar'),
    (N'FrmABMRoles.btnInsertar.Text', N'Insertar'),
    (N'FrmABMRoles.btnQuitar.Text', N'Quitar'),
    (N'FrmABMRoles.btnborrar.Text', N'Borrar'),
    (N'FrmABMRoles.btnlistar.Text', N'Listar'),
    (N'FrmABMRoles.btnmodificar.Text', N'Modificar'),
    (N'FrmABMRoles.groupBox1.Text', N'Roles'),
    (N'FrmABMRoles.groupBox2.Text', N'Permisos'),
    (N'FrmABMRoles.lblPermiso.Text', N'Permiso'),
    (N'FrmABMRoles.lblIdRol.Text', N'Id rol'),
    (N'FrmABMRoles.lblNombreRol.Text', N'Nombre'),
    (N'FrmABMUsuarios.Title', N'Administración de usuarios'),
    (N'FrmABMUsuarios.btnInsertar.Text', N'Insertar'),
    (N'FrmABMUsuarios.btnRestaurarVersAnt.Text', N'Restaurar versión'),
    (N'FrmABMUsuarios.btnborrar.Text', N'Borrar'),
    (N'FrmABMUsuarios.btnlistar.Text', N'Listar'),
    (N'FrmABMUsuarios.btnmodificar.Text', N'Modificar'),
    (N'FrmABMUsuarios.groupBox1.Text', N'Recuperar estados previos'),
    (N'FrmABMUsuarios.lblClave.Text', N'Clave'),
    (N'FrmABMUsuarios.lblD.Text', N'ID'),
    (N'FrmABMUsuarios.lblIdUsuarioSeleccionado.Text', N'Id seleccionado'),
    (N'FrmABMUsuarios.lblNombre.Text', N'Nombre'),
    (N'FrmABMUsuarios.lblPerfil.Text', N'Perfil'),
    (N'FrmABMUsuarios.lblUsuarioSeleccionado.Text', N'Usuario seleccionado'),
    (N'FrmABMUsuarios.msgClaveNoCumple', N'La clave no cumple con los requisitos. Debe tener al menos 6 caracteres, una letra mayúscula y un número.'),
    (N'FrmApp.Title', N'Sistema de gestión administrativa'),
    (N'FrmApp.archivoToolStripMenuItem.Text', N'Archivo'),
    (N'FrmApp.bitácoraToolStripMenuItem.Text', N'Bitácora'),
    (N'FrmApp.cerrarSesiónToolStripMenuItem.Text', N'Cerrar sesión'),
    (N'FrmApp.clientesToolStripMenuItem.Text', N'Nueva venta'),
    (N'FrmApp.gestiónToolStripMenuItem.Text', N'Gestión'),
    (N'FrmApp.historialToolStripMenuItem.Text', N'Historial'),
    (N'FrmApp.idiomasToolStripMenuItem.Text', N'Idiomas'),
    (N'FrmApp.msgConfirmarCerrarSesion', N'¿Realmente desea cerrar sesión?'),
    (N'FrmApp.msgConfirmarSalir', N'¿Realmente desea cerrar sesión y salir?'),
    (N'FrmApp.msgErrorAbrirIdiomas', N'No se pudo abrir el formulario de idiomas.'),
    (N'FrmApp.msgTituloConfirmarSalida', N'Confirmar salida'),
    (N'FrmApp.perfilesToolStripMenuItem.Text', N'Perfiles'),
    (N'FrmApp.productosToolStripMenuItem.Text', N'Clientes'),
    (N'FrmApp.productosToolStripMenuItem1.Text', N'Productos'),
    (N'FrmApp.salirToolStripMenuItem.Text', N'Salir'),
    (N'FrmApp.seguridadToolStripMenuItem.Text', N'Seguridad'),
    (N'FrmApp.usuariosToolStripMenuItem.Text', N'Usuarios'),
    (N'FrmBitacora.Title', N'Bitácora'),
    (N'FrmBitacora.btnBuscar.Text', N'Buscar'),
    (N'FrmBitacora.gbFiltros.Text', N'Filtros'),
    (N'FrmBitacora.lblFechaDesde.Text', N'Fecha desde'),
    (N'FrmBitacora.lblFechaHasta.Text', N'Fecha hasta'),
    (N'FrmBitacora.lblUsuario.Text', N'Usuario'),
    (N'FrmIdioma.Title', N'Gestión de idiomas'),
    (N'FrmIdioma.btnActivar.Text', N'Activar'),
    (N'FrmIdioma.btnBorrar.Text', N'Borrar'),
    (N'FrmIdioma.btnCargarTraducciones.Text', N'Cargar traducciones'),
    (N'FrmIdioma.btnDesactivar.Text', N'Desactivar'),
    (N'FrmIdioma.btnEditar.Text', N'Editar'),
    (N'FrmIdioma.btnGuardarTraducciones.Text', N'Guardar traducciones'),
    (N'FrmIdioma.btnNuevo.Text', N'Nuevo'),
    (N'FrmIdioma.btnSetDefault.Text', N'Predeterminado'),
    (N'FrmIdioma.gbIdiomas.Text', N'Idiomas disponibles'),
    (N'FrmIdioma.gbTraducciones.Text', N'Traducciones del idioma seleccionado'),
    (N'FrmIdioma.dgvIdiomas.Codigo.HeaderText', N'Código'),
    (N'FrmIdioma.dgvIdiomas.Habilitado.HeaderText', N'Habilitado'),
    (N'FrmIdioma.dgvIdiomas.EsDefault.HeaderText', N'Predeterminado'),
    (N'FrmIdioma.dgvIdiomas.Id_Idioma.HeaderText', N'Id'),
    (N'FrmIdioma.dgvIdiomas.Nombre.HeaderText', N'Nombre'),
    (N'FrmIdioma.dgvTraducciones.Clave.HeaderText', N'Clave'),
    (N'FrmIdioma.dgvTraducciones.Id_Idioma.HeaderText', N'Idioma'),
    (N'FrmIdioma.dgvTraducciones.Id_Traduccion.HeaderText', N'Id'),
    (N'FrmIdioma.dgvTraducciones.Valor.HeaderText', N'Valor'),
    (N'FrmIdioma.msgAccesoDenegado', N'Acceso denegado. Requiere rol administrador.'),
    (N'FrmIdioma.msgBorrarIdioma', N'¿Borrar idioma?'),
    (N'FrmIdioma.msgConfirmar', N'Confirmar'),
    (N'FrmIdioma.msgTraduccionesGuardadas', N'Traducciones guardadas.'),
    (N'FrmIdiomaEditor.Title', N'Idioma'),
    (N'FrmIdiomaEditor.btnCancel.Text', N'Cancelar'),
    (N'FrmIdiomaEditor.btnOk.Text', N'OK'),
    (N'FrmIdiomaEditor.chkHabilitado.Text', N'Habilitado'),
    (N'FrmIdiomaEditor.lblCodigo.Text', N'Código:'),
    (N'FrmIdiomaEditor.lblNombre.Text', N'Nombre:'),
    (N'FrmLogin.Title', N'Login'),
    (N'FrmLogin.btnIngresar.Text', N'Ingresar'),
    (N'FrmLogin.btnSalir.Text', N'Salir'),
    (N'FrmLogin.cmbIdiomasLogin.Text', N'Idioma'),
    (N'FrmLogin.lblClave.Text', N'Clave'),
    (N'FrmLogin.lblUsuario.Text', N'Usuario'),
    (N'FrmLogin.msgCamposRequeridos', N'Debe completar todos los campos.'),
    (N'FrmLogin.msgCredencialesInvalidas', N'Usuario y/o clave incorrecta o inexistente.'),
    (N'FrmLogin.msgIngresoExitoso', N'Ingreso exitoso.'),
    (N'FrmLogin.msgSistemaNoDisponible', N'El sistema no está disponible en este momento. Por favor, intente más tarde.'),
    (N'frmRestore.Title', N'Restauración de integridad'),
    (N'frmRestore.btnCancelar.Text', N'Cancelar'),
    (N'frmRestore.btnRecalcular.Text', N'Recalcular'),
    (N'frmRestore.btnRestore.Text', N'Restaurar base de datos'),
    (N'frmRestore.lblIntegridadDVV.Text', N'Integridad de tabla'),
    (N'frmRestore.lblRegistros.Text', N'Integridad de registros'),
    (N'frmRestore.msgIntegridadDVVCorrecta', N'Integridad correcta de tabla.'),
    (N'frmRestore.msgIntegridadDVVFallida', N'Integridad fallida de tabla.'),
    (N'frmRestore.msgIntegridadRegistrosCorrecta', N'Integridad correcta de registros.'),
    (N'frmRestore.msgIntegridadRegistrosFallida', N'Integridad fallida de registros.'),
    (N'frmRestore.msgRestauracionError', N'Error al restaurar la base de datos.'),
    (N'frmRestore.msgRestauracionExitosa', N'Restauración completada con éxito.');

-- TD: traducciones de transporte y distribución
INSERT INTO @Traducciones_es_AR (Clave_Traduccion, Valor_Traduccion)
VALUES
    (N'TD.SinPermiso', N'No tiene permiso para esta operación.'),
    (N'TD.DatosInvalidos', N'Complete los datos obligatorios y revise su formato y longitud.'),
    (N'TD.Duplicado', N'El número, código o producto ya está registrado. Actualice los datos.'),
    (N'TD.EstadoInvalido', N'La operación no está habilitada en el estado actual. Actualice los datos.'),
    (N'TD.PlanIncompleto', N'Cada plan requiere viajes; cada viaje requiere entregas y carga prevista.'),
    (N'TD.CantidadInvalida', N'Ingrese cantidades positivas, con hasta tres decimales.'),
    (N'TD.FechaEntrega', N'Revise destinos y fechas: la entrega no puede preceder al viaje.'),
    (N'TD.Error', N'No se pudo completar la operación. Revise la conexión y actualice los datos.'),
    (N'TD.Seleccionar', N'Seleccione un registro.'),
    (N'TD.Guardado', N'Operación registrada correctamente.'),
    (N'TD.Confirmar', N'¿Confirma la operación?'),
    (N'TD.Formato', N'El valor ingresado no tiene un formato válido.'),
    (N'FrmApp.menuTD.Text', N'Transporte y distribución'),
    (N'FrmPlanificacionDistribucion.Title', N'Planificar distribución'),
    (N'FrmPlanificacionDistribucion.grp0.Text', N'Requerimiento y plan'),
    (N'FrmPlanificacionDistribucion.lblRequerimiento.Text', N'Pendiente'),
    (N'FrmPlanificacionDistribucion.lblPlan.Text', N'N.º plan'),
    (N'FrmPlanificacionDistribucion.btnActualizar.Text', N'Actualizar'),
    (N'FrmPlanificacionDistribucion.lblNuevoReq.Text', N'Nuevo requerimiento: número / origen'),
    (N'FrmPlanificacionDistribucion.btnRecibir.Text', N'Recibir requerimiento'),
    (N'FrmPlanificacionDistribucion.grp1.Text', N'Viajes del plan'),
    (N'FrmPlanificacionDistribucion.lblViaje.Text', N'N.º viaje'),
    (N'FrmPlanificacionDistribucion.lblFechaViaje.Text', N'Salida prevista'),
    (N'FrmPlanificacionDistribucion.btnViaje.Text', N'Agregar viaje'),
    (N'FrmPlanificacionDistribucion.btnQuitarViaje.Text', N'Quitar viaje'),
    (N'FrmPlanificacionDistribucion.dgvViajes.Numero.HeaderText', N'Número'),
    (N'FrmPlanificacionDistribucion.dgvViajes.FechaPrevista.HeaderText', N'Salida prevista'),
    (N'FrmPlanificacionDistribucion.grp2.Text', N'Entregas del viaje seleccionado'),
    (N'FrmPlanificacionDistribucion.lblDestino.Text', N'Destino'),
    (N'FrmPlanificacionDistribucion.btnEntrega.Text', N'Agregar entrega'),
    (N'FrmPlanificacionDistribucion.btnQuitarEntrega.Text', N'Quitar entrega'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmPlanificacionDistribucion.grp3.Text', N'Carga prevista del viaje seleccionado'),
    (N'FrmPlanificacionDistribucion.lblCantidad.Text', N'Cantidad prevista'),
    (N'FrmPlanificacionDistribucion.btnCarga.Text', N'Agregar carga'),
    (N'FrmPlanificacionDistribucion.btnQuitarCarga.Text', N'Quitar carga'),
    (N'FrmPlanificacionDistribucion.dgvCarga.IdMercaderia.HeaderText', N'Mercadería'),
    (N'FrmPlanificacionDistribucion.dgvCarga.CantidadPrevista.HeaderText', N'Cantidad prevista'),
    (N'FrmPlanificacionDistribucion.grp4.Text', N'Alta de producto en catálogo'),
    (N'FrmPlanificacionDistribucion.lblCodigo.Text', N'Código'),
    (N'FrmPlanificacionDistribucion.lblDescripcion.Text', N'Descripción'),
    (N'FrmPlanificacionDistribucion.btnProducto.Text', N'Crear producto'),
    (N'FrmPlanificacionDistribucion.btnConfirmar.Text', N'Confirmar plan'),
    (N'FrmApp.menuTD01.Text', N'Planificar distribución'),
    (N'TD.CantidadPreparadaInvalida', N'La cantidad preparada debe ser cero o positiva, con hasta tres decimales.'),
    (N'TD.ExpliqueDiferencia', N'Registre el motivo de las diferencias en observaciones.'),
    (N'TD.DespachoPendiente', N'Diferencias registradas. El despacho queda pendiente y el viaje no puede iniciarse.'),
    (N'TD.Estado.Pendiente', N'Pendiente'),
    (N'TD.Estado.Confirmado', N'Confirmado'),
    (N'TD.Estado.Planificado', N'Planificado'),
    (N'TD.Estado.Preparado', N'Preparado'),
    (N'TD.Estado.EnCurso', N'En curso'),
    (N'TD.Estado.Cerrado', N'Cerrado'),
    (N'TD.Estado.Entregada', N'Entregada'),
    (N'TD.Estado.Parcial', N'Parcial'),
    (N'TD.Estado.Incumplida', N'Incumplida'),
    (N'FrmApp.menuTD02.Text', N'Preparar despacho'),
    (N'FrmPrepararDespacho.Title', N'Preparar despacho'),
    (N'FrmPrepararDespacho.grp0.Text', N'Viajes y estado de preparación'),
    (N'FrmPrepararDespacho.btnActualizar.Text', N'Actualizar'),
    (N'FrmPrepararDespacho.dgvViajes.Numero.HeaderText', N'Viaje'),
    (N'FrmPrepararDespacho.dgvViajes.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmPrepararDespacho.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmPrepararDespacho.grp1.Text', N'Comparación de cantidades'),
    (N'FrmPrepararDespacho.dgvCarga.Codigo.HeaderText', N'Código'),
    (N'FrmPrepararDespacho.dgvCarga.Descripcion.HeaderText', N'Mercadería'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPrevista.HeaderText', N'Prevista'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPreparada.HeaderText', N'Preparada'),
    (N'FrmPrepararDespacho.dgvCarga.Diferencia.HeaderText', N'Diferencia'),
    (N'FrmPrepararDespacho.grp2.Text', N'Documento de despacho'),
    (N'FrmPrepararDespacho.lblNumero.Text', N'N.º despacho'),
    (N'FrmPrepararDespacho.lblObservaciones.Text', N'Observaciones / diferencias'),
    (N'FrmPrepararDespacho.btnGuardar.Text', N'Guardar preparación'),
    (N'TD.InicioNoHabilitado', N'El viaje requiere un despacho confirmado y una carga sin diferencias.'),
    (N'TD.SinDespacho', N'Sin despacho'),
    (N'FrmApp.menuTD03.Text', N'Registrar ejecución de viaje'),
    (N'FrmEjecucionViaje.Title', N'Registrar ejecución de viaje'),
    (N'FrmEjecucionViaje.grp0.Text', N'Viajes'),
    (N'FrmEjecucionViaje.btnActualizar.Text', N'Actualizar'),
    (N'FrmEjecucionViaje.dgvViajes.Numero.HeaderText', N'Viaje'),
    (N'FrmEjecucionViaje.dgvViajes.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmEjecucionViaje.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmEjecucionViaje.dgvViajes.FechaInicio.HeaderText', N'Inicio'),
    (N'FrmEjecucionViaje.grp1.Text', N'Documento y carga de despacho'),
    (N'FrmEjecucionViaje.dgvCarga.Codigo.HeaderText', N'Código'),
    (N'FrmEjecucionViaje.dgvCarga.Descripcion.HeaderText', N'Mercadería'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPrevista.HeaderText', N'Prevista'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPreparada.HeaderText', N'Preparada'),
    (N'FrmEjecucionViaje.grp2.Text', N'Entregas previstas'),
    (N'FrmEjecucionViaje.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmEjecucionViaje.dgvEntregas.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmEjecucionViaje.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmEjecucionViaje.grp3.Text', N'Inicio del viaje'),
    (N'FrmEjecucionViaje.btnIniciar.Text', N'Confirmar inicio'),
    (N'TD.FechaResultado', N'La fecha debe estar entre el inicio del viaje y el momento actual.'),
    (N'TD.ExpliqueResultado', N'Indique el motivo del resultado parcial o incumplido.'),
    (N'FrmApp.menuTD04.Text', N'Registrar entrega'),
    (N'FrmRegistroEntrega.Title', N'Registrar entrega'),
    (N'FrmRegistroEntrega.grp0.Text', N'Viajes en curso'),
    (N'FrmRegistroEntrega.btnActualizar.Text', N'Actualizar'),
    (N'FrmRegistroEntrega.dgvViajes.Numero.HeaderText', N'Viaje'),
    (N'FrmRegistroEntrega.dgvViajes.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmRegistroEntrega.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmRegistroEntrega.grp1.Text', N'Entregas y comprobantes'),
    (N'FrmRegistroEntrega.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmRegistroEntrega.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaRealizada.HeaderText', N'Fecha real'),
    (N'FrmRegistroEntrega.dgvEntregas.Observaciones.HeaderText', N'Observaciones'),
    (N'FrmRegistroEntrega.dgvEntregas.NumeroComprobante.HeaderText', N'Comprobante'),
    (N'FrmRegistroEntrega.grp2.Text', N'Resultado de la entrega seleccionada'),
    (N'FrmRegistroEntrega.lblResultado.Text', N'Resultado'),
    (N'FrmRegistroEntrega.lblFecha.Text', N'Fecha y hora'),
    (N'FrmRegistroEntrega.lblObservaciones.Text', N'Observaciones'),
    (N'FrmRegistroEntrega.btnRegistrar.Text', N'Registrar resultado'),
    (N'TD.CierreNoHabilitado', N'Sólo se cierra un viaje en curso con todas sus entregas completas y sus comprobantes. Revise los resultados pendientes, parciales o incumplidos.'),
    (N'FrmCumplimientoViaje.Resumen', N'Cumplimiento: {0:N2}% | Total: {1} | Entregadas: {2} | Parciales: {3} | Incumplidas: {4} | Pendientes: {5} | Comprobantes: {6}'),
    (N'FrmApp.menuTD05.Text', N'Controlar cumplimiento de viaje'),
    (N'FrmCumplimientoViaje.Title', N'Controlar cumplimiento de viaje'),
    (N'FrmCumplimientoViaje.grp0.Text', N'Viajes'),
    (N'FrmCumplimientoViaje.btnActualizar.Text', N'Actualizar'),
    (N'FrmCumplimientoViaje.dgvViajes.Numero.HeaderText', N'Viaje'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmCumplimientoViaje.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaInicio.HeaderText', N'Inicio'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaFinalizacion.HeaderText', N'Cierre'),
    (N'FrmCumplimientoViaje.grp1.Text', N'Resultados y comprobantes'),
    (N'FrmCumplimientoViaje.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaPrevista.HeaderText', N'Fecha prevista'),
    (N'FrmCumplimientoViaje.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaRealizada.HeaderText', N'Fecha real'),
    (N'FrmCumplimientoViaje.dgvEntregas.Observaciones.HeaderText', N'Observaciones'),
    (N'FrmCumplimientoViaje.dgvEntregas.NumeroComprobante.HeaderText', N'Comprobante'),
    (N'FrmCumplimientoViaje.grp2.Text', N'Cumplimiento'),
    (N'FrmCumplimientoViaje.btnCerrar.Text', N'Cerrar viaje');
-- Fin traducciones TD


INSERT INTO dbo.TRADUCCION (
    Id_Idioma,
    Clave_Traduccion,
    Valor_Traduccion
)
SELECT
    @IdIdioma_es_AR,
    origen.Clave_Traduccion,
    origen.Valor_Traduccion
FROM @Traducciones_es_AR AS origen
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.TRADUCCION AS destino
    WHERE destino.Id_Idioma = @IdIdioma_es_AR
      AND destino.Clave_Traduccion = origen.Clave_Traduccion
);

-- Configuración de conexión e inicialización de la base.
DECLARE @Conexion_es_AR TABLE (Clave NVARCHAR(200), Valor NVARCHAR(1000));
INSERT @Conexion_es_AR VALUES
(N'BD.SinConfigurar',N'No hay una conexión a base de datos configurada. Configure el servidor y la base antes de iniciar sesión.'),
(N'BD.ConexionFallida',N'No se pudo conectar a SQL Server. Revise servidor, puerto, servicio, red y certificado. No desactive la validación del certificado salvo que confíe en ese servidor.'),
(N'BD.Autenticacion',N'SQL Server rechazó las credenciales. Revise el usuario, la contraseña y el modo de autenticación habilitado.'),
(N'BD.BaseInaccesible',N'La base no existe o su cuenta no tiene acceso. Conecte al servidor y seleccione una base accesible.'),
(N'BD.PermisosSQL',N'La cuenta de SQL Server no tiene permisos suficientes para la operación.'),
(N'BD.BaseExiste',N'Ya existe una base con ese nombre. Selecciónela y verifíquela.'),
(N'BD.Metadatos',N'Se requiere permiso VIEW DEFINITION en la base para comprobar sus objetos.'),
(N'BD.BaseSistema',N'No se permite utilizar ni inicializar una base de sistema.'),
(N'BD.NoVacia',N'La base contiene objetos. No se ejecutó la inicialización. Use Database para una actualización controlada.'),
(N'BD.Incompatible',N'La base no está lista: faltan objetos o datos iniciales. Si contiene objetos, solicite una actualización con Database; no se sobrescribirán datos.'),
(N'BD.ConfiguracionLocal',N'No se pudo leer o guardar la configuración local protegida. Revise los permisos del perfil de Windows y vuelva a configurar la conexión.'),
(N'BD.PaqueteAusente',N'Falta el paquete DatabaseSetup. Repare o vuelva a instalar la aplicación.'),
(N'BD.DatosInvalidos',N'Complete servidor y base. Para puerto TCP use sólo el host, sin instancia ni coma. Complete el usuario cuando utilice autenticación SQL Server.'),
(N'BD.ClaveInicial',N'Para crear el usuario admin de SistemaLogistica, complete una contraseña nueva de al menos 8 caracteres y repítala exactamente. No es la contraseña de SQL Server. Luego pulse Inicializar base.'),
(N'BD.SinPermiso',N'No tiene permiso para configurar la base de datos.'),
(N'BD.Instrucciones',N'Conecte al servidor, seleccione una base y pulse Verificar estructura de la base. Guarde sólo después de una verificación correcta.'),
(N'BD.Busqueda',N'Búsqueda finalizada. La lista puede estar incompleta; escriba manualmente el servidor si no aparece.'),
(N'BD.Conectado',N'Conexión al servidor correcta. Seleccione una base de la lista, o escriba un nombre nuevo y pulse Crear base vacía.'),
(N'BD.Trabajando',N'Operación en curso. Espere a que finalice.'),
(N'BD.Compatible',N'Conexión correcta. Los objetos y datos iniciales requeridos están presentes. Puede guardar la conexión.'),
(N'BD.Vacia',N'La base está vacía: todavía no puede guardar la conexión. En Administrador inicial de SistemaLogistica escriba una contraseña nueva de al menos 8 caracteres y repítala. Pulse Inicializar base para crear los objetos y habilitar Guardar conexión.'),
(N'BD.AdminCreado',N'Usuario inicial: admin. Ingrese con la contraseña elegida en este formulario.'),
(N'BD.ConfirmarCrear',N'¿Crear una base vacía con el nombre indicado en el servidor seleccionado?'),
(N'BD.ConfirmarInicializar',N'¿Crear las tablas, procedimientos y datos iniciales en la base vacía seleccionada?'),
(N'BD.ConfirmarGuardar',N'¿Guardar esta conexión protegida para este usuario de Windows y continuar al login?'),
(N'BD.ConfirmarReinicio',N'¿Guardar esta conexión y reiniciar la aplicación? Se cerrará la sesión y se perderán los cambios sin guardar en las ventanas abiertas.'),
(N'BD.Error',N'No se pudo completar la operación de base de datos. Revise la configuración y los recursos de instalación.'),
(N'FrmConfiguracionBD.Title',N'Configurar base de datos'),
(N'FrmConfiguracionBD.lblServidor.Text',N'Servidor o servidor\instancia'),
(N'FrmConfiguracionBD.lblPuerto.Text',N'Puerto TCP (0 = predeterminado)'),
(N'FrmConfiguracionBD.lblAutenticacion.Text',N'Autenticación'),
(N'FrmConfiguracionBD.chkWindows.Text',N'Usar autenticación de Windows'),
(N'FrmConfiguracionBD.lblUsuario.Text',N'Usuario SQL Server'),
(N'FrmConfiguracionBD.lblClave.Text',N'Contraseña SQL Server'),
(N'FrmConfiguracionBD.lblCifrado.Text',N'Conexión cifrada'),
(N'FrmConfiguracionBD.chkCertificado.Text',N'Confiar en el certificado del servidor'),
(N'FrmConfiguracionBD.lblBase.Text',N'Base existente o nombre nuevo'),
(N'FrmConfiguracionBD.lblAdmin.Text',N'Contraseña nueva (mínimo 8 caracteres)'),
(N'FrmConfiguracionBD.lblRepetir.Text',N'Repetir contraseña nueva'),
(N'FrmConfiguracionBD.lblAyuda.Text',N'Buscar instancias es opcional. También puede escribir el servidor. Para SQL Server, desmarque autenticación Windows. La clave de admin sólo se usa al inicializar una base vacía (mínimo 8 caracteres).'),
(N'FrmConfiguracionBD.btnBuscar.Text',N'Buscar instancias'),
(N'FrmConfiguracionBD.btnConectar.Text',N'Conectar y listar bases'),
(N'FrmConfiguracionBD.btnCrear.Text',N'Crear base vacía'),
(N'FrmConfiguracionBD.btnVerificar.Text',N'Verificar estructura de la base'),
(N'FrmConfiguracionBD.btnInicializar.Text',N'Inicializar base'),
(N'FrmConfiguracionBD.btnGuardar.Text',N'Guardar conexión'),
(N'FrmConfiguracionBD.btnCancelar.Text',N'Cancelar'),
(N'FrmApp.menuConfiguracionBD.Text',N'Configurar base de datos');
INSERT @Conexion_es_AR VALUES
(N'FrmConfiguracionBD.grpAdmin.Text',N'Administrador inicial de SistemaLogistica'),
(N'FrmConfiguracionBD.lblNotaAdmin.Text',N'Sólo para una base vacía: cree la clave del usuario admin de la aplicación. No es una credencial de SQL Server.');
INSERT dbo.TRADUCCION(Id_Idioma,Clave_Traduccion,Valor_Traduccion)
SELECT @IdIdioma_es_AR,Clave,Valor FROM @Conexion_es_AR C
WHERE NOT EXISTS (SELECT 1 FROM dbo.TRADUCCION T WHERE T.Id_Idioma=@IdIdioma_es_AR AND T.Clave_Traduccion=C.Clave);

-- Mensajes de carga opcional de datos de prueba.
DECLARE @Demo TABLE(Clave NVARCHAR(200), Valor NVARCHAR(1000));
INSERT @Demo VALUES
(N'FrmConfiguracionBD.btnDatosPrueba.Text',N'Inicializar datos de prueba'),
(N'BD.ConfirmarDemo',N'¿Agregar usuarios y operaciones ficticias TD en la base seleccionada? Use una base de pruebas. No se restablecerán datos existentes. Se generará una contraseña para los cuatro usuarios demo.'),
(N'BD.DemoCargado',N'Datos de prueba cargados. Usuarios: demo_planificador, demo_expedicion, demo_transporte y demo_consulta. Contraseña común: {0}. Anótela antes de cerrar; no se mostrará nuevamente. El usuario admin conserva su contraseña.'),
(N'BD.DemoExistente',N'Los datos de prueba ya fueron cargados. No se duplicaron registros ni se restablecieron contraseñas o avances.'),
(N'BD.DemoColision',N'Existen registros con nombres reservados para DEMO. No se modificó la base. Utilice otra base de pruebas.'),
(N'BD.DemoIntegridad',N'La integridad de usuarios no es válida. No se cargaron datos ni se recalcularon sus verificadores.'),
(N'BD.DemoError',N'No se pudo cargar el conjunto de prueba. La operación fue revertida.');
INSERT dbo.TRADUCCION(Id_Idioma,Clave_Traduccion,Valor_Traduccion)
SELECT @IdIdioma_es_AR,Clave,Valor FROM @Demo D WHERE NOT EXISTS (SELECT 1 FROM dbo.TRADUCCION T WHERE T.Id_Idioma=@IdIdioma_es_AR AND T.Clave_Traduccion=D.Clave);

-- Mantenimiento y disponibilidad de flota.
DECLARE @MF TABLE(Clave NVARCHAR(200),Valor NVARCHAR(1000));
INSERT @MF VALUES
(N'MF.SinPermiso',N'No tiene permiso para esta operación.'),
(N'MF.Seleccionar',N'Seleccione un registro.'),
(N'MF.DatosInvalidos',N'Complete los campos obligatorios y revise fechas, cantidades y resultado.'),
(N'MF.Kilometraje',N'La unidad debe estar activa y el kilometraje no puede disminuir.'),
(N'MF.EnViaje',N'La unidad está realizando un viaje. No puede modificarse su condición.'),
(N'MF.Pendientes',N'La unidad no está habilitada o tiene partes, órdenes o tareas pendientes.'),
(N'MF.EstadoInvalido',N'La operación no corresponde al estado actual. Actualice la lista y revise la selección y la fecha programada.'),
(N'MF.Asignada',N'La unidad ya está asignada a otro viaje sin cerrar.'),
(N'MF.Duplicado',N'El registro ya existe. Actualice la lista antes de continuar.'),
(N'MF.Concurrencia',N'Otra operación está utilizando la flota. Vuelva a intentar.'),
(N'MF.Confirmar',N'¿Confirma la operación?'),
(N'MF.Guardado',N'Operación registrada correctamente.'),
(N'MF.Error',N'No se pudo completar la operación. Actualice y vuelva a intentar.'),
(N'MF.Titulo',N'Mantenimiento y flota'),
(N'FrmApp.menuMF.Text',N'Mantenimiento y flota'),
(N'MF.Valor.FueraServicio',N'Fuera de servicio'),
(N'MF.Valor.EnMantenimiento',N'En mantenimiento'),
(N'MF.Valor.PendienteVerificacion',N'Pendiente de verificación'),
(N'MF.Valor.Disponible',N'Disponible'),
(N'MF.Valor.Pendiente',N'Pendiente'),
(N'MF.Valor.Programado',N'Programado'),
(N'MF.Valor.Resuelto',N'Resuelto'),
(N'MF.Valor.Programada',N'Programada'),
(N'MF.Valor.EnCurso',N'En curso'),
(N'MF.Valor.Cerrada',N'Cerrada'),
(N'MF.Valor.Satisfactoria',N'Satisfactoria'),
(N'MF.Valor.RequiereTareas',N'Requiere más tareas'),
(N'MF.Valor.Preventivo',N'Preventivo'),
(N'MF.Valor.Correctivo',N'Correctivo'),
(N'MF.Valor.Baja',N'Baja'),
(N'MF.Valor.Media',N'Media'),
(N'MF.Valor.Alta',N'Alta'),
(N'MF.Valor.Urgente',N'Urgente'),
(N'MF.Valor.Planificado',N'Planificado'),
(N'MF.Valor.Preparado',N'Preparado'),
(N'FrmApp.menuMF01.Text',N'Registrar estado de flota'),
(N'FrmApp.menuMF02.Text',N'Programar mantenimiento'),
(N'FrmApp.menuMF03.Text',N'Registrar intervención de mantenimiento'),
(N'FrmApp.menuMF04.Text',N'Habilitar unidad para operar'),
(N'FrmApp.menuMF05.Text',N'Consultar disponibilidad y asignar unidad'),
(N'FrmEstadoFlota.Title',N'Registrar estado de flota'),
(N'FrmEstadoFlota.grpdgvUnidades.Text',N'Unidades'),
(N'FrmEstadoFlota.dgvUnidades.IdUnidadFlota.HeaderText',N'Unidad'),
(N'FrmEstadoFlota.dgvUnidades.Dominio.HeaderText',N'Dominio'),
(N'FrmEstadoFlota.dgvUnidades.Tipo.HeaderText',N'Tipo'),
(N'FrmEstadoFlota.dgvUnidades.Marca.HeaderText',N'Marca'),
(N'FrmEstadoFlota.dgvUnidades.Modelo.HeaderText',N'Modelo'),
(N'FrmEstadoFlota.dgvUnidades.Anio.HeaderText',N'Año'),
(N'FrmEstadoFlota.dgvUnidades.Capacidad.HeaderText',N'Capacidad'),
(N'FrmEstadoFlota.dgvUnidades.KilometrajeActual.HeaderText',N'Kilometraje actual'),
(N'FrmEstadoFlota.dgvUnidades.EstadoOperativo.HeaderText',N'Estado operativo'),
(N'FrmEstadoFlota.grpdgvPartes.Text',N'Partes de la unidad'),
(N'FrmEstadoFlota.dgvPartes.IdParteEstadoUnidad.HeaderText',N'Parte'),
(N'FrmEstadoFlota.dgvPartes.FechaHora.HeaderText',N'Fecha y hora'),
(N'FrmEstadoFlota.dgvPartes.Kilometraje.HeaderText',N'Kilometraje'),
(N'FrmEstadoFlota.dgvPartes.TipoNovedad.HeaderText',N'Novedad'),
(N'FrmEstadoFlota.dgvPartes.Descripcion.HeaderText',N'Descripción'),
(N'FrmEstadoFlota.dgvPartes.RequiereMantenimiento.HeaderText',N'Requiere mantenimiento'),
(N'FrmEstadoFlota.dgvPartes.EstadoParte.HeaderText',N'Estado del parte'),
(N'FrmEstadoFlota.lbltxtDominio.Text',N'Dominio'),
(N'FrmEstadoFlota.lbltxtTipo.Text',N'Tipo'),
(N'FrmEstadoFlota.lbltxtMarca.Text',N'Marca'),
(N'FrmEstadoFlota.lbltxtModelo.Text',N'Modelo'),
(N'FrmEstadoFlota.lblnudAnio.Text',N'Año'),
(N'FrmEstadoFlota.lblnudCapacidad.Text',N'Capacidad'),
(N'FrmEstadoFlota.lblnudKmInicial.Text',N'Kilometraje inicial'),
(N'FrmEstadoFlota.btnCrear.Text',N'Crear unidad'),
(N'FrmEstadoFlota.grpalta.Text',N'Nueva unidad'),
(N'FrmEstadoFlota.lblnudKm.Text',N'Kilometraje'),
(N'FrmEstadoFlota.lbltxtNovedad.Text',N'Novedad'),
(N'FrmEstadoFlota.lbltxtDescripcion.Text',N'Descripción'),
(N'FrmEstadoFlota.lblchkMantenimiento.Text',N'Requiere mantenimiento'),
(N'FrmEstadoFlota.btnRegistrar.Text',N'Registrar estado'),
(N'FrmEstadoFlota.btnActualizar.Text',N'Actualizar'),
(N'FrmEstadoFlota.grpestado.Text',N'Estado de la unidad seleccionada'),
(N'FrmProgramarMantenimiento.Title',N'Programar mantenimiento'),
(N'FrmProgramarMantenimiento.grpdgvPartes.Text',N'Partes pendientes'),
(N'FrmProgramarMantenimiento.dgvPartes.IdParteEstadoUnidad.HeaderText',N'Parte'),
(N'FrmProgramarMantenimiento.dgvPartes.Dominio.HeaderText',N'Dominio'),
(N'FrmProgramarMantenimiento.dgvPartes.FechaHora.HeaderText',N'Fecha y hora'),
(N'FrmProgramarMantenimiento.dgvPartes.Kilometraje.HeaderText',N'Kilometraje'),
(N'FrmProgramarMantenimiento.dgvPartes.TipoNovedad.HeaderText',N'Novedad'),
(N'FrmProgramarMantenimiento.dgvPartes.Descripcion.HeaderText',N'Descripción'),
(N'FrmProgramarMantenimiento.grpdgvOrdenes.Text',N'Órdenes de mantenimiento'),
(N'FrmProgramarMantenimiento.dgvOrdenes.IdOrdenMantenimiento.HeaderText',N'Orden'),
(N'FrmProgramarMantenimiento.dgvOrdenes.Dominio.HeaderText',N'Dominio'),
(N'FrmProgramarMantenimiento.dgvOrdenes.FechaProgramada.HeaderText',N'Fecha programada'),
(N'FrmProgramarMantenimiento.dgvOrdenes.TipoMantenimiento.HeaderText',N'Tipo de mantenimiento'),
(N'FrmProgramarMantenimiento.dgvOrdenes.Prioridad.HeaderText',N'Prioridad'),
(N'FrmProgramarMantenimiento.dgvOrdenes.DescripcionTrabajo.HeaderText',N'Trabajo previsto'),
(N'FrmProgramarMantenimiento.dgvOrdenes.EstadoOrden.HeaderText',N'Estado de orden'),
(N'FrmProgramarMantenimiento.lbldtpProgramada.Text',N'Fecha programada'),
(N'FrmProgramarMantenimiento.lblcmbTipo.Text',N'Tipo'),
(N'FrmProgramarMantenimiento.lblcmbPrioridad.Text',N'Prioridad'),
(N'FrmProgramarMantenimiento.lbltxtTrabajo.Text',N'Trabajo previsto'),
(N'FrmProgramarMantenimiento.btnProgramar.Text',N'Programar'),
(N'FrmProgramarMantenimiento.btnActualizar.Text',N'Actualizar'),
(N'FrmProgramarMantenimiento.grpprograma.Text',N'Programación del parte seleccionado'),
(N'FrmIntervencionMantenimiento.Title',N'Registrar intervención de mantenimiento'),
(N'FrmIntervencionMantenimiento.grpdgvOrdenes.Text',N'Órdenes de mantenimiento'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.IdOrdenMantenimiento.HeaderText',N'Orden'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.Dominio.HeaderText',N'Dominio'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.FechaProgramada.HeaderText',N'Fecha programada'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.TipoMantenimiento.HeaderText',N'Tipo de mantenimiento'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.Prioridad.HeaderText',N'Prioridad'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.DescripcionTrabajo.HeaderText',N'Trabajo previsto'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.EstadoOrden.HeaderText',N'Estado de orden'),
(N'FrmIntervencionMantenimiento.grpdgvIntervenciones.Text',N'Intervenciones de la orden'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.IdIntervencionMantenimiento.HeaderText',N'Intervención'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.FechaInicio.HeaderText',N'Inicio'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.FechaFin.HeaderText',N'Finalización'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.Kilometraje.HeaderText',N'Kilometraje'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.TrabajoRealizado.HeaderText',N'Trabajo realizado'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.Resultado.HeaderText',N'Resultado'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.Observaciones.HeaderText',N'Observaciones'),
(N'FrmIntervencionMantenimiento.lblnudKm.Text',N'Kilometraje'),
(N'FrmIntervencionMantenimiento.lbltxtTrabajo.Text',N'Trabajo realizado'),
(N'FrmIntervencionMantenimiento.lblcmbResultado.Text',N'Resultado'),
(N'FrmIntervencionMantenimiento.lbltxtObservaciones.Text',N'Observaciones'),
(N'FrmIntervencionMantenimiento.btnIniciar.Text',N'Iniciar intervención'),
(N'FrmIntervencionMantenimiento.btnFinalizar.Text',N'Finalizar intervención'),
(N'FrmIntervencionMantenimiento.btnActualizar.Text',N'Actualizar'),
(N'FrmIntervencionMantenimiento.grpintervencion.Text',N'Tareas y resultado'),
(N'FrmHabilitarUnidad.Title',N'Habilitar unidad para operar'),
(N'FrmHabilitarUnidad.grpdgvUnidades.Text',N'Unidades'),
(N'FrmHabilitarUnidad.dgvUnidades.IdUnidadFlota.HeaderText',N'Unidad'),
(N'FrmHabilitarUnidad.dgvUnidades.Dominio.HeaderText',N'Dominio'),
(N'FrmHabilitarUnidad.dgvUnidades.KilometrajeActual.HeaderText',N'Kilometraje actual'),
(N'FrmHabilitarUnidad.dgvUnidades.EstadoOperativo.HeaderText',N'Estado operativo'),
(N'FrmHabilitarUnidad.grpdgvIntervenciones.Text',N'Intervenciones de la unidad'),
(N'FrmHabilitarUnidad.dgvIntervenciones.IdOrdenMantenimiento.HeaderText',N'Orden'),
(N'FrmHabilitarUnidad.dgvIntervenciones.IdIntervencionMantenimiento.HeaderText',N'Intervención'),
(N'FrmHabilitarUnidad.dgvIntervenciones.FechaFin.HeaderText',N'Finalización'),
(N'FrmHabilitarUnidad.dgvIntervenciones.TrabajoRealizado.HeaderText',N'Trabajo realizado'),
(N'FrmHabilitarUnidad.dgvIntervenciones.Resultado.HeaderText',N'Resultado'),
(N'FrmHabilitarUnidad.dgvIntervenciones.Observaciones.HeaderText',N'Observaciones'),
(N'FrmHabilitarUnidad.grpdgvInformes.Text',N'Historial de disponibilidad'),
(N'FrmHabilitarUnidad.dgvInformes.IdInformeDisponibilidad.HeaderText',N'Informe'),
(N'FrmHabilitarUnidad.dgvInformes.FechaHora.HeaderText',N'Fecha y hora'),
(N'FrmHabilitarUnidad.dgvInformes.Disponible.HeaderText',N'Disponible'),
(N'FrmHabilitarUnidad.dgvInformes.EstadoUnidad.HeaderText',N'Estado de unidad'),
(N'FrmHabilitarUnidad.dgvInformes.Observaciones.HeaderText',N'Observaciones'),
(N'FrmHabilitarUnidad.dgvInformes.Vigente.HeaderText',N'Vigente'),
(N'FrmHabilitarUnidad.lbltxtObservaciones.Text',N'Observaciones'),
(N'FrmHabilitarUnidad.btnHabilitar.Text',N'Confirmar habilitación'),
(N'FrmHabilitarUnidad.btnActualizar.Text',N'Actualizar'),
(N'FrmHabilitarUnidad.grphabilitacion.Text',N'Verificación de condiciones'),
(N'FrmDisponibilidadFlota.Title',N'Consultar disponibilidad y asignar unidad'),
(N'FrmDisponibilidadFlota.grpdgvViajes.Text',N'Viajes por iniciar'),
(N'FrmDisponibilidadFlota.dgvViajes.IdViaje.HeaderText',N'Viaje'),
(N'FrmDisponibilidadFlota.dgvViajes.Numero.HeaderText',N'Número'),
(N'FrmDisponibilidadFlota.dgvViajes.FechaPrevista.HeaderText',N'Fecha prevista'),
(N'FrmDisponibilidadFlota.dgvViajes.Estado.HeaderText',N'Estado'),
(N'FrmDisponibilidadFlota.dgvViajes.IdUnidadFlota.HeaderText',N'Unidad'),
(N'FrmDisponibilidadFlota.dgvViajes.IdInformeDisponibilidad.HeaderText',N'Informe'),
(N'FrmDisponibilidadFlota.grpdgvUnidades.Text',N'Unidades disponibles para el viaje seleccionado'),
(N'FrmDisponibilidadFlota.dgvUnidades.IdUnidadFlota.HeaderText',N'Unidad'),
(N'FrmDisponibilidadFlota.dgvUnidades.Dominio.HeaderText',N'Dominio'),
(N'FrmDisponibilidadFlota.dgvUnidades.Tipo.HeaderText',N'Tipo'),
(N'FrmDisponibilidadFlota.dgvUnidades.Capacidad.HeaderText',N'Capacidad'),
(N'FrmDisponibilidadFlota.dgvUnidades.KilometrajeActual.HeaderText',N'Kilometraje actual'),
(N'FrmDisponibilidadFlota.dgvUnidades.EstadoOperativo.HeaderText',N'Estado operativo'),
(N'FrmDisponibilidadFlota.grpdgvInformes.Text',N'Informes vigentes de las unidades disponibles'),
(N'FrmDisponibilidadFlota.dgvInformes.IdInformeDisponibilidad.HeaderText',N'Informe'),
(N'FrmDisponibilidadFlota.dgvInformes.IdUnidadFlota.HeaderText',N'Unidad'),
(N'FrmDisponibilidadFlota.dgvInformes.FechaHora.HeaderText',N'Fecha y hora'),
(N'FrmDisponibilidadFlota.dgvInformes.Disponible.HeaderText',N'Disponible'),
(N'FrmDisponibilidadFlota.dgvInformes.Observaciones.HeaderText',N'Observaciones'),
(N'FrmDisponibilidadFlota.btnAsignar.Text',N'Asignar unidad'),
(N'FrmDisponibilidadFlota.btnActualizar.Text',N'Actualizar'),
(N'FrmDisponibilidadFlota.grpasignacion.Text',N'Asignación de unidad al viaje seleccionado');
INSERT dbo.TRADUCCION(Id_Idioma,Clave_Traduccion,Valor_Traduccion)
SELECT @IdIdioma_es_AR,Clave,Valor FROM @MF M WHERE NOT EXISTS(SELECT 1 FROM dbo.TRADUCCION T WHERE T.Id_Idioma=@IdIdioma_es_AR AND T.Clave_Traduccion=M.Clave);

-- Carga opcional e independiente de ejemplos MF.
DECLARE @DemoMF TABLE(Clave NVARCHAR(200),Valor NVARCHAR(1000));
INSERT @DemoMF VALUES
(N'FrmConfiguracionBD.btnDatosPruebaMF.Text',N'Inicializar datos de prueba MF'),
(N'BD.ConfirmarDemoMF',N'¿Agregar usuarios y operaciones ficticias MF? Use una base de pruebas. No se restablecerán datos existentes. Se generará una contraseña para los tres usuarios MF.'),
(N'BD.DemoMFCargado',N'Datos MF cargados. Usuarios: demo_flota, demo_mantenimiento y demo_trafico_mf. Contraseña común: {0}. Anótela antes de cerrar; no se mostrará nuevamente. Las contraseñas anteriores no cambian.');
INSERT dbo.TRADUCCION(Id_Idioma,Clave_Traduccion,Valor_Traduccion)
SELECT @IdIdioma_es_AR,Clave,Valor FROM @DemoMF M WHERE NOT EXISTS(SELECT 1 FROM dbo.TRADUCCION T WHERE T.Id_Idioma=@IdIdioma_es_AR AND T.Clave_Traduccion=M.Clave);
