/*
Seed de traducciones base: English.

Este script inserta solamente las traducciones que no existen.
No actualiza traducciones existentes para no pisar cambios hechos desde la aplicación por un administrador.
*/

DECLARE @IdIdioma_en_US INT;

SELECT @IdIdioma_en_US = Id_Idioma
FROM dbo.IDIOMA
WHERE Codigo_Idioma = N'en-US';

IF @IdIdioma_en_US IS NULL
BEGIN
    RAISERROR('No existe el idioma en-US. Revisar el script 001_idiomas.sql.', 16, 1);
    RETURN;
END;

DECLARE @Traducciones_en_US TABLE (
    Clave_Traduccion NVARCHAR(200) NOT NULL PRIMARY KEY,
    Valor_Traduccion NVARCHAR(1000) NULL
);

INSERT INTO @Traducciones_en_US (
    Clave_Traduccion,
    Valor_Traduccion
)
VALUES
    (N'Common.btnAceptar.Text', N'OK'),
    (N'Common.btnBorrar.Text', N'Delete'),
    (N'Common.btnBuscar.Text', N'Search'),
    (N'Common.btnCancelar.Text', N'Cancel'),
    (N'Common.btnEditar.Text', N'Edit'),
    (N'Common.btnGuardar.Text', N'Save'),
    (N'Common.btnNuevo.Text', N'New'),
    (N'Common.btnSalir.Text', N'Exit'),
    (N'Common.msgConfirmar', N'Confirm'),
    (N'Common.msgError', N'Error'),
    (N'FrmABMRoles.Title', N'Role management'),
    (N'FrmABMRoles.btnAsignar.Text', N'Assign'),
    (N'FrmABMRoles.btnInsertar.Text', N'Insert'),
    (N'FrmABMRoles.btnQuitar.Text', N'Remove'),
    (N'FrmABMRoles.btnborrar.Text', N'Delete'),
    (N'FrmABMRoles.btnlistar.Text', N'List'),
    (N'FrmABMRoles.btnmodificar.Text', N'Modify'),
    (N'FrmABMRoles.groupBox1.Text', N'Roles'),
    (N'FrmABMRoles.groupBox2.Text', N'Permissions'),
    (N'FrmABMRoles.lblPermiso.Text', N'Permission'),
    (N'FrmABMRoles.lblIdRol.Text', N'Role id'),
    (N'FrmABMRoles.lblNombreRol.Text', N'Name'),
    (N'FrmABMUsuarios.Title', N'User management'),
    (N'FrmABMUsuarios.btnInsertar.Text', N'Insert'),
    (N'FrmABMUsuarios.btnRestaurarVersAnt.Text', N'Restore version'),
    (N'FrmABMUsuarios.btnborrar.Text', N'Delete'),
    (N'FrmABMUsuarios.btnlistar.Text', N'List'),
    (N'FrmABMUsuarios.btnmodificar.Text', N'Modify'),
    (N'FrmABMUsuarios.groupBox1.Text', N'Recover previous states'),
    (N'FrmABMUsuarios.lblClave.Text', N'Password'),
    (N'FrmABMUsuarios.lblD.Text', N'ID'),
    (N'FrmABMUsuarios.lblIdUsuarioSeleccionado.Text', N'Selected id'),
    (N'FrmABMUsuarios.lblNombre.Text', N'Name'),
    (N'FrmABMUsuarios.lblPerfil.Text', N'Profile'),
    (N'FrmABMUsuarios.lblUsuarioSeleccionado.Text', N'Selected user'),
    (N'FrmABMUsuarios.msgClaveNoCumple', N'The password does not meet the requirements. It must have at least 6 characters, one uppercase letter, and one number.'),
    (N'FrmApp.Title', N'Administrative management system'),
    (N'FrmApp.archivoToolStripMenuItem.Text', N'File'),
    (N'FrmApp.bitácoraToolStripMenuItem.Text', N'Audit log'),
    (N'FrmApp.cerrarSesiónToolStripMenuItem.Text', N'Log out'),
    (N'FrmApp.clientesToolStripMenuItem.Text', N'New sale'),
    (N'FrmApp.gestiónToolStripMenuItem.Text', N'Management'),
    (N'FrmApp.historialToolStripMenuItem.Text', N'History'),
    (N'FrmApp.idiomasToolStripMenuItem.Text', N'Languages'),
    (N'FrmApp.msgConfirmarCerrarSesion', N'Do you really want to log out?'),
    (N'FrmApp.msgConfirmarSalir', N'Do you really want to log out and exit?'),
    (N'FrmApp.msgErrorAbrirIdiomas', N'The language form could not be opened.'),
    (N'FrmApp.msgTituloConfirmarSalida', N'Confirm exit'),
    (N'FrmApp.perfilesToolStripMenuItem.Text', N'Profiles'),
    (N'FrmApp.productosToolStripMenuItem.Text', N'Customers'),
    (N'FrmApp.productosToolStripMenuItem1.Text', N'Products'),
    (N'FrmApp.salirToolStripMenuItem.Text', N'Exit'),
    (N'FrmApp.seguridadToolStripMenuItem.Text', N'Security'),
    (N'FrmApp.usuariosToolStripMenuItem.Text', N'Users'),
    (N'FrmBitacora.Title', N'Audit log'),
    (N'FrmBitacora.btnBuscar.Text', N'Search'),
    (N'FrmBitacora.gbFiltros.Text', N'Filters'),
    (N'FrmBitacora.lblFechaDesde.Text', N'Start date'),
    (N'FrmBitacora.lblFechaHasta.Text', N'End date'),
    (N'FrmBitacora.lblUsuario.Text', N'User'),
    (N'FrmIdioma.Title', N'Language management'),
    (N'FrmIdioma.btnActivar.Text', N'Enable'),
    (N'FrmIdioma.btnBorrar.Text', N'Delete'),
    (N'FrmIdioma.btnCargarTraducciones.Text', N'Load translations'),
    (N'FrmIdioma.btnDesactivar.Text', N'Disable'),
    (N'FrmIdioma.btnEditar.Text', N'Edit'),
    (N'FrmIdioma.btnGuardarTraducciones.Text', N'Save translations'),
    (N'FrmIdioma.btnNuevo.Text', N'New'),
    (N'FrmIdioma.btnSetDefault.Text', N'Default'),
    (N'FrmIdioma.gbIdiomas.Text', N'Available languages'),
    (N'FrmIdioma.gbTraducciones.Text', N'Translations for the selected language'),
    (N'FrmIdioma.dgvIdiomas.Codigo.HeaderText', N'Code'),
    (N'FrmIdioma.dgvIdiomas.Habilitado.HeaderText', N'Enabled'),
    (N'FrmIdioma.dgvIdiomas.EsDefault.HeaderText', N'Default'),
    (N'FrmIdioma.dgvIdiomas.Id_Idioma.HeaderText', N'Id'),
    (N'FrmIdioma.dgvIdiomas.Nombre.HeaderText', N'Name'),
    (N'FrmIdioma.dgvTraducciones.Clave.HeaderText', N'Key'),
    (N'FrmIdioma.dgvTraducciones.Id_Idioma.HeaderText', N'Language'),
    (N'FrmIdioma.dgvTraducciones.Id_Traduccion.HeaderText', N'Id'),
    (N'FrmIdioma.dgvTraducciones.Valor.HeaderText', N'Value'),
    (N'FrmIdioma.msgAccesoDenegado', N'Access denied. Administrator role required.'),
    (N'FrmIdioma.msgBorrarIdioma', N'Delete language?'),
    (N'FrmIdioma.msgConfirmar', N'Confirm'),
    (N'FrmIdioma.msgTraduccionesGuardadas', N'Translations saved.'),
    (N'FrmIdiomaEditor.Title', N'Language'),
    (N'FrmIdiomaEditor.btnCancel.Text', N'Cancel'),
    (N'FrmIdiomaEditor.btnOk.Text', N'OK'),
    (N'FrmIdiomaEditor.chkHabilitado.Text', N'Enabled'),
    (N'FrmIdiomaEditor.lblCodigo.Text', N'Code:'),
    (N'FrmIdiomaEditor.lblNombre.Text', N'Name:'),
    (N'FrmLogin.Title', N'Login'),
    (N'FrmLogin.btnIngresar.Text', N'Log in'),
    (N'FrmLogin.btnSalir.Text', N'Exit'),
    (N'FrmLogin.cmbIdiomasLogin.Text', N'Language'),
    (N'FrmLogin.lblClave.Text', N'Password'),
    (N'FrmLogin.lblUsuario.Text', N'User'),
    (N'FrmLogin.msgCamposRequeridos', N'All fields are required.'),
    (N'FrmLogin.msgCredencialesInvalidas', N'Incorrect or nonexistent username and/or password.'),
    (N'FrmLogin.msgIngresoExitoso', N'Login successful.'),
    (N'FrmLogin.msgSistemaNoDisponible', N'The system is not available at this time. Please try again later.'),
    (N'frmRestore.Title', N'Integrity restore'),
    (N'frmRestore.btnCancelar.Text', N'Cancel'),
    (N'frmRestore.btnRecalcular.Text', N'Recalculate'),
    (N'frmRestore.btnRestore.Text', N'Restore database'),
    (N'frmRestore.lblIntegridadDVV.Text', N'Table integrity'),
    (N'frmRestore.lblRegistros.Text', N'Record integrity'),
    (N'frmRestore.msgIntegridadDVVCorrecta', N'Table integrity is correct.'),
    (N'frmRestore.msgIntegridadDVVFallida', N'Table integrity failed.'),
    (N'frmRestore.msgIntegridadRegistrosCorrecta', N'Record integrity is correct.'),
    (N'frmRestore.msgIntegridadRegistrosFallida', N'Record integrity failed.'),
    (N'frmRestore.msgRestauracionError', N'Error restoring the database.'),
    (N'frmRestore.msgRestauracionExitosa', N'Restore completed successfully.');

-- TD: traducciones de transporte y distribución
INSERT INTO @Traducciones_en_US (Clave_Traduccion, Valor_Traduccion)
VALUES
    (N'TD.SinPermiso', N'You do not have permission for this operation.'),
    (N'TD.DatosInvalidos', N'Complete the required fields and check their format and length.'),
    (N'TD.Duplicado', N'The number, code or product is already registered. Refresh the data.'),
    (N'TD.EstadoInvalido', N'The operation is not allowed in the current state. Refresh the data.'),
    (N'TD.PlanIncompleto', N'Each plan requires trips; each trip requires deliveries and planned cargo.'),
    (N'TD.CantidadInvalida', N'Enter positive quantities with up to three decimal places.'),
    (N'TD.FechaEntrega', N'Check destinations and dates: a delivery cannot precede its trip.'),
    (N'TD.Error', N'The operation could not be completed. Check the connection and refresh the data.'),
    (N'TD.Seleccionar', N'Select a record.'),
    (N'TD.Guardado', N'Operation saved successfully.'),
    (N'TD.Confirmar', N'Confirm this operation?'),
    (N'TD.Formato', N'The entered value has an invalid format.'),
    (N'FrmApp.menuTD.Text', N'Transport and distribution'),
    (N'FrmPlanificacionDistribucion.Title', N'Plan distribution'),
    (N'FrmPlanificacionDistribucion.grp0.Text', N'Request and plan'),
    (N'FrmPlanificacionDistribucion.lblRequerimiento.Text', N'Pending'),
    (N'FrmPlanificacionDistribucion.lblPlan.Text', N'Plan no.'),
    (N'FrmPlanificacionDistribucion.btnActualizar.Text', N'Refresh'),
    (N'FrmPlanificacionDistribucion.lblNuevoReq.Text', N'New request: number / origin'),
    (N'FrmPlanificacionDistribucion.btnRecibir.Text', N'Receive request'),
    (N'FrmPlanificacionDistribucion.grp1.Text', N'Trips in the plan'),
    (N'FrmPlanificacionDistribucion.lblViaje.Text', N'Trip no.'),
    (N'FrmPlanificacionDistribucion.lblFechaViaje.Text', N'Planned departure'),
    (N'FrmPlanificacionDistribucion.btnViaje.Text', N'Add trip'),
    (N'FrmPlanificacionDistribucion.btnQuitarViaje.Text', N'Remove trip'),
    (N'FrmPlanificacionDistribucion.dgvViajes.Numero.HeaderText', N'Number'),
    (N'FrmPlanificacionDistribucion.dgvViajes.FechaPrevista.HeaderText', N'Planned departure'),
    (N'FrmPlanificacionDistribucion.grp2.Text', N'Deliveries for selected trip'),
    (N'FrmPlanificacionDistribucion.lblDestino.Text', N'Destination'),
    (N'FrmPlanificacionDistribucion.btnEntrega.Text', N'Add delivery'),
    (N'FrmPlanificacionDistribucion.btnQuitarEntrega.Text', N'Remove delivery'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.Destino.HeaderText', N'Destination'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.FechaPrevista.HeaderText', N'Planned date'),
    (N'FrmPlanificacionDistribucion.grp3.Text', N'Planned cargo for selected trip'),
    (N'FrmPlanificacionDistribucion.lblCantidad.Text', N'Planned quantity'),
    (N'FrmPlanificacionDistribucion.btnCarga.Text', N'Add cargo'),
    (N'FrmPlanificacionDistribucion.btnQuitarCarga.Text', N'Remove cargo'),
    (N'FrmPlanificacionDistribucion.dgvCarga.IdMercaderia.HeaderText', N'Goods'),
    (N'FrmPlanificacionDistribucion.dgvCarga.CantidadPrevista.HeaderText', N'Planned quantity'),
    (N'FrmPlanificacionDistribucion.grp4.Text', N'Add catalog product'),
    (N'FrmPlanificacionDistribucion.lblCodigo.Text', N'Code'),
    (N'FrmPlanificacionDistribucion.lblDescripcion.Text', N'Description'),
    (N'FrmPlanificacionDistribucion.btnProducto.Text', N'Create product'),
    (N'FrmPlanificacionDistribucion.btnConfirmar.Text', N'Confirm plan'),
    (N'FrmApp.menuTD01.Text', N'Plan distribution'),
    (N'TD.CantidadPreparadaInvalida', N'Prepared quantities must be zero or positive, with up to three decimal places.'),
    (N'TD.ExpliqueDiferencia', N'Explain the differences in the notes.'),
    (N'TD.DespachoPendiente', N'Differences recorded. Dispatch remains pending and the trip cannot start.'),
    (N'TD.Estado.Pendiente', N'Pending'),
    (N'TD.Estado.Confirmado', N'Confirmed'),
    (N'TD.Estado.Planificado', N'Planned'),
    (N'TD.Estado.Preparado', N'Prepared'),
    (N'TD.Estado.EnCurso', N'In progress'),
    (N'TD.Estado.Cerrado', N'Closed'),
    (N'TD.Estado.Entregada', N'Delivered'),
    (N'TD.Estado.Parcial', N'Partial'),
    (N'TD.Estado.Incumplida', N'Failed'),
    (N'FrmApp.menuTD02.Text', N'Prepare dispatch'),
    (N'FrmPrepararDespacho.Title', N'Prepare dispatch'),
    (N'FrmPrepararDespacho.grp0.Text', N'Trips and preparation status'),
    (N'FrmPrepararDespacho.btnActualizar.Text', N'Refresh'),
    (N'FrmPrepararDespacho.dgvViajes.Numero.HeaderText', N'Trip'),
    (N'FrmPrepararDespacho.dgvViajes.FechaPrevista.HeaderText', N'Planned date'),
    (N'FrmPrepararDespacho.dgvViajes.Estado.HeaderText', N'Status'),
    (N'FrmPrepararDespacho.grp1.Text', N'Quantity comparison'),
    (N'FrmPrepararDespacho.dgvCarga.Codigo.HeaderText', N'Code'),
    (N'FrmPrepararDespacho.dgvCarga.Descripcion.HeaderText', N'Goods'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPrevista.HeaderText', N'Planned'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPreparada.HeaderText', N'Prepared'),
    (N'FrmPrepararDespacho.dgvCarga.Diferencia.HeaderText', N'Difference'),
    (N'FrmPrepararDespacho.grp2.Text', N'Dispatch document'),
    (N'FrmPrepararDespacho.lblNumero.Text', N'Dispatch no.'),
    (N'FrmPrepararDespacho.lblObservaciones.Text', N'Notes / differences'),
    (N'FrmPrepararDespacho.btnGuardar.Text', N'Save preparation'),
    (N'TD.InicioNoHabilitado', N'The trip requires a confirmed dispatch and matching cargo quantities.'),
    (N'TD.SinDespacho', N'No dispatch'),
    (N'FrmApp.menuTD03.Text', N'Start trip'),
    (N'FrmEjecucionViaje.Title', N'Start trip'),
    (N'FrmEjecucionViaje.grp0.Text', N'Trips'),
    (N'FrmEjecucionViaje.btnActualizar.Text', N'Refresh'),
    (N'FrmEjecucionViaje.dgvViajes.Numero.HeaderText', N'Trip'),
    (N'FrmEjecucionViaje.dgvViajes.FechaPrevista.HeaderText', N'Planned date'),
    (N'FrmEjecucionViaje.dgvViajes.Estado.HeaderText', N'Status'),
    (N'FrmEjecucionViaje.dgvViajes.FechaInicio.HeaderText', N'Start'),
    (N'FrmEjecucionViaje.grp1.Text', N'Dispatch document and cargo'),
    (N'FrmEjecucionViaje.dgvCarga.Codigo.HeaderText', N'Code'),
    (N'FrmEjecucionViaje.dgvCarga.Descripcion.HeaderText', N'Goods'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPrevista.HeaderText', N'Planned'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPreparada.HeaderText', N'Prepared'),
    (N'FrmEjecucionViaje.grp2.Text', N'Planned deliveries'),
    (N'FrmEjecucionViaje.dgvEntregas.Destino.HeaderText', N'Destination'),
    (N'FrmEjecucionViaje.dgvEntregas.FechaPrevista.HeaderText', N'Planned date'),
    (N'FrmEjecucionViaje.dgvEntregas.Estado.HeaderText', N'Status'),
    (N'FrmEjecucionViaje.grp3.Text', N'Trip start'),
    (N'FrmEjecucionViaje.btnIniciar.Text', N'Confirm start'),
    (N'TD.FechaResultado', N'The date must be between the trip start and the current time.'),
    (N'TD.ExpliqueResultado', N'Explain the partial or failed delivery.'),
    (N'FrmApp.menuTD04.Text', N'Record delivery'),
    (N'FrmRegistroEntrega.Title', N'Record delivery'),
    (N'FrmRegistroEntrega.grp0.Text', N'Trips in progress'),
    (N'FrmRegistroEntrega.btnActualizar.Text', N'Refresh'),
    (N'FrmRegistroEntrega.dgvViajes.Numero.HeaderText', N'Trip'),
    (N'FrmRegistroEntrega.dgvViajes.FechaPrevista.HeaderText', N'Planned date'),
    (N'FrmRegistroEntrega.dgvViajes.Estado.HeaderText', N'Status'),
    (N'FrmRegistroEntrega.grp1.Text', N'Deliveries and receipts'),
    (N'FrmRegistroEntrega.dgvEntregas.Destino.HeaderText', N'Destination'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaPrevista.HeaderText', N'Planned date'),
    (N'FrmRegistroEntrega.dgvEntregas.Estado.HeaderText', N'Status'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaRealizada.HeaderText', N'Actual date'),
    (N'FrmRegistroEntrega.dgvEntregas.Observaciones.HeaderText', N'Notes'),
    (N'FrmRegistroEntrega.dgvEntregas.NumeroComprobante.HeaderText', N'Receipt'),
    (N'FrmRegistroEntrega.grp2.Text', N'Result for selected delivery'),
    (N'FrmRegistroEntrega.lblResultado.Text', N'Result'),
    (N'FrmRegistroEntrega.lblFecha.Text', N'Date and time'),
    (N'FrmRegistroEntrega.lblObservaciones.Text', N'Notes'),
    (N'FrmRegistroEntrega.btnRegistrar.Text', N'Record result'),
    (N'TD.CierreNoHabilitado', N'Only an in-progress trip with every delivery completed and receipted can be closed. Review pending, partial or failed deliveries.'),
    (N'FrmCumplimientoViaje.Resumen', N'Completion: {0:N2}% | Total: {1} | Delivered: {2} | Partial: {3} | Failed: {4} | Pending: {5} | Receipts: {6}'),
    (N'FrmApp.menuTD05.Text', N'Check trip completion'),
    (N'FrmCumplimientoViaje.Title', N'Check trip completion'),
    (N'FrmCumplimientoViaje.grp0.Text', N'Trips'),
    (N'FrmCumplimientoViaje.btnActualizar.Text', N'Refresh'),
    (N'FrmCumplimientoViaje.dgvViajes.Numero.HeaderText', N'Trip'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaPrevista.HeaderText', N'Planned date'),
    (N'FrmCumplimientoViaje.dgvViajes.Estado.HeaderText', N'Status'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaInicio.HeaderText', N'Start'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaFinalizacion.HeaderText', N'Closure'),
    (N'FrmCumplimientoViaje.grp1.Text', N'Results and receipts'),
    (N'FrmCumplimientoViaje.dgvEntregas.Destino.HeaderText', N'Destination'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaPrevista.HeaderText', N'Planned date'),
    (N'FrmCumplimientoViaje.dgvEntregas.Estado.HeaderText', N'Status'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaRealizada.HeaderText', N'Actual date'),
    (N'FrmCumplimientoViaje.dgvEntregas.Observaciones.HeaderText', N'Notes'),
    (N'FrmCumplimientoViaje.dgvEntregas.NumeroComprobante.HeaderText', N'Receipt'),
    (N'FrmCumplimientoViaje.grp2.Text', N'Completion'),
    (N'FrmCumplimientoViaje.btnCerrar.Text', N'Close trip');
-- Fin traducciones TD


INSERT INTO dbo.TRADUCCION (
    Id_Idioma,
    Clave_Traduccion,
    Valor_Traduccion
)
SELECT
    @IdIdioma_en_US,
    origen.Clave_Traduccion,
    origen.Valor_Traduccion
FROM @Traducciones_en_US AS origen
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.TRADUCCION AS destino
    WHERE destino.Id_Idioma = @IdIdioma_en_US
      AND destino.Clave_Traduccion = origen.Clave_Traduccion
);
