/*
Seed de traducciones base: Português.

Este script inserta solamente las traducciones que no existen.
No actualiza traducciones existentes para no pisar cambios hechos desde la aplicación por un administrador.
*/

DECLARE @IdIdioma_pt_BR INT;

SELECT @IdIdioma_pt_BR = Id_Idioma
FROM dbo.IDIOMA
WHERE Codigo_Idioma = N'pt-BR';

IF @IdIdioma_pt_BR IS NULL
BEGIN
    RAISERROR('No existe el idioma pt-BR. Revisar el script 001_idiomas.sql.', 16, 1);
    RETURN;
END;

DECLARE @Traducciones_pt_BR TABLE (
    Clave_Traduccion NVARCHAR(200) NOT NULL PRIMARY KEY,
    Valor_Traduccion NVARCHAR(1000) NULL
);

INSERT INTO @Traducciones_pt_BR (
    Clave_Traduccion,
    Valor_Traduccion
)
VALUES
    (N'Common.btnAceptar.Text', N'Aceitar'),
    (N'Common.btnBorrar.Text', N'Excluir'),
    (N'Common.btnBuscar.Text', N'Pesquisar'),
    (N'Common.btnCancelar.Text', N'Cancelar'),
    (N'Common.btnEditar.Text', N'Editar'),
    (N'Common.btnGuardar.Text', N'Salvar'),
    (N'Common.btnNuevo.Text', N'Novo'),
    (N'Common.btnSalir.Text', N'Sair'),
    (N'Common.msgConfirmar', N'Confirmar'),
    (N'Common.msgError', N'Erro'),
    (N'FrmABMRoles.Title', N'Administração de funções'),
    (N'FrmABMRoles.btnAsignar.Text', N'Atribuir'),
    (N'FrmABMRoles.btnInsertar.Text', N'Inserir'),
    (N'FrmABMRoles.btnQuitar.Text', N'Remover'),
    (N'FrmABMRoles.btnborrar.Text', N'Excluir'),
    (N'FrmABMRoles.btnlistar.Text', N'Listar'),
    (N'FrmABMRoles.btnmodificar.Text', N'Modificar'),
    (N'FrmABMRoles.groupBox1.Text', N'Funções'),
    (N'FrmABMRoles.groupBox2.Text', N'Permissões'),
    (N'FrmABMRoles.lblPermiso.Text', N'Permissão'),
    (N'FrmABMRoles.lblIdRol.Text', N'Id função'),
    (N'FrmABMRoles.lblNombreRol.Text', N'Nome'),
    (N'FrmABMUsuarios.Title', N'Administração de usuários'),
    (N'FrmABMUsuarios.btnInsertar.Text', N'Inserir'),
    (N'FrmABMUsuarios.btnRestaurarVersAnt.Text', N'Restaurar versão'),
    (N'FrmABMUsuarios.btnborrar.Text', N'Excluir'),
    (N'FrmABMUsuarios.btnlistar.Text', N'Listar'),
    (N'FrmABMUsuarios.btnmodificar.Text', N'Modificar'),
    (N'FrmABMUsuarios.groupBox1.Text', N'Recuperar estados anteriores'),
    (N'FrmABMUsuarios.lblClave.Text', N'Senha'),
    (N'FrmABMUsuarios.lblD.Text', N'ID'),
    (N'FrmABMUsuarios.lblIdUsuarioSeleccionado.Text', N'Id selecionado'),
    (N'FrmABMUsuarios.lblNombre.Text', N'Nome'),
    (N'FrmABMUsuarios.lblPerfil.Text', N'Perfil'),
    (N'FrmABMUsuarios.lblUsuarioSeleccionado.Text', N'Usuário selecionado'),
    (N'FrmABMUsuarios.msgClaveNoCumple', N'A senha não atende aos requisitos. Deve ter pelo menos 6 caracteres, uma letra maiúscula e um número.'),
    (N'FrmApp.Title', N'Sistema de gestão administrativa'),
    (N'FrmApp.archivoToolStripMenuItem.Text', N'Arquivo'),
    (N'FrmApp.bitácoraToolStripMenuItem.Text', N'Registro de auditoria'),
    (N'FrmApp.cerrarSesiónToolStripMenuItem.Text', N'Encerrar sessão'),
    (N'FrmApp.clientesToolStripMenuItem.Text', N'Nova venda'),
    (N'FrmApp.gestiónToolStripMenuItem.Text', N'Gestão'),
    (N'FrmApp.historialToolStripMenuItem.Text', N'Histórico'),
    (N'FrmApp.idiomasToolStripMenuItem.Text', N'Idiomas'),
    (N'FrmApp.msgConfirmarCerrarSesion', N'Deseja realmente encerrar a sessão?'),
    (N'FrmApp.msgConfirmarSalir', N'Deseja realmente encerrar a sessão e sair?'),
    (N'FrmApp.msgErrorAbrirIdiomas', N'Não foi possível abrir o formulário de idiomas.'),
    (N'FrmApp.msgTituloConfirmarSalida', N'Confirmar saída'),
    (N'FrmApp.perfilesToolStripMenuItem.Text', N'Perfis'),
    (N'FrmApp.productosToolStripMenuItem.Text', N'Clientes'),
    (N'FrmApp.productosToolStripMenuItem1.Text', N'Produtos'),
    (N'FrmApp.salirToolStripMenuItem.Text', N'Sair'),
    (N'FrmApp.seguridadToolStripMenuItem.Text', N'Segurança'),
    (N'FrmApp.usuariosToolStripMenuItem.Text', N'Usuários'),
    (N'FrmBitacora.Title', N'Registro de auditoria'),
    (N'FrmBitacora.btnBuscar.Text', N'Pesquisar'),
    (N'FrmBitacora.gbFiltros.Text', N'Filtros'),
    (N'FrmBitacora.lblFechaDesde.Text', N'Data inicial'),
    (N'FrmBitacora.lblFechaHasta.Text', N'Data final'),
    (N'FrmBitacora.lblUsuario.Text', N'Usuário'),
    (N'FrmIdioma.Title', N'Gestão de idiomas'),
    (N'FrmIdioma.btnActivar.Text', N'Ativar'),
    (N'FrmIdioma.btnBorrar.Text', N'Excluir'),
    (N'FrmIdioma.btnCargarTraducciones.Text', N'Carregar traduções'),
    (N'FrmIdioma.btnDesactivar.Text', N'Desativar'),
    (N'FrmIdioma.btnEditar.Text', N'Editar'),
    (N'FrmIdioma.btnGuardarTraducciones.Text', N'Salvar traduções'),
    (N'FrmIdioma.btnNuevo.Text', N'Novo'),
    (N'FrmIdioma.btnSetDefault.Text', N'Padrão'),
    (N'FrmIdioma.gbIdiomas.Text', N'Idiomas disponíveis'),
    (N'FrmIdioma.gbTraducciones.Text', N'Traduções do idioma selecionado'),
    (N'FrmIdioma.dgvIdiomas.Codigo.HeaderText', N'Código'),
    (N'FrmIdioma.dgvIdiomas.Habilitado.HeaderText', N'Ativado'),
    (N'FrmIdioma.dgvIdiomas.EsDefault.HeaderText', N'Padrão'),
    (N'FrmIdioma.dgvIdiomas.Id_Idioma.HeaderText', N'Id'),
    (N'FrmIdioma.dgvIdiomas.Nombre.HeaderText', N'Nome'),
    (N'FrmIdioma.dgvTraducciones.Clave.HeaderText', N'Chave'),
    (N'FrmIdioma.dgvTraducciones.Id_Idioma.HeaderText', N'Idioma'),
    (N'FrmIdioma.dgvTraducciones.Id_Traduccion.HeaderText', N'Id'),
    (N'FrmIdioma.dgvTraducciones.Valor.HeaderText', N'Valor'),
    (N'FrmIdioma.msgAccesoDenegado', N'Acesso negado. Requer função de administrador.'),
    (N'FrmIdioma.msgBorrarIdioma', N'Excluir idioma?'),
    (N'FrmIdioma.msgConfirmar', N'Confirmar'),
    (N'FrmIdioma.msgTraduccionesGuardadas', N'Traduções salvas.'),
    (N'FrmIdiomaEditor.Title', N'Idioma'),
    (N'FrmIdiomaEditor.btnCancel.Text', N'Cancelar'),
    (N'FrmIdiomaEditor.btnOk.Text', N'OK'),
    (N'FrmIdiomaEditor.chkHabilitado.Text', N'Ativado'),
    (N'FrmIdiomaEditor.lblCodigo.Text', N'Código:'),
    (N'FrmIdiomaEditor.lblNombre.Text', N'Nome:'),
    (N'FrmLogin.Title', N'Login'),
    (N'FrmLogin.btnIngresar.Text', N'Entrar'),
    (N'FrmLogin.btnSalir.Text', N'Sair'),
    (N'FrmLogin.cmbIdiomasLogin.Text', N'Idioma'),
    (N'FrmLogin.lblClave.Text', N'Senha'),
    (N'FrmLogin.lblUsuario.Text', N'Usuário'),
    (N'FrmLogin.msgCamposRequeridos', N'Todos os campos são obrigatórios.'),
    (N'FrmLogin.msgCredencialesInvalidas', N'Usuário e/ou senha incorretos ou inexistentes.'),
    (N'FrmLogin.msgIngresoExitoso', N'Login realizado com sucesso.'),
    (N'FrmLogin.msgSistemaNoDisponible', N'O sistema não está disponível no momento. Tente novamente mais tarde.'),
    (N'frmRestore.Title', N'Restauração de integridade'),
    (N'frmRestore.btnCancelar.Text', N'Cancelar'),
    (N'frmRestore.btnRecalcular.Text', N'Recalcular'),
    (N'frmRestore.btnRestore.Text', N'Restaurar banco de dados'),
    (N'frmRestore.lblIntegridadDVV.Text', N'Integridade da tabela'),
    (N'frmRestore.lblRegistros.Text', N'Integridade dos registros'),
    (N'frmRestore.msgIntegridadDVVCorrecta', N'Integridade da tabela correta.'),
    (N'frmRestore.msgIntegridadDVVFallida', N'Falha na integridade da tabela.'),
    (N'frmRestore.msgIntegridadRegistrosCorrecta', N'Integridade dos registros correta.'),
    (N'frmRestore.msgIntegridadRegistrosFallida', N'Falha na integridade dos registros.'),
    (N'frmRestore.msgRestauracionError', N'Erro ao restaurar o banco de dados.'),
    (N'frmRestore.msgRestauracionExitosa', N'Restauração concluída com sucesso.');

-- TD: traducciones de transporte y distribución
INSERT INTO @Traducciones_pt_BR (Clave_Traduccion, Valor_Traduccion)
VALUES
    (N'TD.SinPermiso', N'Você não tem permissão para esta operação.'),
    (N'TD.DatosInvalidos', N'Preencha os campos obrigatórios e verifique o formato e o tamanho.'),
    (N'TD.Duplicado', N'O número, código ou produto já está cadastrado. Atualize os dados.'),
    (N'TD.EstadoInvalido', N'A operação não é permitida no estado atual. Atualize os dados.'),
    (N'TD.PlanIncompleto', N'Cada plano exige viagens; cada viagem exige entregas e carga prevista.'),
    (N'TD.CantidadInvalida', N'Informe quantidades positivas com até três casas decimais.'),
    (N'TD.FechaEntrega', N'Verifique destinos e datas: a entrega não pode anteceder a viagem.'),
    (N'TD.Error', N'Não foi possível concluir a operação. Verifique a conexão e atualize os dados.'),
    (N'TD.Seleccionar', N'Selecione um registro.'),
    (N'TD.Guardado', N'Operação registrada com sucesso.'),
    (N'TD.Confirmar', N'Confirma a operação?'),
    (N'TD.Formato', N'O valor informado tem formato inválido.'),
    (N'FrmApp.menuTD.Text', N'Transporte e distribuição'),
    (N'FrmPlanificacionDistribucion.Title', N'Planejar distribuição'),
    (N'FrmPlanificacionDistribucion.grp0.Text', N'Requisição e plano'),
    (N'FrmPlanificacionDistribucion.lblRequerimiento.Text', N'Pendente'),
    (N'FrmPlanificacionDistribucion.lblPlan.Text', N'N.º plano'),
    (N'FrmPlanificacionDistribucion.btnActualizar.Text', N'Atualizar'),
    (N'FrmPlanificacionDistribucion.lblNuevoReq.Text', N'Nova requisição: número / origem'),
    (N'FrmPlanificacionDistribucion.btnRecibir.Text', N'Receber requisição'),
    (N'FrmPlanificacionDistribucion.grp1.Text', N'Viagens do plano'),
    (N'FrmPlanificacionDistribucion.lblViaje.Text', N'N.º viagem'),
    (N'FrmPlanificacionDistribucion.lblFechaViaje.Text', N'Saída prevista'),
    (N'FrmPlanificacionDistribucion.btnViaje.Text', N'Adicionar viagem'),
    (N'FrmPlanificacionDistribucion.btnQuitarViaje.Text', N'Remover viagem'),
    (N'FrmPlanificacionDistribucion.dgvViajes.Numero.HeaderText', N'Número'),
    (N'FrmPlanificacionDistribucion.dgvViajes.FechaPrevista.HeaderText', N'Saída prevista'),
    (N'FrmPlanificacionDistribucion.grp2.Text', N'Entregas da viagem selecionada'),
    (N'FrmPlanificacionDistribucion.lblDestino.Text', N'Destino'),
    (N'FrmPlanificacionDistribucion.btnEntrega.Text', N'Adicionar entrega'),
    (N'FrmPlanificacionDistribucion.btnQuitarEntrega.Text', N'Remover entrega'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmPlanificacionDistribucion.grp3.Text', N'Carga prevista da viagem selecionada'),
    (N'FrmPlanificacionDistribucion.lblCantidad.Text', N'Quantidade prevista'),
    (N'FrmPlanificacionDistribucion.btnCarga.Text', N'Adicionar carga'),
    (N'FrmPlanificacionDistribucion.btnQuitarCarga.Text', N'Remover carga'),
    (N'FrmPlanificacionDistribucion.dgvCarga.IdMercaderia.HeaderText', N'Mercadoria'),
    (N'FrmPlanificacionDistribucion.dgvCarga.CantidadPrevista.HeaderText', N'Quantidade prevista'),
    (N'FrmPlanificacionDistribucion.grp4.Text', N'Cadastrar produto no catálogo'),
    (N'FrmPlanificacionDistribucion.lblCodigo.Text', N'Código'),
    (N'FrmPlanificacionDistribucion.lblDescripcion.Text', N'Descrição'),
    (N'FrmPlanificacionDistribucion.btnProducto.Text', N'Criar produto'),
    (N'FrmPlanificacionDistribucion.btnConfirmar.Text', N'Confirmar plano'),
    (N'FrmApp.menuTD01.Text', N'Planejar distribuição'),
    (N'TD.CantidadPreparadaInvalida', N'A quantidade preparada deve ser zero ou positiva, com até três casas decimais.'),
    (N'TD.ExpliqueDiferencia', N'Registre o motivo das diferenças nas observações.'),
    (N'TD.DespachoPendiente', N'Diferenças registradas. O despacho fica pendente e a viagem não pode iniciar.'),
    (N'TD.Estado.Pendiente', N'Pendente'),
    (N'TD.Estado.Confirmado', N'Confirmado'),
    (N'TD.Estado.Planificado', N'Planejado'),
    (N'TD.Estado.Preparado', N'Preparado'),
    (N'TD.Estado.EnCurso', N'Em andamento'),
    (N'TD.Estado.Cerrado', N'Encerrado'),
    (N'TD.Estado.Entregada', N'Entregue'),
    (N'TD.Estado.Parcial', N'Parcial'),
    (N'TD.Estado.Incumplida', N'Não cumprida'),
    (N'FrmApp.menuTD02.Text', N'Preparar despacho'),
    (N'FrmPrepararDespacho.Title', N'Preparar despacho'),
    (N'FrmPrepararDespacho.grp0.Text', N'Viagens e estado de preparação'),
    (N'FrmPrepararDespacho.btnActualizar.Text', N'Atualizar'),
    (N'FrmPrepararDespacho.dgvViajes.Numero.HeaderText', N'Viagem'),
    (N'FrmPrepararDespacho.dgvViajes.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmPrepararDespacho.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmPrepararDespacho.grp1.Text', N'Comparação de quantidades'),
    (N'FrmPrepararDespacho.dgvCarga.Codigo.HeaderText', N'Código'),
    (N'FrmPrepararDespacho.dgvCarga.Descripcion.HeaderText', N'Mercadoria'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPrevista.HeaderText', N'Prevista'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPreparada.HeaderText', N'Preparada'),
    (N'FrmPrepararDespacho.dgvCarga.Diferencia.HeaderText', N'Diferença'),
    (N'FrmPrepararDespacho.grp2.Text', N'Documento de despacho'),
    (N'FrmPrepararDespacho.lblNumero.Text', N'N.º despacho'),
    (N'FrmPrepararDespacho.lblObservaciones.Text', N'Observações / diferenças'),
    (N'FrmPrepararDespacho.btnGuardar.Text', N'Salvar preparação'),
    (N'TD.InicioNoHabilitado', N'A viagem exige despacho confirmado e carga sem diferenças.'),
    (N'TD.SinDespacho', N'Sem despacho'),
    (N'FrmApp.menuTD03.Text', N'Iniciar viagem'),
    (N'FrmEjecucionViaje.Title', N'Iniciar viagem'),
    (N'FrmEjecucionViaje.grp0.Text', N'Viagens'),
    (N'FrmEjecucionViaje.btnActualizar.Text', N'Atualizar'),
    (N'FrmEjecucionViaje.dgvViajes.Numero.HeaderText', N'Viagem'),
    (N'FrmEjecucionViaje.dgvViajes.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmEjecucionViaje.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmEjecucionViaje.dgvViajes.FechaInicio.HeaderText', N'Início'),
    (N'FrmEjecucionViaje.grp1.Text', N'Documento e carga de despacho'),
    (N'FrmEjecucionViaje.dgvCarga.Codigo.HeaderText', N'Código'),
    (N'FrmEjecucionViaje.dgvCarga.Descripcion.HeaderText', N'Mercadoria'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPrevista.HeaderText', N'Prevista'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPreparada.HeaderText', N'Preparada'),
    (N'FrmEjecucionViaje.grp2.Text', N'Entregas previstas'),
    (N'FrmEjecucionViaje.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmEjecucionViaje.dgvEntregas.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmEjecucionViaje.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmEjecucionViaje.grp3.Text', N'Início da viagem'),
    (N'FrmEjecucionViaje.btnIniciar.Text', N'Confirmar início'),
    (N'TD.FechaResultado', N'A data deve estar entre o início da viagem e o momento atual.'),
    (N'TD.ExpliqueResultado', N'Informe o motivo da entrega parcial ou não cumprida.'),
    (N'FrmApp.menuTD04.Text', N'Registrar entrega'),
    (N'FrmRegistroEntrega.Title', N'Registrar entrega'),
    (N'FrmRegistroEntrega.grp0.Text', N'Viagens em andamento'),
    (N'FrmRegistroEntrega.btnActualizar.Text', N'Atualizar'),
    (N'FrmRegistroEntrega.dgvViajes.Numero.HeaderText', N'Viagem'),
    (N'FrmRegistroEntrega.dgvViajes.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmRegistroEntrega.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmRegistroEntrega.grp1.Text', N'Entregas e comprovantes'),
    (N'FrmRegistroEntrega.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmRegistroEntrega.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaRealizada.HeaderText', N'Data efetiva'),
    (N'FrmRegistroEntrega.dgvEntregas.Observaciones.HeaderText', N'Observações'),
    (N'FrmRegistroEntrega.dgvEntregas.NumeroComprobante.HeaderText', N'Comprovante'),
    (N'FrmRegistroEntrega.grp2.Text', N'Resultado da entrega selecionada'),
    (N'FrmRegistroEntrega.lblResultado.Text', N'Resultado'),
    (N'FrmRegistroEntrega.lblFecha.Text', N'Data e hora'),
    (N'FrmRegistroEntrega.lblObservaciones.Text', N'Observações'),
    (N'FrmRegistroEntrega.btnRegistrar.Text', N'Registrar resultado'),
    (N'TD.CierreNoHabilitado', N'Somente viagens em andamento com todas as entregas completas e comprovadas podem ser encerradas. Revise entregas pendentes, parciais ou não cumpridas.'),
    (N'FrmCumplimientoViaje.Resumen', N'Cumprimento: {0:N2}% | Total: {1} | Entregues: {2} | Parciais: {3} | Não cumpridas: {4} | Pendentes: {5} | Comprovantes: {6}'),
    (N'FrmApp.menuTD05.Text', N'Controlar cumprimento da viagem'),
    (N'FrmCumplimientoViaje.Title', N'Controlar cumprimento da viagem'),
    (N'FrmCumplimientoViaje.grp0.Text', N'Viagens'),
    (N'FrmCumplimientoViaje.btnActualizar.Text', N'Atualizar'),
    (N'FrmCumplimientoViaje.dgvViajes.Numero.HeaderText', N'Viagem'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmCumplimientoViaje.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaInicio.HeaderText', N'Início'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaFinalizacion.HeaderText', N'Encerramento'),
    (N'FrmCumplimientoViaje.grp1.Text', N'Resultados e comprovantes'),
    (N'FrmCumplimientoViaje.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmCumplimientoViaje.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaRealizada.HeaderText', N'Data efetiva'),
    (N'FrmCumplimientoViaje.dgvEntregas.Observaciones.HeaderText', N'Observações'),
    (N'FrmCumplimientoViaje.dgvEntregas.NumeroComprobante.HeaderText', N'Comprovante'),
    (N'FrmCumplimientoViaje.grp2.Text', N'Cumprimento'),
    (N'FrmCumplimientoViaje.btnCerrar.Text', N'Encerrar viagem');
-- Fin traducciones TD


INSERT INTO dbo.TRADUCCION (
    Id_Idioma,
    Clave_Traduccion,
    Valor_Traduccion
)
SELECT
    @IdIdioma_pt_BR,
    origen.Clave_Traduccion,
    origen.Valor_Traduccion
FROM @Traducciones_pt_BR AS origen
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.TRADUCCION AS destino
    WHERE destino.Id_Idioma = @IdIdioma_pt_BR
      AND destino.Clave_Traduccion = origen.Clave_Traduccion
);
