/*
Seed de traducciones base: Português.

Este script inserta solamente las traducciones que no existen.
No actualiza traducciones existentes para no pisar cambios hechos desde la aplicación por un administrador.
*/

DECLARE @IdIdioma_pt_BR INT;

SELECT @IdIdioma_pt_BR = Id_Idioma
FROM dbo.IDIOMA
WHERE Codigo_Idioma = N'pt-BR';

IF @IdIdioma_pt_BR IS NULL
BEGIN
    RAISERROR('No existe el idioma pt-BR. Revisar el script 001_idiomas.sql.', 16, 1);
    RETURN;
END;

DECLARE @Traducciones_pt_BR TABLE (
    Clave_Traduccion NVARCHAR(200) NOT NULL PRIMARY KEY,
    Valor_Traduccion NVARCHAR(1000) NULL
);

INSERT INTO @Traducciones_pt_BR (
    Clave_Traduccion,
    Valor_Traduccion
)
VALUES
    (N'Common.btnAceptar.Text', N'Aceitar'),
    (N'Common.btnBorrar.Text', N'Excluir'),
    (N'Common.btnBuscar.Text', N'Pesquisar'),
    (N'Common.btnCancelar.Text', N'Cancelar'),
    (N'Common.btnEditar.Text', N'Editar'),
    (N'Common.btnGuardar.Text', N'Salvar'),
    (N'Common.btnNuevo.Text', N'Novo'),
    (N'Common.btnSalir.Text', N'Sair'),
    (N'Common.msgConfirmar', N'Confirmar'),
    (N'Common.msgError', N'Erro'),
    (N'FrmABMRoles.Title', N'Administração de funções'),
    (N'FrmABMRoles.btnAsignar.Text', N'Atribuir'),
    (N'FrmABMRoles.btnInsertar.Text', N'Inserir'),
    (N'FrmABMRoles.btnQuitar.Text', N'Remover'),
    (N'FrmABMRoles.btnborrar.Text', N'Excluir'),
    (N'FrmABMRoles.btnlistar.Text', N'Listar'),
    (N'FrmABMRoles.btnmodificar.Text', N'Modificar'),
    (N'FrmABMRoles.groupBox1.Text', N'Funções'),
    (N'FrmABMRoles.groupBox2.Text', N'Permissões'),
    (N'FrmABMRoles.lblPermiso.Text', N'Permissão'),
    (N'FrmABMRoles.lblIdRol.Text', N'Id função'),
    (N'FrmABMRoles.lblNombreRol.Text', N'Nome'),
    (N'FrmABMUsuarios.Title', N'Administração de usuários'),
    (N'FrmABMUsuarios.btnInsertar.Text', N'Inserir'),
    (N'FrmABMUsuarios.btnRestaurarVersAnt.Text', N'Restaurar versão'),
    (N'FrmABMUsuarios.btnborrar.Text', N'Excluir'),
    (N'FrmABMUsuarios.btnlistar.Text', N'Listar'),
    (N'FrmABMUsuarios.btnmodificar.Text', N'Modificar'),
    (N'FrmABMUsuarios.groupBox1.Text', N'Recuperar estados anteriores'),
    (N'FrmABMUsuarios.lblClave.Text', N'Senha'),
    (N'FrmABMUsuarios.lblD.Text', N'ID'),
    (N'FrmABMUsuarios.lblIdUsuarioSeleccionado.Text', N'Id selecionado'),
    (N'FrmABMUsuarios.lblNombre.Text', N'Nome'),
    (N'FrmABMUsuarios.lblPerfil.Text', N'Perfil'),
    (N'FrmABMUsuarios.lblUsuarioSeleccionado.Text', N'Usuário selecionado'),
    (N'FrmABMUsuarios.msgClaveNoCumple', N'A senha não atende aos requisitos. Deve ter pelo menos 6 caracteres, uma letra maiúscula e um número.'),
    (N'FrmApp.Title', N'Sistema de gestão administrativa'),
    (N'FrmApp.archivoToolStripMenuItem.Text', N'Arquivo'),
    (N'FrmApp.bitácoraToolStripMenuItem.Text', N'Registro de auditoria'),
    (N'FrmApp.cerrarSesiónToolStripMenuItem.Text', N'Encerrar sessão'),
    (N'FrmApp.clientesToolStripMenuItem.Text', N'Nova venda'),
    (N'FrmApp.gestiónToolStripMenuItem.Text', N'Gestão'),
    (N'FrmApp.historialToolStripMenuItem.Text', N'Histórico'),
    (N'FrmApp.idiomasToolStripMenuItem.Text', N'Idiomas'),
    (N'FrmApp.msgConfirmarCerrarSesion', N'Deseja realmente encerrar a sessão?'),
    (N'FrmApp.msgConfirmarSalir', N'Deseja realmente encerrar a sessão e sair?'),
    (N'FrmApp.msgErrorAbrirIdiomas', N'Não foi possível abrir o formulário de idiomas.'),
    (N'FrmApp.msgTituloConfirmarSalida', N'Confirmar saída'),
    (N'FrmApp.perfilesToolStripMenuItem.Text', N'Perfis'),
    (N'FrmApp.productosToolStripMenuItem.Text', N'Clientes'),
    (N'FrmApp.productosToolStripMenuItem1.Text', N'Produtos'),
    (N'FrmApp.salirToolStripMenuItem.Text', N'Sair'),
    (N'FrmApp.seguridadToolStripMenuItem.Text', N'Segurança'),
    (N'FrmApp.usuariosToolStripMenuItem.Text', N'Usuários'),
    (N'FrmBitacora.Title', N'Registro de auditoria'),
    (N'FrmBitacora.btnBuscar.Text', N'Pesquisar'),
    (N'FrmBitacora.gbFiltros.Text', N'Filtros'),
    (N'FrmBitacora.lblFechaDesde.Text', N'Data inicial'),
    (N'FrmBitacora.lblFechaHasta.Text', N'Data final'),
    (N'FrmBitacora.lblUsuario.Text', N'Usuário'),
    (N'FrmIdioma.Title', N'Gestão de idiomas'),
    (N'FrmIdioma.btnActivar.Text', N'Ativar'),
    (N'FrmIdioma.btnBorrar.Text', N'Excluir'),
    (N'FrmIdioma.btnCargarTraducciones.Text', N'Carregar traduções'),
    (N'FrmIdioma.btnDesactivar.Text', N'Desativar'),
    (N'FrmIdioma.btnEditar.Text', N'Editar'),
    (N'FrmIdioma.btnGuardarTraducciones.Text', N'Salvar traduções'),
    (N'FrmIdioma.btnNuevo.Text', N'Novo'),
    (N'FrmIdioma.btnSetDefault.Text', N'Padrão'),
    (N'FrmIdioma.gbIdiomas.Text', N'Idiomas disponíveis'),
    (N'FrmIdioma.gbTraducciones.Text', N'Traduções do idioma selecionado'),
    (N'FrmIdioma.dgvIdiomas.Codigo.HeaderText', N'Código'),
    (N'FrmIdioma.dgvIdiomas.Habilitado.HeaderText', N'Ativado'),
    (N'FrmIdioma.dgvIdiomas.EsDefault.HeaderText', N'Padrão'),
    (N'FrmIdioma.dgvIdiomas.Id_Idioma.HeaderText', N'Id'),
    (N'FrmIdioma.dgvIdiomas.Nombre.HeaderText', N'Nome'),
    (N'FrmIdioma.dgvTraducciones.Clave.HeaderText', N'Chave'),
    (N'FrmIdioma.dgvTraducciones.Id_Idioma.HeaderText', N'Idioma'),
    (N'FrmIdioma.dgvTraducciones.Id_Traduccion.HeaderText', N'Id'),
    (N'FrmIdioma.dgvTraducciones.Valor.HeaderText', N'Valor'),
    (N'FrmIdioma.msgAccesoDenegado', N'Acesso negado. Requer função de administrador.'),
    (N'FrmIdioma.msgBorrarIdioma', N'Excluir idioma?'),
    (N'FrmIdioma.msgConfirmar', N'Confirmar'),
    (N'FrmIdioma.msgTraduccionesGuardadas', N'Traduções salvas.'),
    (N'FrmIdiomaEditor.Title', N'Idioma'),
    (N'FrmIdiomaEditor.btnCancel.Text', N'Cancelar'),
    (N'FrmIdiomaEditor.btnOk.Text', N'OK'),
    (N'FrmIdiomaEditor.chkHabilitado.Text', N'Ativado'),
    (N'FrmIdiomaEditor.lblCodigo.Text', N'Código:'),
    (N'FrmIdiomaEditor.lblNombre.Text', N'Nome:'),
    (N'FrmLogin.Title', N'Login'),
    (N'FrmLogin.btnIngresar.Text', N'Entrar'),
    (N'FrmLogin.btnSalir.Text', N'Sair'),
    (N'FrmLogin.cmbIdiomasLogin.Text', N'Idioma'),
    (N'FrmLogin.lblClave.Text', N'Senha'),
    (N'FrmLogin.lblUsuario.Text', N'Usuário'),
    (N'FrmLogin.msgCamposRequeridos', N'Todos os campos são obrigatórios.'),
    (N'FrmLogin.msgCredencialesInvalidas', N'Usuário e/ou senha incorretos ou inexistentes.'),
    (N'FrmLogin.msgIngresoExitoso', N'Login realizado com sucesso.'),
    (N'FrmLogin.msgSistemaNoDisponible', N'O sistema não está disponível no momento. Tente novamente mais tarde.'),
    (N'frmRestore.Title', N'Restauração de integridade'),
    (N'frmRestore.btnCancelar.Text', N'Cancelar'),
    (N'frmRestore.btnRecalcular.Text', N'Recalcular'),
    (N'frmRestore.btnRestore.Text', N'Restaurar banco de dados'),
    (N'frmRestore.lblIntegridadDVV.Text', N'Integridade da tabela'),
    (N'frmRestore.lblRegistros.Text', N'Integridade dos registros'),
    (N'frmRestore.msgIntegridadDVVCorrecta', N'Integridade da tabela correta.'),
    (N'frmRestore.msgIntegridadDVVFallida', N'Falha na integridade da tabela.'),
    (N'frmRestore.msgIntegridadRegistrosCorrecta', N'Integridade dos registros correta.'),
    (N'frmRestore.msgIntegridadRegistrosFallida', N'Falha na integridade dos registros.'),
    (N'frmRestore.msgRestauracionError', N'Erro ao restaurar o banco de dados.'),
    (N'frmRestore.msgRestauracionExitosa', N'Restauração concluída com sucesso.');

-- TD: traducciones de transporte y distribución
INSERT INTO @Traducciones_pt_BR (Clave_Traduccion, Valor_Traduccion)
VALUES
    (N'TD.SinPermiso', N'Você não tem permissão para esta operação.'),
    (N'TD.DatosInvalidos', N'Preencha os campos obrigatórios e verifique o formato e o tamanho.'),
    (N'TD.Duplicado', N'O número, código ou produto já está cadastrado. Atualize os dados.'),
    (N'TD.EstadoInvalido', N'A operação não é permitida no estado atual. Atualize os dados.'),
    (N'TD.PlanIncompleto', N'Cada plano exige viagens; cada viagem exige entregas e carga prevista.'),
    (N'TD.CantidadInvalida', N'Informe quantidades positivas com até três casas decimais.'),
    (N'TD.FechaEntrega', N'Verifique destinos e datas: a entrega não pode anteceder a viagem.'),
    (N'TD.Error', N'Não foi possível concluir a operação. Verifique a conexão e atualize os dados.'),
    (N'TD.Seleccionar', N'Selecione um registro.'),
    (N'TD.Guardado', N'Operação registrada com sucesso.'),
    (N'TD.Confirmar', N'Confirma a operação?'),
    (N'TD.Formato', N'O valor informado tem formato inválido.'),
    (N'FrmApp.menuTD.Text', N'Transporte e distribuição'),
    (N'FrmPlanificacionDistribucion.Title', N'Planejar distribuição'),
    (N'FrmPlanificacionDistribucion.grp0.Text', N'Requisição e plano'),
    (N'FrmPlanificacionDistribucion.lblRequerimiento.Text', N'Pendente'),
    (N'FrmPlanificacionDistribucion.lblPlan.Text', N'N.º plano'),
    (N'FrmPlanificacionDistribucion.btnActualizar.Text', N'Atualizar'),
    (N'FrmPlanificacionDistribucion.lblNuevoReq.Text', N'Nova requisição: número / origem'),
    (N'FrmPlanificacionDistribucion.btnRecibir.Text', N'Receber requisição'),
    (N'FrmPlanificacionDistribucion.grp1.Text', N'Viagens do plano'),
    (N'FrmPlanificacionDistribucion.lblViaje.Text', N'N.º viagem'),
    (N'FrmPlanificacionDistribucion.lblFechaViaje.Text', N'Saída prevista'),
    (N'FrmPlanificacionDistribucion.btnViaje.Text', N'Adicionar viagem'),
    (N'FrmPlanificacionDistribucion.btnQuitarViaje.Text', N'Remover viagem'),
    (N'FrmPlanificacionDistribucion.dgvViajes.Numero.HeaderText', N'Número'),
    (N'FrmPlanificacionDistribucion.dgvViajes.FechaPrevista.HeaderText', N'Saída prevista'),
    (N'FrmPlanificacionDistribucion.grp2.Text', N'Entregas da viagem selecionada'),
    (N'FrmPlanificacionDistribucion.lblDestino.Text', N'Destino'),
    (N'FrmPlanificacionDistribucion.btnEntrega.Text', N'Adicionar entrega'),
    (N'FrmPlanificacionDistribucion.btnQuitarEntrega.Text', N'Remover entrega'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmPlanificacionDistribucion.dgvEntregas.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmPlanificacionDistribucion.grp3.Text', N'Carga prevista da viagem selecionada'),
    (N'FrmPlanificacionDistribucion.lblCantidad.Text', N'Quantidade prevista'),
    (N'FrmPlanificacionDistribucion.btnCarga.Text', N'Adicionar carga'),
    (N'FrmPlanificacionDistribucion.btnQuitarCarga.Text', N'Remover carga'),
    (N'FrmPlanificacionDistribucion.dgvCarga.IdMercaderia.HeaderText', N'Mercadoria'),
    (N'FrmPlanificacionDistribucion.dgvCarga.CantidadPrevista.HeaderText', N'Quantidade prevista'),
    (N'FrmPlanificacionDistribucion.grp4.Text', N'Cadastrar produto no catálogo'),
    (N'FrmPlanificacionDistribucion.lblCodigo.Text', N'Código'),
    (N'FrmPlanificacionDistribucion.lblDescripcion.Text', N'Descrição'),
    (N'FrmPlanificacionDistribucion.btnProducto.Text', N'Criar produto'),
    (N'FrmPlanificacionDistribucion.btnConfirmar.Text', N'Confirmar plano'),
    (N'FrmApp.menuTD01.Text', N'Planejar distribuição'),
    (N'TD.CantidadPreparadaInvalida', N'A quantidade preparada deve ser zero ou positiva, com até três casas decimais.'),
    (N'TD.ExpliqueDiferencia', N'Registre o motivo das diferenças nas observações.'),
    (N'TD.DespachoPendiente', N'Diferenças registradas. O despacho fica pendente e a viagem não pode iniciar.'),
    (N'TD.Estado.Pendiente', N'Pendente'),
    (N'TD.Estado.Confirmado', N'Confirmado'),
    (N'TD.Estado.Planificado', N'Planejado'),
    (N'TD.Estado.Preparado', N'Preparado'),
    (N'TD.Estado.EnCurso', N'Em andamento'),
    (N'TD.Estado.Cerrado', N'Encerrado'),
    (N'TD.Estado.Entregada', N'Entregue'),
    (N'TD.Estado.Parcial', N'Parcial'),
    (N'TD.Estado.Incumplida', N'Não cumprida'),
    (N'FrmApp.menuTD02.Text', N'Preparar despacho'),
    (N'FrmPrepararDespacho.Title', N'Preparar despacho'),
    (N'FrmPrepararDespacho.grp0.Text', N'Viagens e estado de preparação'),
    (N'FrmPrepararDespacho.btnActualizar.Text', N'Atualizar'),
    (N'FrmPrepararDespacho.dgvViajes.Numero.HeaderText', N'Viagem'),
    (N'FrmPrepararDespacho.dgvViajes.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmPrepararDespacho.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmPrepararDespacho.grp1.Text', N'Comparação de quantidades'),
    (N'FrmPrepararDespacho.dgvCarga.Codigo.HeaderText', N'Código'),
    (N'FrmPrepararDespacho.dgvCarga.Descripcion.HeaderText', N'Mercadoria'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPrevista.HeaderText', N'Prevista'),
    (N'FrmPrepararDespacho.dgvCarga.CantidadPreparada.HeaderText', N'Preparada'),
    (N'FrmPrepararDespacho.dgvCarga.Diferencia.HeaderText', N'Diferença'),
    (N'FrmPrepararDespacho.grp2.Text', N'Documento de despacho'),
    (N'FrmPrepararDespacho.lblNumero.Text', N'N.º despacho'),
    (N'FrmPrepararDespacho.lblObservaciones.Text', N'Observações / diferenças'),
    (N'FrmPrepararDespacho.btnGuardar.Text', N'Salvar preparação'),
    (N'TD.InicioNoHabilitado', N'A viagem exige despacho confirmado e carga sem diferenças.'),
    (N'TD.SinDespacho', N'Sem despacho'),
    (N'FrmApp.menuTD03.Text', N'Iniciar viagem'),
    (N'FrmEjecucionViaje.Title', N'Iniciar viagem'),
    (N'FrmEjecucionViaje.grp0.Text', N'Viagens'),
    (N'FrmEjecucionViaje.btnActualizar.Text', N'Atualizar'),
    (N'FrmEjecucionViaje.dgvViajes.Numero.HeaderText', N'Viagem'),
    (N'FrmEjecucionViaje.dgvViajes.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmEjecucionViaje.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmEjecucionViaje.dgvViajes.FechaInicio.HeaderText', N'Início'),
    (N'FrmEjecucionViaje.grp1.Text', N'Documento e carga de despacho'),
    (N'FrmEjecucionViaje.dgvCarga.Codigo.HeaderText', N'Código'),
    (N'FrmEjecucionViaje.dgvCarga.Descripcion.HeaderText', N'Mercadoria'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPrevista.HeaderText', N'Prevista'),
    (N'FrmEjecucionViaje.dgvCarga.CantidadPreparada.HeaderText', N'Preparada'),
    (N'FrmEjecucionViaje.grp2.Text', N'Entregas previstas'),
    (N'FrmEjecucionViaje.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmEjecucionViaje.dgvEntregas.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmEjecucionViaje.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmEjecucionViaje.grp3.Text', N'Início da viagem'),
    (N'FrmEjecucionViaje.btnIniciar.Text', N'Confirmar início'),
    (N'TD.FechaResultado', N'A data deve estar entre o início da viagem e o momento atual.'),
    (N'TD.ExpliqueResultado', N'Informe o motivo da entrega parcial ou não cumprida.'),
    (N'FrmApp.menuTD04.Text', N'Registrar entrega'),
    (N'FrmRegistroEntrega.Title', N'Registrar entrega'),
    (N'FrmRegistroEntrega.grp0.Text', N'Viagens em andamento'),
    (N'FrmRegistroEntrega.btnActualizar.Text', N'Atualizar'),
    (N'FrmRegistroEntrega.dgvViajes.Numero.HeaderText', N'Viagem'),
    (N'FrmRegistroEntrega.dgvViajes.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmRegistroEntrega.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmRegistroEntrega.grp1.Text', N'Entregas e comprovantes'),
    (N'FrmRegistroEntrega.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmRegistroEntrega.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmRegistroEntrega.dgvEntregas.FechaRealizada.HeaderText', N'Data efetiva'),
    (N'FrmRegistroEntrega.dgvEntregas.Observaciones.HeaderText', N'Observações'),
    (N'FrmRegistroEntrega.dgvEntregas.NumeroComprobante.HeaderText', N'Comprovante'),
    (N'FrmRegistroEntrega.grp2.Text', N'Resultado da entrega selecionada'),
    (N'FrmRegistroEntrega.lblResultado.Text', N'Resultado'),
    (N'FrmRegistroEntrega.lblFecha.Text', N'Data e hora'),
    (N'FrmRegistroEntrega.lblObservaciones.Text', N'Observações'),
    (N'FrmRegistroEntrega.btnRegistrar.Text', N'Registrar resultado'),
    (N'TD.CierreNoHabilitado', N'Somente viagens em andamento com todas as entregas completas e comprovadas podem ser encerradas. Revise entregas pendentes, parciais ou não cumpridas.'),
    (N'FrmCumplimientoViaje.Resumen', N'Cumprimento: {0:N2}% | Total: {1} | Entregues: {2} | Parciais: {3} | Não cumpridas: {4} | Pendentes: {5} | Comprovantes: {6}'),
    (N'FrmApp.menuTD05.Text', N'Controlar cumprimento da viagem'),
    (N'FrmCumplimientoViaje.Title', N'Controlar cumprimento da viagem'),
    (N'FrmCumplimientoViaje.grp0.Text', N'Viagens'),
    (N'FrmCumplimientoViaje.btnActualizar.Text', N'Atualizar'),
    (N'FrmCumplimientoViaje.dgvViajes.Numero.HeaderText', N'Viagem'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmCumplimientoViaje.dgvViajes.Estado.HeaderText', N'Estado'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaInicio.HeaderText', N'Início'),
    (N'FrmCumplimientoViaje.dgvViajes.FechaFinalizacion.HeaderText', N'Encerramento'),
    (N'FrmCumplimientoViaje.grp1.Text', N'Resultados e comprovantes'),
    (N'FrmCumplimientoViaje.dgvEntregas.Destino.HeaderText', N'Destino'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaPrevista.HeaderText', N'Data prevista'),
    (N'FrmCumplimientoViaje.dgvEntregas.Estado.HeaderText', N'Estado'),
    (N'FrmCumplimientoViaje.dgvEntregas.FechaRealizada.HeaderText', N'Data efetiva'),
    (N'FrmCumplimientoViaje.dgvEntregas.Observaciones.HeaderText', N'Observações'),
    (N'FrmCumplimientoViaje.dgvEntregas.NumeroComprobante.HeaderText', N'Comprovante'),
    (N'FrmCumplimientoViaje.grp2.Text', N'Cumprimento'),
    (N'FrmCumplimientoViaje.btnCerrar.Text', N'Encerrar viagem');
-- Fin traducciones TD


INSERT INTO dbo.TRADUCCION (
    Id_Idioma,
    Clave_Traduccion,
    Valor_Traduccion
)
SELECT
    @IdIdioma_pt_BR,
    origen.Clave_Traduccion,
    origen.Valor_Traduccion
FROM @Traducciones_pt_BR AS origen
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.TRADUCCION AS destino
    WHERE destino.Id_Idioma = @IdIdioma_pt_BR
      AND destino.Clave_Traduccion = origen.Clave_Traduccion
);

-- Configuración de conexión e inicialización de la base.
DECLARE @Conexion_pt_BR TABLE (Clave NVARCHAR(200), Valor NVARCHAR(1000));
INSERT @Conexion_pt_BR VALUES
(N'BD.SinConfigurar',N'Nenhuma conexão com banco de dados está configurada. Configure o servidor e o banco antes de entrar.'),
(N'BD.ConexionFallida',N'Não foi possível conectar ao SQL Server. Verifique servidor, porta, serviço, rede e certificado. Confie no certificado somente se confiar nesse servidor.'),
(N'BD.Autenticacion',N'O SQL Server rejeitou as credenciais. Verifique usuário, senha e modo de autenticação habilitado.'),
(N'BD.BaseInaccesible',N'O banco não existe ou sua conta não tem acesso. Conecte ao servidor e selecione um banco acessível.'),
(N'BD.PermisosSQL',N'A conta do SQL Server não possui permissões suficientes para esta operação.'),
(N'BD.BaseExiste',N'Já existe um banco com esse nome. Selecione e verifique esse banco.'),
(N'BD.Metadatos',N'É necessária a permissão VIEW DEFINITION no banco para verificar seus objetos.'),
(N'BD.BaseSistema',N'Não é permitido utilizar ou inicializar bancos de sistema.'),
(N'BD.NoVacia',N'O banco contém objetos. A inicialização não foi executada. Use Database para uma atualização controlada.'),
(N'BD.Incompatible',N'O banco não está pronto: faltam objetos ou dados iniciais. Se houver objetos, solicite uma atualização com Database; os dados existentes não serão sobrescritos.'),
(N'BD.ConfiguracionLocal',N'Não foi possível ler ou salvar a configuração local protegida. Verifique as permissões do perfil do Windows e configure a conexão novamente.'),
(N'BD.PaqueteAusente',N'O pacote DatabaseSetup está ausente. Repare ou reinstale o aplicativo.'),
(N'BD.DatosInvalidos',N'Informe servidor e banco. Para porta TCP, use apenas o host, sem instância nem vírgula. Informe o usuário para autenticação SQL Server.'),
(N'BD.ClaveInicial',N'Para criar o usuário admin de SistemaLogistica, informe uma nova senha de pelo menos 8 caracteres e repita exatamente. Não é a senha do SQL Server. Depois clique em Inicializar banco.'),
(N'BD.SinPermiso',N'Você não tem permissão para configurar o banco de dados.'),
(N'BD.Instrucciones',N'Conecte ao servidor, selecione um banco e clique em Verificar estrutura do banco. Salve somente após uma verificação bem-sucedida.'),
(N'BD.Busqueda',N'Busca concluída. A lista pode estar incompleta; digite o servidor manualmente se ele não aparecer.'),
(N'BD.Conectado',N'Conectado ao servidor. Selecione um banco ou digite um novo nome e clique em Criar banco vazio.'),
(N'BD.Trabajando',N'Operação em andamento. Aguarde.'),
(N'BD.Compatible',N'Conexão bem-sucedida. Os objetos e dados iniciais necessários estão presentes. Você pode salvar a conexão.'),
(N'BD.Vacia',N'O banco está vazio. Informe a senha inicial de admin e clique em Inicializar banco.'),
(N'BD.AdminCreado',N'Usuário inicial: admin. Entre com a senha escolhida neste formulário.'),
(N'BD.ConfirmarCrear',N'Criar um banco vazio com o nome informado no servidor selecionado?'),
(N'BD.ConfirmarInicializar',N'Criar tabelas, procedimentos e dados iniciais no banco vazio selecionado?'),
(N'BD.ConfirmarGuardar',N'Salvar esta conexão protegida para este usuário do Windows e continuar para o login?'),
(N'BD.ConfirmarReinicio',N'Salvar esta conexão e reiniciar o aplicativo? A sessão será encerrada e as alterações não salvas nas janelas abertas serão perdidas.'),
(N'BD.Error',N'Não foi possível concluir a operação de banco de dados. Verifique a configuração e os recursos de instalação.'),
(N'FrmConfiguracionBD.Title',N'Configurar banco de dados'),
(N'FrmConfiguracionBD.lblServidor.Text',N'Servidor ou servidor\instância'),
(N'FrmConfiguracionBD.lblPuerto.Text',N'Porta TCP (0 = padrão)'),
(N'FrmConfiguracionBD.lblAutenticacion.Text',N'Autenticação'),
(N'FrmConfiguracionBD.chkWindows.Text',N'Usar autenticação do Windows'),
(N'FrmConfiguracionBD.lblUsuario.Text',N'Usuário SQL Server'),
(N'FrmConfiguracionBD.lblClave.Text',N'Senha SQL Server'),
(N'FrmConfiguracionBD.lblCifrado.Text',N'Conexão criptografada'),
(N'FrmConfiguracionBD.chkCertificado.Text',N'Confiar no certificado do servidor'),
(N'FrmConfiguracionBD.lblBase.Text',N'Banco existente ou novo nome'),
(N'FrmConfiguracionBD.lblAdmin.Text',N'Nova senha (mínimo de 8 caracteres)'),
(N'FrmConfiguracionBD.lblRepetir.Text',N'Repetir nova senha'),
(N'FrmConfiguracionBD.lblAyuda.Text',N'A busca de instâncias é opcional. Você também pode digitar o servidor. Para SQL Server, desmarque a autenticação Windows. A senha de admin é usada apenas para inicializar um banco vazio (mínimo de 8 caracteres).'),
(N'FrmConfiguracionBD.btnBuscar.Text',N'Buscar instâncias'),
(N'FrmConfiguracionBD.btnConectar.Text',N'Conectar e listar bancos'),
(N'FrmConfiguracionBD.btnCrear.Text',N'Criar banco vazio'),
(N'FrmConfiguracionBD.btnVerificar.Text',N'Verificar estrutura do banco'),
(N'FrmConfiguracionBD.btnInicializar.Text',N'Inicializar banco'),
(N'FrmConfiguracionBD.btnGuardar.Text',N'Salvar conexão'),
(N'FrmConfiguracionBD.btnCancelar.Text',N'Cancelar'),
(N'FrmApp.menuConfiguracionBD.Text',N'Configurar banco de dados');
INSERT @Conexion_pt_BR VALUES
(N'FrmConfiguracionBD.grpAdmin.Text',N'Administrador inicial do SistemaLogistica'),
(N'FrmConfiguracionBD.lblNotaAdmin.Text',N'Somente para um banco vazio: crie a senha do usuário admin do aplicativo. Não é uma credencial do SQL Server.');
INSERT dbo.TRADUCCION(Id_Idioma,Clave_Traduccion,Valor_Traduccion)
SELECT @IdIdioma_pt_BR,Clave,Valor FROM @Conexion_pt_BR C
WHERE NOT EXISTS (SELECT 1 FROM dbo.TRADUCCION T WHERE T.Id_Idioma=@IdIdioma_pt_BR AND T.Clave_Traduccion=C.Clave);

-- Mensajes de carga opcional de datos de prueba.
DECLARE @Demo TABLE(Clave NVARCHAR(200), Valor NVARCHAR(1000));
INSERT @Demo VALUES
(N'FrmConfiguracionBD.btnDatosPrueba.Text',N'Inicializar dados de teste'),
(N'BD.ConfirmarDemo',N'Adicionar usuários e operações fictícias TD ao banco selecionado? Use um banco de testes. Dados existentes não serão redefinidos. Uma senha será gerada para os quatro usuários demo.'),
(N'BD.DemoCargado',N'Dados de teste carregados. Usuários: demo_planificador, demo_expedicion, demo_transporte e demo_consulta. Senha comum: {0}. Anote antes de fechar; ela não será exibida novamente. A senha de admin permanece inalterada.'),
(N'BD.DemoExistente',N'Os dados de teste já foram carregados. Nenhum registro foi duplicado e senhas e avanços não foram redefinidos.'),
(N'BD.DemoColision',N'Já existem registros com nomes reservados para DEMO. O banco não foi alterado. Use outro banco de testes.'),
(N'BD.DemoIntegridad',N'A integridade dos usuários é inválida. Nenhum dado foi carregado e os verificadores não foram recalculados.'),
(N'BD.DemoError',N'Não foi possível carregar os dados de teste. A operação foi revertida.');
INSERT dbo.TRADUCCION(Id_Idioma,Clave_Traduccion,Valor_Traduccion)
SELECT @IdIdioma_pt_BR,Clave,Valor FROM @Demo D WHERE NOT EXISTS (SELECT 1 FROM dbo.TRADUCCION T WHERE T.Id_Idioma=@IdIdioma_pt_BR AND T.Clave_Traduccion=D.Clave);

-- Mantenimiento y disponibilidad de flota.
DECLARE @MF TABLE(Clave NVARCHAR(200),Valor NVARCHAR(1000));
INSERT @MF VALUES
(N'MF.SinPermiso',N'Você não tem permissão para esta operação.'),
(N'MF.Seleccionar',N'Selecione um registro.'),
(N'MF.DatosInvalidos',N'Preencha os campos obrigatórios e verifique datas, quantidades e resultado.'),
(N'MF.Kilometraje',N'A unidade deve estar ativa e a quilometragem não pode diminuir.'),
(N'MF.EnViaje',N'A unidade está em viagem. Sua condição não pode ser alterada.'),
(N'MF.Pendientes',N'A unidade não está habilitada ou possui registros, ordens ou tarefas pendentes.'),
(N'MF.EstadoInvalido',N'A operação não corresponde ao estado atual. Atualize e verifique a seleção e a data programada.'),
(N'MF.Asignada',N'A unidade já está atribuída a outra viagem não encerrada.'),
(N'MF.Duplicado',N'O registro já existe. Atualize a lista antes de continuar.'),
(N'MF.Concurrencia',N'Outra operação está utilizando a frota. Tente novamente.'),
(N'MF.Confirmar',N'Confirma a operação?'),
(N'MF.Guardado',N'Operação registrada com sucesso.'),
(N'MF.Error',N'Não foi possível concluir a operação. Atualize e tente novamente.'),
(N'MF.Titulo',N'Manutenção e frota'),
(N'FrmApp.menuMF.Text',N'Manutenção e frota'),
(N'MF.Valor.FueraServicio',N'Fora de serviço'),
(N'MF.Valor.EnMantenimiento',N'Em manutenção'),
(N'MF.Valor.PendienteVerificacion',N'Aguardando verificação'),
(N'MF.Valor.Disponible',N'Disponível'),
(N'MF.Valor.Pendiente',N'Pendente'),
(N'MF.Valor.Programado',N'Programado'),
(N'MF.Valor.Resuelto',N'Resolvido'),
(N'MF.Valor.Programada',N'Programada'),
(N'MF.Valor.EnCurso',N'Em andamento'),
(N'MF.Valor.Cerrada',N'Encerrada'),
(N'MF.Valor.Satisfactoria',N'Satisfatória'),
(N'MF.Valor.RequiereTareas',N'Requer mais tarefas'),
(N'MF.Valor.Preventivo',N'Preventivo'),
(N'MF.Valor.Correctivo',N'Corretivo'),
(N'MF.Valor.Baja',N'Baixa'),
(N'MF.Valor.Media',N'Média'),
(N'MF.Valor.Alta',N'Alta'),
(N'MF.Valor.Urgente',N'Urgente'),
(N'MF.Valor.Planificado',N'Planejado'),
(N'MF.Valor.Preparado',N'Preparado'),
(N'FrmApp.menuMF01.Text',N'Registrar estado da frota'),
(N'FrmApp.menuMF02.Text',N'Programar manutenção'),
(N'FrmApp.menuMF03.Text',N'Registrar intervenção de manutenção'),
(N'FrmApp.menuMF04.Text',N'Habilitar unidade para operar'),
(N'FrmApp.menuMF05.Text',N'Consultar disponibilidade e atribuir unidade'),
(N'FrmEstadoFlota.Title',N'Registrar estado da frota'),
(N'FrmEstadoFlota.grpdgvUnidades.Text',N'Unidades'),
(N'FrmEstadoFlota.dgvUnidades.IdUnidadFlota.HeaderText',N'Unidade'),
(N'FrmEstadoFlota.dgvUnidades.Dominio.HeaderText',N'Placa'),
(N'FrmEstadoFlota.dgvUnidades.Tipo.HeaderText',N'Tipo'),
(N'FrmEstadoFlota.dgvUnidades.Marca.HeaderText',N'Marca'),
(N'FrmEstadoFlota.dgvUnidades.Modelo.HeaderText',N'Modelo'),
(N'FrmEstadoFlota.dgvUnidades.Anio.HeaderText',N'Ano'),
(N'FrmEstadoFlota.dgvUnidades.Capacidad.HeaderText',N'Capacidade'),
(N'FrmEstadoFlota.dgvUnidades.KilometrajeActual.HeaderText',N'Quilometragem atual'),
(N'FrmEstadoFlota.dgvUnidades.EstadoOperativo.HeaderText',N'Estado operacional'),
(N'FrmEstadoFlota.grpdgvPartes.Text',N'Registros da unidade'),
(N'FrmEstadoFlota.dgvPartes.IdParteEstadoUnidad.HeaderText',N'Registro'),
(N'FrmEstadoFlota.dgvPartes.FechaHora.HeaderText',N'Data e hora'),
(N'FrmEstadoFlota.dgvPartes.Kilometraje.HeaderText',N'Quilometragem'),
(N'FrmEstadoFlota.dgvPartes.TipoNovedad.HeaderText',N'Ocorrência'),
(N'FrmEstadoFlota.dgvPartes.Descripcion.HeaderText',N'Descrição'),
(N'FrmEstadoFlota.dgvPartes.RequiereMantenimiento.HeaderText',N'Requer manutenção'),
(N'FrmEstadoFlota.dgvPartes.EstadoParte.HeaderText',N'Estado do registro'),
(N'FrmEstadoFlota.lbltxtDominio.Text',N'Placa'),
(N'FrmEstadoFlota.lbltxtTipo.Text',N'Tipo'),
(N'FrmEstadoFlota.lbltxtMarca.Text',N'Marca'),
(N'FrmEstadoFlota.lbltxtModelo.Text',N'Modelo'),
(N'FrmEstadoFlota.lblnudAnio.Text',N'Ano'),
(N'FrmEstadoFlota.lblnudCapacidad.Text',N'Capacidade'),
(N'FrmEstadoFlota.lblnudKmInicial.Text',N'Quilometragem inicial'),
(N'FrmEstadoFlota.btnCrear.Text',N'Criar unidade'),
(N'FrmEstadoFlota.grpalta.Text',N'Nova unidade'),
(N'FrmEstadoFlota.lblnudKm.Text',N'Quilometragem'),
(N'FrmEstadoFlota.lbltxtNovedad.Text',N'Ocorrência'),
(N'FrmEstadoFlota.lbltxtDescripcion.Text',N'Descrição'),
(N'FrmEstadoFlota.lblchkMantenimiento.Text',N'Requer manutenção'),
(N'FrmEstadoFlota.btnRegistrar.Text',N'Registrar estado'),
(N'FrmEstadoFlota.btnActualizar.Text',N'Atualizar'),
(N'FrmEstadoFlota.grpestado.Text',N'Estado da unidade selecionada'),
(N'FrmProgramarMantenimiento.Title',N'Programar manutenção'),
(N'FrmProgramarMantenimiento.grpdgvPartes.Text',N'Registros pendentes'),
(N'FrmProgramarMantenimiento.dgvPartes.IdParteEstadoUnidad.HeaderText',N'Registro'),
(N'FrmProgramarMantenimiento.dgvPartes.Dominio.HeaderText',N'Placa'),
(N'FrmProgramarMantenimiento.dgvPartes.FechaHora.HeaderText',N'Data e hora'),
(N'FrmProgramarMantenimiento.dgvPartes.Kilometraje.HeaderText',N'Quilometragem'),
(N'FrmProgramarMantenimiento.dgvPartes.TipoNovedad.HeaderText',N'Ocorrência'),
(N'FrmProgramarMantenimiento.dgvPartes.Descripcion.HeaderText',N'Descrição'),
(N'FrmProgramarMantenimiento.grpdgvOrdenes.Text',N'Ordens de manutenção'),
(N'FrmProgramarMantenimiento.dgvOrdenes.IdOrdenMantenimiento.HeaderText',N'Ordem'),
(N'FrmProgramarMantenimiento.dgvOrdenes.Dominio.HeaderText',N'Placa'),
(N'FrmProgramarMantenimiento.dgvOrdenes.FechaProgramada.HeaderText',N'Data programada'),
(N'FrmProgramarMantenimiento.dgvOrdenes.TipoMantenimiento.HeaderText',N'Tipo de manutenção'),
(N'FrmProgramarMantenimiento.dgvOrdenes.Prioridad.HeaderText',N'Prioridade'),
(N'FrmProgramarMantenimiento.dgvOrdenes.DescripcionTrabajo.HeaderText',N'Trabalho previsto'),
(N'FrmProgramarMantenimiento.dgvOrdenes.EstadoOrden.HeaderText',N'Estado da ordem'),
(N'FrmProgramarMantenimiento.lbldtpProgramada.Text',N'Data programada'),
(N'FrmProgramarMantenimiento.lblcmbTipo.Text',N'Tipo'),
(N'FrmProgramarMantenimiento.lblcmbPrioridad.Text',N'Prioridade'),
(N'FrmProgramarMantenimiento.lbltxtTrabajo.Text',N'Trabalho previsto'),
(N'FrmProgramarMantenimiento.btnProgramar.Text',N'Programar'),
(N'FrmProgramarMantenimiento.btnActualizar.Text',N'Atualizar'),
(N'FrmProgramarMantenimiento.grpprograma.Text',N'Programação do registro selecionado'),
(N'FrmIntervencionMantenimiento.Title',N'Registrar intervenção de manutenção'),
(N'FrmIntervencionMantenimiento.grpdgvOrdenes.Text',N'Ordens de manutenção'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.IdOrdenMantenimiento.HeaderText',N'Ordem'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.Dominio.HeaderText',N'Placa'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.FechaProgramada.HeaderText',N'Data programada'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.TipoMantenimiento.HeaderText',N'Tipo de manutenção'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.Prioridad.HeaderText',N'Prioridade'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.DescripcionTrabajo.HeaderText',N'Trabalho previsto'),
(N'FrmIntervencionMantenimiento.dgvOrdenes.EstadoOrden.HeaderText',N'Estado da ordem'),
(N'FrmIntervencionMantenimiento.grpdgvIntervenciones.Text',N'Intervenções da ordem'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.IdIntervencionMantenimiento.HeaderText',N'Intervenção'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.FechaInicio.HeaderText',N'Início'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.FechaFin.HeaderText',N'Término'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.Kilometraje.HeaderText',N'Quilometragem'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.TrabajoRealizado.HeaderText',N'Trabalho realizado'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.Resultado.HeaderText',N'Resultado'),
(N'FrmIntervencionMantenimiento.dgvIntervenciones.Observaciones.HeaderText',N'Observações'),
(N'FrmIntervencionMantenimiento.lblnudKm.Text',N'Quilometragem'),
(N'FrmIntervencionMantenimiento.lbltxtTrabajo.Text',N'Trabalho realizado'),
(N'FrmIntervencionMantenimiento.lblcmbResultado.Text',N'Resultado'),
(N'FrmIntervencionMantenimiento.lbltxtObservaciones.Text',N'Observações'),
(N'FrmIntervencionMantenimiento.btnIniciar.Text',N'Iniciar intervenção'),
(N'FrmIntervencionMantenimiento.btnFinalizar.Text',N'Finalizar intervenção'),
(N'FrmIntervencionMantenimiento.btnActualizar.Text',N'Atualizar'),
(N'FrmIntervencionMantenimiento.grpintervencion.Text',N'Tarefas e resultado'),
(N'FrmHabilitarUnidad.Title',N'Habilitar unidade para operar'),
(N'FrmHabilitarUnidad.grpdgvUnidades.Text',N'Unidades'),
(N'FrmHabilitarUnidad.dgvUnidades.IdUnidadFlota.HeaderText',N'Unidade'),
(N'FrmHabilitarUnidad.dgvUnidades.Dominio.HeaderText',N'Placa'),
(N'FrmHabilitarUnidad.dgvUnidades.KilometrajeActual.HeaderText',N'Quilometragem atual'),
(N'FrmHabilitarUnidad.dgvUnidades.EstadoOperativo.HeaderText',N'Estado operacional'),
(N'FrmHabilitarUnidad.grpdgvIntervenciones.Text',N'Intervenções da unidade'),
(N'FrmHabilitarUnidad.dgvIntervenciones.IdOrdenMantenimiento.HeaderText',N'Ordem'),
(N'FrmHabilitarUnidad.dgvIntervenciones.IdIntervencionMantenimiento.HeaderText',N'Intervenção'),
(N'FrmHabilitarUnidad.dgvIntervenciones.FechaFin.HeaderText',N'Término'),
(N'FrmHabilitarUnidad.dgvIntervenciones.TrabajoRealizado.HeaderText',N'Trabalho realizado'),
(N'FrmHabilitarUnidad.dgvIntervenciones.Resultado.HeaderText',N'Resultado'),
(N'FrmHabilitarUnidad.dgvIntervenciones.Observaciones.HeaderText',N'Observações'),
(N'FrmHabilitarUnidad.grpdgvInformes.Text',N'Histórico de disponibilidade'),
(N'FrmHabilitarUnidad.dgvInformes.IdInformeDisponibilidad.HeaderText',N'Relatório'),
(N'FrmHabilitarUnidad.dgvInformes.FechaHora.HeaderText',N'Data e hora'),
(N'FrmHabilitarUnidad.dgvInformes.Disponible.HeaderText',N'Disponível'),
(N'FrmHabilitarUnidad.dgvInformes.EstadoUnidad.HeaderText',N'Estado da unidade'),
(N'FrmHabilitarUnidad.dgvInformes.Observaciones.HeaderText',N'Observações'),
(N'FrmHabilitarUnidad.dgvInformes.Vigente.HeaderText',N'Vigente'),
(N'FrmHabilitarUnidad.lbltxtObservaciones.Text',N'Observações'),
(N'FrmHabilitarUnidad.btnHabilitar.Text',N'Confirmar habilitação'),
(N'FrmHabilitarUnidad.btnActualizar.Text',N'Atualizar'),
(N'FrmHabilitarUnidad.grphabilitacion.Text',N'Verificação de condições'),
(N'FrmDisponibilidadFlota.Title',N'Consultar disponibilidade e atribuir unidade'),
(N'FrmDisponibilidadFlota.grpdgvViajes.Text',N'Viagens a iniciar'),
(N'FrmDisponibilidadFlota.dgvViajes.IdViaje.HeaderText',N'Viagem'),
(N'FrmDisponibilidadFlota.dgvViajes.Numero.HeaderText',N'Número'),
(N'FrmDisponibilidadFlota.dgvViajes.FechaPrevista.HeaderText',N'Data prevista'),
(N'FrmDisponibilidadFlota.dgvViajes.Estado.HeaderText',N'Estado'),
(N'FrmDisponibilidadFlota.dgvViajes.IdUnidadFlota.HeaderText',N'Unidade'),
(N'FrmDisponibilidadFlota.dgvViajes.IdInformeDisponibilidad.HeaderText',N'Relatório'),
(N'FrmDisponibilidadFlota.grpdgvUnidades.Text',N'Unidades disponíveis para a viagem selecionada'),
(N'FrmDisponibilidadFlota.dgvUnidades.IdUnidadFlota.HeaderText',N'Unidade'),
(N'FrmDisponibilidadFlota.dgvUnidades.Dominio.HeaderText',N'Placa'),
(N'FrmDisponibilidadFlota.dgvUnidades.Tipo.HeaderText',N'Tipo'),
(N'FrmDisponibilidadFlota.dgvUnidades.Capacidad.HeaderText',N'Capacidade'),
(N'FrmDisponibilidadFlota.dgvUnidades.KilometrajeActual.HeaderText',N'Quilometragem atual'),
(N'FrmDisponibilidadFlota.dgvUnidades.EstadoOperativo.HeaderText',N'Estado operacional'),
(N'FrmDisponibilidadFlota.grpdgvInformes.Text',N'Relatórios vigentes das unidades disponíveis'),
(N'FrmDisponibilidadFlota.dgvInformes.IdInformeDisponibilidad.HeaderText',N'Relatório'),
(N'FrmDisponibilidadFlota.dgvInformes.IdUnidadFlota.HeaderText',N'Unidade'),
(N'FrmDisponibilidadFlota.dgvInformes.FechaHora.HeaderText',N'Data e hora'),
(N'FrmDisponibilidadFlota.dgvInformes.Disponible.HeaderText',N'Disponível'),
(N'FrmDisponibilidadFlota.dgvInformes.Observaciones.HeaderText',N'Observações'),
(N'FrmDisponibilidadFlota.btnAsignar.Text',N'Atribuir unidade'),
(N'FrmDisponibilidadFlota.btnActualizar.Text',N'Atualizar'),
(N'FrmDisponibilidadFlota.grpasignacion.Text',N'Atribuição de unidade à viagem selecionada');
INSERT dbo.TRADUCCION(Id_Idioma,Clave_Traduccion,Valor_Traduccion)
SELECT @IdIdioma_pt_BR,Clave,Valor FROM @MF M WHERE NOT EXISTS(SELECT 1 FROM dbo.TRADUCCION T WHERE T.Id_Idioma=@IdIdioma_pt_BR AND T.Clave_Traduccion=M.Clave);
