CREATE PROC [dbo].[BACKUP_BD]
    @Ruta varchar(260)
AS
BEGIN
    ALTER DATABASE NUEVAIngSoftv2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    RESTORE DATABASE NUEVAIngSoftv2 FROM DISK = @Ruta WITH REPLACE;
    ALTER DATABASE NUEVAIngSoftv2 SET MULTI_USER;
END