CREATE PROCEDURE dbo.MF_LISTAR_INFORMES @IdUnidadFlota INT=NULL AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
SELECT * FROM dbo.INFORME_DISPONIBILIDAD WHERE @IdUnidadFlota IS NULL OR IdUnidadFlota=@IdUnidadFlota ORDER BY IdInformeDisponibilidad DESC;
END;
