CREATE PROCEDURE dbo.TD_RECIBIR_REQUERIMIENTO @Numero NVARCHAR(50), @Origen NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;
    IF NULLIF(LTRIM(RTRIM(@Numero)), '') IS NULL OR NULLIF(LTRIM(RTRIM(@Origen)), '') IS NULL THROW 50002, 'TD.DatosInvalidos', 1;
    INSERT dbo.REQUERIMIENTO_DISTRIBUCION(Numero,Fecha,Origen,Estado) VALUES (@Numero,GETDATE(),@Origen,'Pendiente');
    SELECT CAST(SCOPE_IDENTITY() AS INT) AS Id;
END;
